'use strict';

const regions = [
  {
    id: 1,
    continent_id: 1,
    name: JSON.stringify({
      en: 'Southern Africa',
      de: 'Südliches Afrika',
      it: 'Africa Meridionale',
      ja: '南部アフリカ',
      ko: '남아프리카',
      zh: '南部非洲',
      pt: 'África Austral',
      ru: 'Южная Африка',
      es: 'África Austral',
      fr: 'Afrique australe',
    }),
  },
  {
    id: 2,
    continent_id: 1,
    name: JSON.stringify({
      en: 'Middle Africa',
      de: 'Zentralafrika',
      it: 'Africa Centrale',
      ja: '中部アフリカ',
      ko: '중앙아프리카',
      zh: '中部非洲',
      pt: 'África Central',
      ru: 'Центральная Африка',
      es: 'África Central',
      fr: 'Afrique centrale',
    }),
  },
  {
    id: 3,
    continent_id: 1,
    name: JSON.stringify({
      en: 'Northern Africa',
      de: 'Nordafrika',
      it: 'Africa Settentrionale',
      ja: '北アフリカ',
      ko: '북아프리카',
      zh: '北非',
      pt: 'África do Norte',
      ru: 'Северная Африка',
      es: 'África del Norte',
      fr: 'Afrique du Nord',
    }),
  },
  {
    id: 4,
    continent_id: 1,
    name: JSON.stringify({
      en: 'Western Africa',
      de: 'Westafrika',
      it: 'Africa Occidentale',
      ja: '西アフリカ',
      ko: '서아프리카',
      zh: '西非',
      pt: 'África Ocidental',
      ru: 'Западная Африка',
      es: 'África Occidental',
      fr: 'Afrique occidentale',
    }),
  },
  {
    id: 5,
    continent_id: 1,
    name: JSON.stringify({
      en: 'Eastern Africa',
      de: 'Ostafrika',
      it: 'Africa Orientale',
      ja: '東アフリカ',
      ko: '동아프리카',
      zh: '东非',
      pt: 'África Oriental',
      ru: 'Восточная Африка',
      es: 'África Oriental',
      fr: 'Afrique orientale',
    }),
  },
  {
    id: 6,
    continent_id: 2,
    name: JSON.stringify({
      en: 'South America',
      de: 'Südamerika',
      it: 'America del Sud',
      ja: '南アメリカ',
      ko: '남아메리카',
      zh: '南美洲',
      pt: 'América do Sul',
      ru: 'Южная Америка',
      es: 'América del Sur',
      fr: 'Amérique du Sud',
    }),
  },
  {
    id: 7,
    continent_id: 2,
    name: JSON.stringify({
      en: 'Caribbean',
      de: 'Karibik',
      it: 'Caraibi',
      ja: 'カリブ海',
      ko: '카리브해',
      zh: '加勒比地区',
      pt: 'Caribe',
      ru: 'Карибский бассейн',
      es: 'Caribe',
      fr: 'Caraïbes',
    }),
  },
  {
    id: 8,
    continent_id: 2,
    name: JSON.stringify({
      en: 'North America',
      de: 'Nordamerika',
      it: 'America del Nord',
      ja: '北アメリカ',
      ko: '북아메리카',
      zh: '北美洲',
      pt: 'América do Norte',
      ru: 'Северная Америка',
      es: 'América del Norte',
      fr: 'Amérique du Nord',
    }),
  },
  {
    id: 9,
    continent_id: 2,
    name: JSON.stringify({
      en: 'Central America',
      de: 'Mittelamerika',
      it: 'America Centrale',
      ja: '中央アメリカ',
      ko: '중앙아메리카',
      zh: '中美洲',
      pt: 'América Central',
      ru: 'Центральная Америка',
      es: 'América Central',
      fr: 'Amérique centrale',
    }),
  },
  {
    id: 10,
    continent_id: 3,
    name: JSON.stringify({
      en: 'Antarctic',
      de: 'Antarktis',
      it: 'Antartico',
      ja: '南極',
      ko: '남극',
      zh: '南极洲',
      pt: 'Antártica',
      ru: 'Антарктика',
      es: 'Antártica',
      fr: 'Antarctique',
    }),
  },
  {
    id: 11,
    continent_id: 4,
    name: JSON.stringify({
      en: 'Eastern Asia',
      de: 'Ostasien',
      it: 'Asia Orientale',
      ja: '東アジア',
      ko: '동아시아',
      zh: '东亚',
      pt: 'Ásia Oriental',
      ru: 'Восточная Азия',
      es: 'Asia Oriental',
      fr: "Asie de l'Est",
    }),
  },
  {
    id: 12,
    continent_id: 4,
    name: JSON.stringify({
      en: 'Western Asia',
      de: 'Westasien',
      it: 'Asia Occidentale',
      ja: '西アジア',
      ko: '서아시아',
      zh: '西亚',
      pt: 'Ásia Ocidental',
      ru: 'Западная Азия',
      es: 'Asia Occidental',
      fr: 'Asie occidentale',
    }),
  },
  {
    id: 13,
    continent_id: 4,
    name: JSON.stringify({
      en: 'Southern Asia',
      de: 'Südasien',
      it: 'Asia Meridionale',
      ja: '南アジア',
      ko: '남아시아',
      zh: '南亚',
      pt: 'Ásia Meridional',
      ru: 'Южная Азия',
      es: 'Asia Meridional',
      fr: 'Asie méridionale',
    }),
  },
  {
    id: 14,
    continent_id: 4,
    name: JSON.stringify({
      en: 'South-Eastern Asia',
      de: 'Südostasien',
      it: 'Asia Sud-Orientale',
      ja: '東南アジア',
      ko: '동남아시아',
      zh: '东南亚',
      pt: 'Sudeste Asiático',
      ru: 'Юго-Восточная Азия',
      es: 'Sudeste Asiático',
      fr: 'Asie du Sud-Est',
    }),
  },
  {
    id: 15,
    continent_id: 4,
    name: JSON.stringify({
      en: 'Central Asia',
      de: 'Zentralasien',
      it: 'Asia Centrale',
      ja: '中央アジア',
      ko: '중앙아시아',
      zh: '中亚',
      pt: 'Ásia Central',
      ru: 'Центральная Азия',
      es: 'Asia Central',
      fr: 'Asie centrale',
    }),
  },
  {
    id: 16,
    continent_id: 5,
    name: JSON.stringify({
      en: 'Northern Europe',
      de: 'Nordeuropa',
      it: 'Europa Settentrionale',
      ja: '北ヨーロッパ',
      ko: '북유럽',
      zh: '北欧',
      pt: 'Europa do Norte',
      ru: 'Северная Европа',
      es: 'Europa del Norte',
      fr: 'Europe du Nord',
    }),
  },
  {
    id: 17,
    continent_id: 5,
    name: JSON.stringify({
      en: 'Southern Europe',
      de: 'Südeuropa',
      it: 'Europa Meridionale',
      ja: '南ヨーロッパ',
      ko: '남유럽',
      zh: '南欧',
      pt: 'Europa do Sul',
      ru: 'Южная Европа',
      es: 'Europa del Sur',
      fr: 'Europe du Sud',
    }),
  },
  {
    id: 18,
    continent_id: 5,
    name: JSON.stringify({
      en: 'Western Europe',
      de: 'Westeuropa',
      it: 'Europa Occidentale',
      ja: '西ヨーロッパ',
      ko: '서유럽',
      zh: '西欧',
      pt: 'Europa Ocidental',
      ru: 'Западная Европа',
      es: 'Europa Occidental',
      fr: 'Europe occidentale',
    }),
  },
  {
    id: 19,
    continent_id: 5,
    name: JSON.stringify({
      en: 'Southeast Europe',
      de: 'Südosteuropa',
      it: 'Europa Sud-Orientale',
      ja: '南東ヨーロッパ',
      ko: '남동유럽',
      zh: '东南欧',
      pt: 'Sudeste Europeu',
      ru: 'Юго-Восточная Европа',
      es: 'Europa Sudoriental',
      fr: 'Europe du Sud-Est',
    }),
  },
  {
    id: 20,
    continent_id: 5,
    name: JSON.stringify({
      en: 'Central Europe',
      de: 'Mitteleuropa',
      it: 'Europa Centrale',
      ja: '中央ヨーロッパ',
      ko: '중앙유럽',
      zh: '中欧',
      pt: 'Europa Central',
      ru: 'Центральная Европа',
      es: 'Europa Central',
      fr: 'Europe centrale',
    }),
  },
  {
    id: 21,
    continent_id: 5,
    name: JSON.stringify({
      en: 'Eastern Europe',
      de: 'Osteuropa',
      it: 'Europa Orientale',
      ja: '東ヨーロッパ',
      ko: '동유럽',
      zh: '东欧',
      pt: 'Europa Oriental',
      ru: 'Восточная Европа',
      es: 'Europa del Este',
      fr: "Europe de l'Est",
    }),
  },
  {
    id: 22,
    continent_id: 6,
    name: JSON.stringify({
      en: 'Melanesia',
      de: 'Melanesien',
      it: 'Melanesia',
      ja: 'メラネシア',
      ko: '멜라네시아',
      zh: '美拉尼西亚',
      pt: 'Melanésia',
      ru: 'Меланезия',
      es: 'Melanesia',
      fr: 'Mélanésie',
    }),
  },
  {
    id: 23,
    continent_id: 6,
    name: JSON.stringify({
      en: 'Micronesia',
      de: 'Mikronesien',
      it: 'Micronesia',
      ja: 'ミクロネシア',
      ko: '미크로네시아',
      zh: '密克罗尼西亚',
      pt: 'Micronésia',
      ru: 'Микронезия',
      es: 'Micronesia',
      fr: 'Micronésie',
    }),
  },
  {
    id: 24,
    continent_id: 6,
    name: JSON.stringify({
      en: 'Polynesia',
      de: 'Polynesien',
      it: 'Polinesia',
      ja: 'ポリネシア',
      ko: '폴리네시아',
      zh: '波利尼西亚',
      pt: 'Polinésia',
      ru: 'Полинезия',
      es: 'Polinesia',
      fr: 'Polynésie',
    }),
  },
  {
    id: 25,
    continent_id: 6,
    name: JSON.stringify({
      en: 'Australia and New Zealand',
      de: 'Australien und Neuseeland',
      it: 'Australia e Nuova Zelanda',
      ja: 'オーストラリアとニュージーランド',
      ko: '오스트레일리아와 뉴질랜드',
      zh: '澳大利亚和新西兰',
      pt: 'Austrália e Nova Zelândia',
      ru: 'Австралия и Новая Зеландия',
      es: 'Australia y Nueva Zelanda',
      fr: 'Australie et Nouvelle-Zélande',
    }),
  },
];

module.exports = {
  up: async (queryInterface) => {
    for (const region of regions) {
      await queryInterface.bulkInsert('geo_regions', [region], {
        updateOnDuplicate: ['continent_id', 'name'],
      });
    }
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('geo_regions', null, {});
  },
};
