'use strict';

const flags = [
  {
    id: 1,
    name: 'afghanistan',
    emoji: '',
    location: 'afghanistan_location.svg',
    flat_2d: 'afghanistan_flat_2d.svg',
    rounded_2d: 'afghanistan_rounded_2d.svg',
    wave_2d: 'afghanistan_wave_2d.svg',
    flat_3d: 'afghanistan_flat_3d.svg',
    rounded_3d: 'afghanistan_rounded_3d.svg',
    wave_3d: 'afghanistan_wave_3d.svg',
  },
  {
    id: 2,
    name: 'aland',
    emoji: '',
    location: 'aland_location.svg',
    flat_2d: 'aland_flat_2d.svg',
    rounded_2d: 'aland_rounded_2d.svg',
    wave_2d: 'aland_wave_2d.svg',
    flat_3d: 'aland_flat_3d.svg',
    rounded_3d: 'aland_rounded_3d.svg',
    wave_3d: 'aland_wave_3d.svg',
  },
  {
    id: 3,
    name: 'albania',
    emoji: '',
    location: 'albania_location.svg',
    flat_2d: 'albania_flat_2d.svg',
    rounded_2d: 'albania_rounded_2d.svg',
    wave_2d: 'albania_wave_2d.svg',
    flat_3d: 'albania_flat_3d.svg',
    rounded_3d: 'albania_rounded_3d.svg',
    wave_3d: 'albania_wave_3d.svg',
  },
  {
    id: 4,
    name: 'algeria',
    emoji: '',
    location: 'algeria_location.svg',
    flat_2d: 'algeria_flat_2d.svg',
    rounded_2d: 'algeria_rounded_2d.svg',
    wave_2d: 'algeria_wave_2d.svg',
    flat_3d: 'algeria_flat_3d.svg',
    rounded_3d: 'algeria_rounded_3d.svg',
    wave_3d: 'algeria_wave_3d.svg',
  },
  {
    id: 5,
    name: 'american_samoa',
    emoji: '',
    location: 'american_samoa_location.svg',
    flat_2d: 'american_samoa_flat_2d.svg',
    rounded_2d: 'american_samoa_rounded_2d.svg',
    wave_2d: 'american_samoa_wave_2d.svg',
    flat_3d: 'american_samoa_flat_3d.svg',
    rounded_3d: 'american_samoa_rounded_3d.svg',
    wave_3d: 'american_samoa_wave_3d.svg',
  },
  {
    id: 6,
    name: 'andorra',
    emoji: '',
    location: 'andorra_location.svg',
    flat_2d: 'andorra_flat_2d.svg',
    rounded_2d: 'andorra_rounded_2d.svg',
    wave_2d: 'andorra_wave_2d.svg',
    flat_3d: 'andorra_flat_3d.svg',
    rounded_3d: 'andorra_rounded_3d.svg',
    wave_3d: 'andorra_wave_3d.svg',
  },
  {
    id: 7,
    name: 'angola',
    emoji: '',
    location: 'angola_location.svg',
    flat_2d: 'angola_flat_2d.svg',
    rounded_2d: 'angola_rounded_2d.svg',
    wave_2d: 'angola_wave_2d.svg',
    flat_3d: 'angola_flat_3d.svg',
    rounded_3d: 'angola_rounded_3d.svg',
    wave_3d: 'angola_wave_3d.svg',
  },
  {
    id: 8,
    name: 'anguilla',
    emoji: '',
    location: 'anguilla_location.svg',
    flat_2d: 'anguilla_flat_2d.svg',
    rounded_2d: 'anguilla_rounded_2d.svg',
    wave_2d: 'anguilla_wave_2d.svg',
    flat_3d: 'anguilla_flat_3d.svg',
    rounded_3d: 'anguilla_rounded_3d.svg',
    wave_3d: 'anguilla_wave_3d.svg',
  },
  {
    id: 9,
    name: 'antarctica',
    emoji: '',
    location: 'antarctica_location.svg',
    flat_2d: 'antarctica_flat_2d.svg',
    rounded_2d: 'antarctica_rounded_2d.svg',
    wave_2d: 'antarctica_wave_2d.svg',
    flat_3d: 'antarctica_flat_3d.svg',
    rounded_3d: 'antarctica_rounded_3d.svg',
    wave_3d: 'antarctica_wave_3d.svg',
  },
  {
    id: 10,
    name: 'antigua_and_barbuda',
    emoji: '',
    location: 'antigua_and_barbuda_location.svg',
    flat_2d: 'antigua_and_barbuda_flat_2d.svg',
    rounded_2d: 'antigua_and_barbuda_rounded_2d.svg',
    wave_2d: 'antigua_and_barbuda_wave_2d.svg',
    flat_3d: 'antigua_and_barbuda_flat_3d.svg',
    rounded_3d: 'antigua_and_barbuda_rounded_3d.svg',
    wave_3d: 'antigua_and_barbuda_wave_3d.svg',
  },
  {
    id: 11,
    name: 'argentina',
    emoji: '',
    location: 'argentina_location.svg',
    flat_2d: 'argentina_flat_2d.svg',
    rounded_2d: 'argentina_rounded_2d.svg',
    wave_2d: 'argentina_wave_2d.svg',
    flat_3d: 'argentina_flat_3d.svg',
    rounded_3d: 'argentina_rounded_3d.svg',
    wave_3d: 'argentina_wave_3d.svg',
  },
  {
    id: 12,
    name: 'armenia',
    emoji: '',
    location: 'armenia_location.svg',
    flat_2d: 'armenia_flat_2d.svg',
    rounded_2d: 'armenia_rounded_2d.svg',
    wave_2d: 'armenia_wave_2d.svg',
    flat_3d: 'armenia_flat_3d.svg',
    rounded_3d: 'armenia_rounded_3d.svg',
    wave_3d: 'armenia_wave_3d.svg',
  },
  {
    id: 13,
    name: 'aruba',
    emoji: '',
    location: 'aruba_location.svg',
    flat_2d: 'aruba_flat_2d.svg',
    rounded_2d: 'aruba_rounded_2d.svg',
    wave_2d: 'aruba_wave_2d.svg',
    flat_3d: 'aruba_flat_3d.svg',
    rounded_3d: 'aruba_rounded_3d.svg',
    wave_3d: 'aruba_wave_3d.svg',
  },
  {
    id: 14,
    name: 'australia',
    emoji: '',
    location: 'australia_location.svg',
    flat_2d: 'australia_flat_2d.svg',
    rounded_2d: 'australia_rounded_2d.svg',
    wave_2d: 'australia_wave_2d.svg',
    flat_3d: 'australia_flat_3d.svg',
    rounded_3d: 'australia_rounded_3d.svg',
    wave_3d: 'australia_wave_3d.svg',
  },
  {
    id: 15,
    name: 'austria',
    emoji: '',
    location: 'austria_location.svg',
    flat_2d: 'austria_flat_2d.svg',
    rounded_2d: 'austria_rounded_2d.svg',
    wave_2d: 'austria_wave_2d.svg',
    flat_3d: 'austria_flat_3d.svg',
    rounded_3d: 'austria_rounded_3d.svg',
    wave_3d: 'austria_wave_3d.svg',
  },
  {
    id: 16,
    name: 'azerbaijan',
    emoji: '',
    location: 'azerbaijan_location.svg',
    flat_2d: 'azerbaijan_flat_2d.svg',
    rounded_2d: 'azerbaijan_rounded_2d.svg',
    wave_2d: 'azerbaijan_wave_2d.svg',
    flat_3d: 'azerbaijan_flat_3d.svg',
    rounded_3d: 'azerbaijan_rounded_3d.svg',
    wave_3d: 'azerbaijan_wave_3d.svg',
  },
  {
    id: 17,
    name: 'bahamas',
    emoji: '',
    location: 'bahamas_location.svg',
    flat_2d: 'bahamas_flat_2d.svg',
    rounded_2d: 'bahamas_rounded_2d.svg',
    wave_2d: 'bahamas_wave_2d.svg',
    flat_3d: 'bahamas_flat_3d.svg',
    rounded_3d: 'bahamas_rounded_3d.svg',
    wave_3d: 'bahamas_wave_3d.svg',
  },
  {
    id: 18,
    name: 'bahrain',
    emoji: '',
    location: 'bahrain_location.svg',
    flat_2d: 'bahrain_flat_2d.svg',
    rounded_2d: 'bahrain_rounded_2d.svg',
    wave_2d: 'bahrain_wave_2d.svg',
    flat_3d: 'bahrain_flat_3d.svg',
    rounded_3d: 'bahrain_rounded_3d.svg',
    wave_3d: 'bahrain_wave_3d.svg',
  },
  {
    id: 19,
    name: 'bangladesh',
    emoji: '',
    location: 'bangladesh_location.svg',
    flat_2d: 'bangladesh_flat_2d.svg',
    rounded_2d: 'bangladesh_rounded_2d.svg',
    wave_2d: 'bangladesh_wave_2d.svg',
    flat_3d: 'bangladesh_flat_3d.svg',
    rounded_3d: 'bangladesh_rounded_3d.svg',
    wave_3d: 'bangladesh_wave_3d.svg',
  },
  {
    id: 20,
    name: 'barbados',
    emoji: '',
    location: 'barbados_location.svg',
    flat_2d: 'barbados_flat_2d.svg',
    rounded_2d: 'barbados_rounded_2d.svg',
    wave_2d: 'barbados_wave_2d.svg',
    flat_3d: 'barbados_flat_3d.svg',
    rounded_3d: 'barbados_rounded_3d.svg',
    wave_3d: 'barbados_wave_3d.svg',
  },
  {
    id: 21,
    name: 'belarus',
    emoji: '',
    location: 'belarus_location.svg',
    flat_2d: 'belarus_flat_2d.svg',
    rounded_2d: 'belarus_rounded_2d.svg',
    wave_2d: 'belarus_wave_2d.svg',
    flat_3d: 'belarus_flat_3d.svg',
    rounded_3d: 'belarus_rounded_3d.svg',
    wave_3d: 'belarus_wave_3d.svg',
  },
  {
    id: 22,
    name: 'belgium',
    emoji: '',
    location: 'belgium_location.svg',
    flat_2d: 'belgium_flat_2d.svg',
    rounded_2d: 'belgium_rounded_2d.svg',
    wave_2d: 'belgium_wave_2d.svg',
    flat_3d: 'belgium_flat_3d.svg',
    rounded_3d: 'belgium_rounded_3d.svg',
    wave_3d: 'belgium_wave_3d.svg',
  },
  {
    id: 23,
    name: 'belize',
    emoji: '',
    location: 'belize_location.svg',
    flat_2d: 'belize_flat_2d.svg',
    rounded_2d: 'belize_rounded_2d.svg',
    wave_2d: 'belize_wave_2d.svg',
    flat_3d: 'belize_flat_3d.svg',
    rounded_3d: 'belize_rounded_3d.svg',
    wave_3d: 'belize_wave_3d.svg',
  },
  {
    id: 24,
    name: 'benin',
    emoji: '',
    location: 'benin_location.svg',
    flat_2d: 'benin_flat_2d.svg',
    rounded_2d: 'benin_rounded_2d.svg',
    wave_2d: 'benin_wave_2d.svg',
    flat_3d: 'benin_flat_3d.svg',
    rounded_3d: 'benin_rounded_3d.svg',
    wave_3d: 'benin_wave_3d.svg',
  },
  {
    id: 25,
    name: 'bermuda',
    emoji: '',
    location: 'bermuda_location.svg',
    flat_2d: 'bermuda_flat_2d.svg',
    rounded_2d: 'bermuda_rounded_2d.svg',
    wave_2d: 'bermuda_wave_2d.svg',
    flat_3d: 'bermuda_flat_3d.svg',
    rounded_3d: 'bermuda_rounded_3d.svg',
    wave_3d: 'bermuda_wave_3d.svg',
  },
  {
    id: 26,
    name: 'bhutan',
    emoji: '',
    location: 'bhutan_location.svg',
    flat_2d: 'bhutan_flat_2d.svg',
    rounded_2d: 'bhutan_rounded_2d.svg',
    wave_2d: 'bhutan_wave_2d.svg',
    flat_3d: 'bhutan_flat_3d.svg',
    rounded_3d: 'bhutan_rounded_3d.svg',
    wave_3d: 'bhutan_wave_3d.svg',
  },
  {
    id: 27,
    name: 'bolivia',
    emoji: '',
    location: 'bolivia_location.svg',
    flat_2d: 'bolivia_flat_2d.svg',
    rounded_2d: 'bolivia_rounded_2d.svg',
    wave_2d: 'bolivia_wave_2d.svg',
    flat_3d: 'bolivia_flat_3d.svg',
    rounded_3d: 'bolivia_rounded_3d.svg',
    wave_3d: 'bolivia_wave_3d.svg',
  },
  {
    id: 28,
    name: 'bonaire_sint_eustatius_and_saba',
    emoji: '',
    location: 'bonaire_sint_eustatius_and_saba_location.svg',
    flat_2d: 'bonaire_sint_eustatius_and_saba_flat_2d.svg',
    rounded_2d: 'bonaire_sint_eustatius_and_saba_rounded_2d.svg',
    wave_2d: 'bonaire_sint_eustatius_and_saba_wave_2d.svg',
    flat_3d: 'bonaire_sint_eustatius_and_saba_flat_3d.svg',
    rounded_3d: 'bonaire_sint_eustatius_and_saba_rounded_3d.svg',
    wave_3d: 'bonaire_sint_eustatius_and_saba_wave_3d.svg',
  },
  {
    id: 29,
    name: 'bosnia_and_herzegovina',
    emoji: '',
    location: 'bosnia_and_herzegovina_location.svg',
    flat_2d: 'bosnia_and_herzegovina_flat_2d.svg',
    rounded_2d: 'bosnia_and_herzegovina_rounded_2d.svg',
    wave_2d: 'bosnia_and_herzegovina_wave_2d.svg',
    flat_3d: 'bosnia_and_herzegovina_flat_3d.svg',
    rounded_3d: 'bosnia_and_herzegovina_rounded_3d.svg',
    wave_3d: 'bosnia_and_herzegovina_wave_3d.svg',
  },
  {
    id: 30,
    name: 'botswana',
    emoji: '',
    location: 'botswana_location.svg',
    flat_2d: 'botswana_flat_2d.svg',
    rounded_2d: 'botswana_rounded_2d.svg',
    wave_2d: 'botswana_wave_2d.svg',
    flat_3d: 'botswana_flat_3d.svg',
    rounded_3d: 'botswana_rounded_3d.svg',
    wave_3d: 'botswana_wave_3d.svg',
  },
  {
    id: 31,
    name: 'bouvet_island',
    emoji: '',
    location: 'bouvet_island_location.svg',
    flat_2d: 'bouvet_island_flat_2d.svg',
    rounded_2d: 'bouvet_island_rounded_2d.svg',
    wave_2d: 'bouvet_island_wave_2d.svg',
    flat_3d: 'bouvet_island_flat_3d.svg',
    rounded_3d: 'bouvet_island_rounded_3d.svg',
    wave_3d: 'bouvet_island_wave_3d.svg',
  },
  {
    id: 32,
    name: 'brazil',
    emoji: '',
    location: 'brazil_location.svg',
    flat_2d: 'brazil_flat_2d.svg',
    rounded_2d: 'brazil_rounded_2d.svg',
    wave_2d: 'brazil_wave_2d.svg',
    flat_3d: 'brazil_flat_3d.svg',
    rounded_3d: 'brazil_rounded_3d.svg',
    wave_3d: 'brazil_wave_3d.svg',
  },
  {
    id: 33,
    name: 'british_indian_ocean_territory',
    emoji: '',
    location: 'british_indian_ocean_territory_location.svg',
    flat_2d: 'british_indian_ocean_territory_flat_2d.svg',
    rounded_2d: 'british_indian_ocean_territory_rounded_2d.svg',
    wave_2d: 'british_indian_ocean_territory_wave_2d.svg',
    flat_3d: 'british_indian_ocean_territory_flat_3d.svg',
    rounded_3d: 'british_indian_ocean_territory_rounded_3d.svg',
    wave_3d: 'british_indian_ocean_territory_wave_3d.svg',
  },
  {
    id: 34,
    name: 'british_virgin_islands',
    emoji: '',
    location: 'british_virgin_islands_location.svg',
    flat_2d: 'british_virgin_islands_flat_2d.svg',
    rounded_2d: 'british_virgin_islands_rounded_2d.svg',
    wave_2d: 'british_virgin_islands_wave_2d.svg',
    flat_3d: 'british_virgin_islands_flat_3d.svg',
    rounded_3d: 'british_virgin_islands_rounded_3d.svg',
    wave_3d: 'british_virgin_islands_wave_3d.svg',
  },
  {
    id: 35,
    name: 'brunei',
    emoji: '',
    location: 'brunei_location.svg',
    flat_2d: 'brunei_flat_2d.svg',
    rounded_2d: 'brunei_rounded_2d.svg',
    wave_2d: 'brunei_wave_2d.svg',
    flat_3d: 'brunei_flat_3d.svg',
    rounded_3d: 'brunei_rounded_3d.svg',
    wave_3d: 'brunei_wave_3d.svg',
  },
  {
    id: 36,
    name: 'bulgaria',
    emoji: '',
    location: 'bulgaria_location.svg',
    flat_2d: 'bulgaria_flat_2d.svg',
    rounded_2d: 'bulgaria_rounded_2d.svg',
    wave_2d: 'bulgaria_wave_2d.svg',
    flat_3d: 'bulgaria_flat_3d.svg',
    rounded_3d: 'bulgaria_rounded_3d.svg',
    wave_3d: 'bulgaria_wave_3d.svg',
  },
  {
    id: 37,
    name: 'burkina_faso',
    emoji: '',
    location: 'burkina_faso_location.svg',
    flat_2d: 'burkina_faso_flat_2d.svg',
    rounded_2d: 'burkina_faso_rounded_2d.svg',
    wave_2d: 'burkina_faso_wave_2d.svg',
    flat_3d: 'burkina_faso_flat_3d.svg',
    rounded_3d: 'burkina_faso_rounded_3d.svg',
    wave_3d: 'burkina_faso_wave_3d.svg',
  },
  {
    id: 38,
    name: 'burundi',
    emoji: '',
    location: 'burundi_location.svg',
    flat_2d: 'burundi_flat_2d.svg',
    rounded_2d: 'burundi_rounded_2d.svg',
    wave_2d: 'burundi_wave_2d.svg',
    flat_3d: 'burundi_flat_3d.svg',
    rounded_3d: 'burundi_rounded_3d.svg',
    wave_3d: 'burundi_wave_3d.svg',
  },
  {
    id: 39,
    name: 'cabo_verde',
    emoji: '',
    location: 'cabo_verde_location.svg',
    flat_2d: 'cabo_verde_flat_2d.svg',
    rounded_2d: 'cabo_verde_rounded_2d.svg',
    wave_2d: 'cabo_verde_wave_2d.svg',
    flat_3d: 'cabo_verde_flat_3d.svg',
    rounded_3d: 'cabo_verde_rounded_3d.svg',
    wave_3d: 'cabo_verde_wave_3d.svg',
  },
  {
    id: 40,
    name: 'cambodia',
    emoji: '',
    location: 'cambodia_location.svg',
    flat_2d: 'cambodia_flat_2d.svg',
    rounded_2d: 'cambodia_rounded_2d.svg',
    wave_2d: 'cambodia_wave_2d.svg',
    flat_3d: 'cambodia_flat_3d.svg',
    rounded_3d: 'cambodia_rounded_3d.svg',
    wave_3d: 'cambodia_wave_3d.svg',
  },
  {
    id: 41,
    name: 'cameroon',
    emoji: '',
    location: 'cameroon_location.svg',
    flat_2d: 'cameroon_flat_2d.svg',
    rounded_2d: 'cameroon_rounded_2d.svg',
    wave_2d: 'cameroon_wave_2d.svg',
    flat_3d: 'cameroon_flat_3d.svg',
    rounded_3d: 'cameroon_rounded_3d.svg',
    wave_3d: 'cameroon_wave_3d.svg',
  },
  {
    id: 42,
    name: 'canada',
    emoji: '',
    location: 'canada_location.svg',
    flat_2d: 'canada_flat_2d.svg',
    rounded_2d: 'canada_rounded_2d.svg',
    wave_2d: 'canada_wave_2d.svg',
    flat_3d: 'canada_flat_3d.svg',
    rounded_3d: 'canada_rounded_3d.svg',
    wave_3d: 'canada_wave_3d.svg',
  },
  {
    id: 43,
    name: 'cayman_islands',
    emoji: '',
    location: 'cayman_islands_location.svg',
    flat_2d: 'cayman_islands_flat_2d.svg',
    rounded_2d: 'cayman_islands_rounded_2d.svg',
    wave_2d: 'cayman_islands_wave_2d.svg',
    flat_3d: 'cayman_islands_flat_3d.svg',
    rounded_3d: 'cayman_islands_rounded_3d.svg',
    wave_3d: 'cayman_islands_wave_3d.svg',
  },
  {
    id: 44,
    name: 'central_african_republic',
    emoji: '',
    location: 'central_african_republic_location.svg',
    flat_2d: 'central_african_republic_flat_2d.svg',
    rounded_2d: 'central_african_republic_rounded_2d.svg',
    wave_2d: 'central_african_republic_wave_2d.svg',
    flat_3d: 'central_african_republic_flat_3d.svg',
    rounded_3d: 'central_african_republic_rounded_3d.svg',
    wave_3d: 'central_african_republic_wave_3d.svg',
  },
  {
    id: 45,
    name: 'chad',
    emoji: '',
    location: 'chad_location.svg',
    flat_2d: 'chad_flat_2d.svg',
    rounded_2d: 'chad_rounded_2d.svg',
    wave_2d: 'chad_wave_2d.svg',
    flat_3d: 'chad_flat_3d.svg',
    rounded_3d: 'chad_rounded_3d.svg',
    wave_3d: 'chad_wave_3d.svg',
  },
  {
    id: 46,
    name: 'chile',
    emoji: '',
    location: 'chile_location.svg',
    flat_2d: 'chile_flat_2d.svg',
    rounded_2d: 'chile_rounded_2d.svg',
    wave_2d: 'chile_wave_2d.svg',
    flat_3d: 'chile_flat_3d.svg',
    rounded_3d: 'chile_rounded_3d.svg',
    wave_3d: 'chile_wave_3d.svg',
  },
  {
    id: 47,
    name: 'china',
    emoji: '',
    location: 'china_location.svg',
    flat_2d: 'china_flat_2d.svg',
    rounded_2d: 'china_rounded_2d.svg',
    wave_2d: 'china_wave_2d.svg',
    flat_3d: 'china_flat_3d.svg',
    rounded_3d: 'china_rounded_3d.svg',
    wave_3d: 'china_wave_3d.svg',
  },
  {
    id: 48,
    name: 'christmas_island',
    emoji: '',
    location: 'christmas_island_location.svg',
    flat_2d: 'christmas_island_flat_2d.svg',
    rounded_2d: 'christmas_island_rounded_2d.svg',
    wave_2d: 'christmas_island_wave_2d.svg',
    flat_3d: 'christmas_island_flat_3d.svg',
    rounded_3d: 'christmas_island_rounded_3d.svg',
    wave_3d: 'christmas_island_wave_3d.svg',
  },
  {
    id: 49,
    name: 'cocos_keeling_islands',
    emoji: '',
    location: 'cocos_keeling_islands_location.svg',
    flat_2d: 'cocos_keeling_islands_flat_2d.svg',
    rounded_2d: 'cocos_keeling_islands_rounded_2d.svg',
    wave_2d: 'cocos_keeling_islands_wave_2d.svg',
    flat_3d: 'cocos_keeling_islands_flat_3d.svg',
    rounded_3d: 'cocos_keeling_islands_rounded_3d.svg',
    wave_3d: 'cocos_keeling_islands_wave_3d.svg',
  },
  {
    id: 50,
    name: 'colombia',
    emoji: '',
    location: 'colombia_location.svg',
    flat_2d: 'colombia_flat_2d.svg',
    rounded_2d: 'colombia_rounded_2d.svg',
    wave_2d: 'colombia_wave_2d.svg',
    flat_3d: 'colombia_flat_3d.svg',
    rounded_3d: 'colombia_rounded_3d.svg',
    wave_3d: 'colombia_wave_3d.svg',
  },
  {
    id: 51,
    name: 'comoros',
    emoji: '',
    location: 'comoros_location.svg',
    flat_2d: 'comoros_flat_2d.svg',
    rounded_2d: 'comoros_rounded_2d.svg',
    wave_2d: 'comoros_wave_2d.svg',
    flat_3d: 'comoros_flat_3d.svg',
    rounded_3d: 'comoros_rounded_3d.svg',
    wave_3d: 'comoros_wave_3d.svg',
  },
  {
    id: 52,
    name: 'congo_republic',
    emoji: '',
    location: 'congo_republic_location.svg',
    flat_2d: 'congo_republic_flat_2d.svg',
    rounded_2d: 'congo_republic_rounded_2d.svg',
    wave_2d: 'congo_republic_wave_2d.svg',
    flat_3d: 'congo_republic_flat_3d.svg',
    rounded_3d: 'congo_republic_rounded_3d.svg',
    wave_3d: 'congo_republic_wave_3d.svg',
  },
  {
    id: 53,
    name: 'cook_islands',
    emoji: '',
    location: 'cook_islands_location.svg',
    flat_2d: 'cook_islands_flat_2d.svg',
    rounded_2d: 'cook_islands_rounded_2d.svg',
    wave_2d: 'cook_islands_wave_2d.svg',
    flat_3d: 'cook_islands_flat_3d.svg',
    rounded_3d: 'cook_islands_rounded_3d.svg',
    wave_3d: 'cook_islands_wave_3d.svg',
  },
  {
    id: 54,
    name: 'costa_rica',
    emoji: '',
    location: 'costa_rica_location.svg',
    flat_2d: 'costa_rica_flat_2d.svg',
    rounded_2d: 'costa_rica_rounded_2d.svg',
    wave_2d: 'costa_rica_wave_2d.svg',
    flat_3d: 'costa_rica_flat_3d.svg',
    rounded_3d: 'costa_rica_rounded_3d.svg',
    wave_3d: 'costa_rica_wave_3d.svg',
  },
  {
    id: 55,
    name: 'croatia',
    emoji: '',
    location: 'croatia_location.svg',
    flat_2d: 'croatia_flat_2d.svg',
    rounded_2d: 'croatia_rounded_2d.svg',
    wave_2d: 'croatia_wave_2d.svg',
    flat_3d: 'croatia_flat_3d.svg',
    rounded_3d: 'croatia_rounded_3d.svg',
    wave_3d: 'croatia_wave_3d.svg',
  },
  {
    id: 56,
    name: 'cuba',
    emoji: '',
    location: 'cuba_location.svg',
    flat_2d: 'cuba_flat_2d.svg',
    rounded_2d: 'cuba_rounded_2d.svg',
    wave_2d: 'cuba_wave_2d.svg',
    flat_3d: 'cuba_flat_3d.svg',
    rounded_3d: 'cuba_rounded_3d.svg',
    wave_3d: 'cuba_wave_3d.svg',
  },
  {
    id: 57,
    name: 'curaao',
    emoji: '',
    location: 'curaao_location.svg',
    flat_2d: 'curaao_flat_2d.svg',
    rounded_2d: 'curaao_rounded_2d.svg',
    wave_2d: 'curaao_wave_2d.svg',
    flat_3d: 'curaao_flat_3d.svg',
    rounded_3d: 'curaao_rounded_3d.svg',
    wave_3d: 'curaao_wave_3d.svg',
  },
  {
    id: 58,
    name: 'cyprus',
    emoji: '',
    location: 'cyprus_location.svg',
    flat_2d: 'cyprus_flat_2d.svg',
    rounded_2d: 'cyprus_rounded_2d.svg',
    wave_2d: 'cyprus_wave_2d.svg',
    flat_3d: 'cyprus_flat_3d.svg',
    rounded_3d: 'cyprus_rounded_3d.svg',
    wave_3d: 'cyprus_wave_3d.svg',
  },
  {
    id: 59,
    name: 'czechia',
    emoji: '',
    location: 'czechia_location.svg',
    flat_2d: 'czechia_flat_2d.svg',
    rounded_2d: 'czechia_rounded_2d.svg',
    wave_2d: 'czechia_wave_2d.svg',
    flat_3d: 'czechia_flat_3d.svg',
    rounded_3d: 'czechia_rounded_3d.svg',
    wave_3d: 'czechia_wave_3d.svg',
  },
  {
    id: 60,
    name: 'denmark',
    emoji: '',
    location: 'denmark_location.svg',
    flat_2d: 'denmark_flat_2d.svg',
    rounded_2d: 'denmark_rounded_2d.svg',
    wave_2d: 'denmark_wave_2d.svg',
    flat_3d: 'denmark_flat_3d.svg',
    rounded_3d: 'denmark_rounded_3d.svg',
    wave_3d: 'denmark_wave_3d.svg',
  },
  {
    id: 61,
    name: 'djibouti',
    emoji: '',
    location: 'djibouti_location.svg',
    flat_2d: 'djibouti_flat_2d.svg',
    rounded_2d: 'djibouti_rounded_2d.svg',
    wave_2d: 'djibouti_wave_2d.svg',
    flat_3d: 'djibouti_flat_3d.svg',
    rounded_3d: 'djibouti_rounded_3d.svg',
    wave_3d: 'djibouti_wave_3d.svg',
  },
  {
    id: 62,
    name: 'dominica',
    emoji: '',
    location: 'dominica_location.svg',
    flat_2d: 'dominica_flat_2d.svg',
    rounded_2d: 'dominica_rounded_2d.svg',
    wave_2d: 'dominica_wave_2d.svg',
    flat_3d: 'dominica_flat_3d.svg',
    rounded_3d: 'dominica_rounded_3d.svg',
    wave_3d: 'dominica_wave_3d.svg',
  },
  {
    id: 63,
    name: 'dominican_republic',
    emoji: '',
    location: 'dominican_republic_location.svg',
    flat_2d: 'dominican_republic_flat_2d.svg',
    rounded_2d: 'dominican_republic_rounded_2d.svg',
    wave_2d: 'dominican_republic_wave_2d.svg',
    flat_3d: 'dominican_republic_flat_3d.svg',
    rounded_3d: 'dominican_republic_rounded_3d.svg',
    wave_3d: 'dominican_republic_wave_3d.svg',
  },
  {
    id: 64,
    name: 'd_r_congo',
    emoji: '',
    location: 'd_r_congo_location.svg',
    flat_2d: 'd_r_congo_flat_2d.svg',
    rounded_2d: 'd_r_congo_rounded_2d.svg',
    wave_2d: 'd_r_congo_wave_2d.svg',
    flat_3d: 'd_r_congo_flat_3d.svg',
    rounded_3d: 'd_r_congo_rounded_3d.svg',
    wave_3d: 'd_r_congo_wave_3d.svg',
  },
  {
    id: 65,
    name: 'ecuador',
    emoji: '',
    location: 'ecuador_location.svg',
    flat_2d: 'ecuador_flat_2d.svg',
    rounded_2d: 'ecuador_rounded_2d.svg',
    wave_2d: 'ecuador_wave_2d.svg',
    flat_3d: 'ecuador_flat_3d.svg',
    rounded_3d: 'ecuador_rounded_3d.svg',
    wave_3d: 'ecuador_wave_3d.svg',
  },
  {
    id: 66,
    name: 'egypt',
    emoji: '',
    location: 'egypt_location.svg',
    flat_2d: 'egypt_flat_2d.svg',
    rounded_2d: 'egypt_rounded_2d.svg',
    wave_2d: 'egypt_wave_2d.svg',
    flat_3d: 'egypt_flat_3d.svg',
    rounded_3d: 'egypt_rounded_3d.svg',
    wave_3d: 'egypt_wave_3d.svg',
  },
  {
    id: 67,
    name: 'el_salvador',
    emoji: '',
    location: 'el_salvador_location.svg',
    flat_2d: 'el_salvador_flat_2d.svg',
    rounded_2d: 'el_salvador_rounded_2d.svg',
    wave_2d: 'el_salvador_wave_2d.svg',
    flat_3d: 'el_salvador_flat_3d.svg',
    rounded_3d: 'el_salvador_rounded_3d.svg',
    wave_3d: 'el_salvador_wave_3d.svg',
  },
  {
    id: 68,
    name: 'equatorial_guinea',
    emoji: '',
    location: 'equatorial_guinea_location.svg',
    flat_2d: 'equatorial_guinea_flat_2d.svg',
    rounded_2d: 'equatorial_guinea_rounded_2d.svg',
    wave_2d: 'equatorial_guinea_wave_2d.svg',
    flat_3d: 'equatorial_guinea_flat_3d.svg',
    rounded_3d: 'equatorial_guinea_rounded_3d.svg',
    wave_3d: 'equatorial_guinea_wave_3d.svg',
  },
  {
    id: 69,
    name: 'eritrea',
    emoji: '',
    location: 'eritrea_location.svg',
    flat_2d: 'eritrea_flat_2d.svg',
    rounded_2d: 'eritrea_rounded_2d.svg',
    wave_2d: 'eritrea_wave_2d.svg',
    flat_3d: 'eritrea_flat_3d.svg',
    rounded_3d: 'eritrea_rounded_3d.svg',
    wave_3d: 'eritrea_wave_3d.svg',
  },
  {
    id: 70,
    name: 'estonia',
    emoji: '',
    location: 'estonia_location.svg',
    flat_2d: 'estonia_flat_2d.svg',
    rounded_2d: 'estonia_rounded_2d.svg',
    wave_2d: 'estonia_wave_2d.svg',
    flat_3d: 'estonia_flat_3d.svg',
    rounded_3d: 'estonia_rounded_3d.svg',
    wave_3d: 'estonia_wave_3d.svg',
  },
  {
    id: 71,
    name: 'eswatini',
    emoji: '',
    location: 'eswatini_location.svg',
    flat_2d: 'eswatini_flat_2d.svg',
    rounded_2d: 'eswatini_rounded_2d.svg',
    wave_2d: 'eswatini_wave_2d.svg',
    flat_3d: 'eswatini_flat_3d.svg',
    rounded_3d: 'eswatini_rounded_3d.svg',
    wave_3d: 'eswatini_wave_3d.svg',
  },
  {
    id: 72,
    name: 'ethiopia',
    emoji: '',
    location: 'ethiopia_location.svg',
    flat_2d: 'ethiopia_flat_2d.svg',
    rounded_2d: 'ethiopia_rounded_2d.svg',
    wave_2d: 'ethiopia_wave_2d.svg',
    flat_3d: 'ethiopia_flat_3d.svg',
    rounded_3d: 'ethiopia_rounded_3d.svg',
    wave_3d: 'ethiopia_wave_3d.svg',
  },
  {
    id: 73,
    name: 'falkland_islands',
    emoji: '',
    location: 'falkland_islands_location.svg',
    flat_2d: 'falkland_islands_flat_2d.svg',
    rounded_2d: 'falkland_islands_rounded_2d.svg',
    wave_2d: 'falkland_islands_wave_2d.svg',
    flat_3d: 'falkland_islands_flat_3d.svg',
    rounded_3d: 'falkland_islands_rounded_3d.svg',
    wave_3d: 'falkland_islands_wave_3d.svg',
  },
  {
    id: 74,
    name: 'faroe_islands',
    emoji: '',
    location: 'faroe_islands_location.svg',
    flat_2d: 'faroe_islands_flat_2d.svg',
    rounded_2d: 'faroe_islands_rounded_2d.svg',
    wave_2d: 'faroe_islands_wave_2d.svg',
    flat_3d: 'faroe_islands_flat_3d.svg',
    rounded_3d: 'faroe_islands_rounded_3d.svg',
    wave_3d: 'faroe_islands_wave_3d.svg',
  },
  {
    id: 75,
    name: 'fiji',
    emoji: '',
    location: 'fiji_location.svg',
    flat_2d: 'fiji_flat_2d.svg',
    rounded_2d: 'fiji_rounded_2d.svg',
    wave_2d: 'fiji_wave_2d.svg',
    flat_3d: 'fiji_flat_3d.svg',
    rounded_3d: 'fiji_rounded_3d.svg',
    wave_3d: 'fiji_wave_3d.svg',
  },
  {
    id: 76,
    name: 'finland',
    emoji: '',
    location: 'finland_location.svg',
    flat_2d: 'finland_flat_2d.svg',
    rounded_2d: 'finland_rounded_2d.svg',
    wave_2d: 'finland_wave_2d.svg',
    flat_3d: 'finland_flat_3d.svg',
    rounded_3d: 'finland_rounded_3d.svg',
    wave_3d: 'finland_wave_3d.svg',
  },
  {
    id: 77,
    name: 'france',
    emoji: '',
    location: 'france_location.svg',
    flat_2d: 'france_flat_2d.svg',
    rounded_2d: 'france_rounded_2d.svg',
    wave_2d: 'france_wave_2d.svg',
    flat_3d: 'france_flat_3d.svg',
    rounded_3d: 'france_rounded_3d.svg',
    wave_3d: 'france_wave_3d.svg',
  },
  {
    id: 78,
    name: 'french_guiana',
    emoji: '',
    location: 'french_guiana_location.svg',
    flat_2d: 'french_guiana_flat_2d.svg',
    rounded_2d: 'french_guiana_rounded_2d.svg',
    wave_2d: 'french_guiana_wave_2d.svg',
    flat_3d: 'french_guiana_flat_3d.svg',
    rounded_3d: 'french_guiana_rounded_3d.svg',
    wave_3d: 'french_guiana_wave_3d.svg',
  },
  {
    id: 79,
    name: 'french_polynesia',
    emoji: '',
    location: 'french_polynesia_location.svg',
    flat_2d: 'french_polynesia_flat_2d.svg',
    rounded_2d: 'french_polynesia_rounded_2d.svg',
    wave_2d: 'french_polynesia_wave_2d.svg',
    flat_3d: 'french_polynesia_flat_3d.svg',
    rounded_3d: 'french_polynesia_rounded_3d.svg',
    wave_3d: 'french_polynesia_wave_3d.svg',
  },
  {
    id: 80,
    name: 'french_southern_territories',
    emoji: '',
    location: 'french_southern_territories_location.svg',
    flat_2d: 'french_southern_territories_flat_2d.svg',
    rounded_2d: 'french_southern_territories_rounded_2d.svg',
    wave_2d: 'french_southern_territories_wave_2d.svg',
    flat_3d: 'french_southern_territories_flat_3d.svg',
    rounded_3d: 'french_southern_territories_rounded_3d.svg',
    wave_3d: 'french_southern_territories_wave_3d.svg',
  },
  {
    id: 81,
    name: 'gabon',
    emoji: '',
    location: 'gabon_location.svg',
    flat_2d: 'gabon_flat_2d.svg',
    rounded_2d: 'gabon_rounded_2d.svg',
    wave_2d: 'gabon_wave_2d.svg',
    flat_3d: 'gabon_flat_3d.svg',
    rounded_3d: 'gabon_rounded_3d.svg',
    wave_3d: 'gabon_wave_3d.svg',
  },
  {
    id: 82,
    name: 'georgia',
    emoji: '',
    location: 'georgia_location.svg',
    flat_2d: 'georgia_flat_2d.svg',
    rounded_2d: 'georgia_rounded_2d.svg',
    wave_2d: 'georgia_wave_2d.svg',
    flat_3d: 'georgia_flat_3d.svg',
    rounded_3d: 'georgia_rounded_3d.svg',
    wave_3d: 'georgia_wave_3d.svg',
  },
  {
    id: 83,
    name: 'germany',
    emoji: '',
    location: 'germany_location.svg',
    flat_2d: 'germany_flat_2d.svg',
    rounded_2d: 'germany_rounded_2d.svg',
    wave_2d: 'germany_wave_2d.svg',
    flat_3d: 'germany_flat_3d.svg',
    rounded_3d: 'germany_rounded_3d.svg',
    wave_3d: 'germany_wave_3d.svg',
  },
  {
    id: 84,
    name: 'ghana',
    emoji: '',
    location: 'ghana_location.svg',
    flat_2d: 'ghana_flat_2d.svg',
    rounded_2d: 'ghana_rounded_2d.svg',
    wave_2d: 'ghana_wave_2d.svg',
    flat_3d: 'ghana_flat_3d.svg',
    rounded_3d: 'ghana_rounded_3d.svg',
    wave_3d: 'ghana_wave_3d.svg',
  },
  {
    id: 85,
    name: 'gibraltar',
    emoji: '',
    location: 'gibraltar_location.svg',
    flat_2d: 'gibraltar_flat_2d.svg',
    rounded_2d: 'gibraltar_rounded_2d.svg',
    wave_2d: 'gibraltar_wave_2d.svg',
    flat_3d: 'gibraltar_flat_3d.svg',
    rounded_3d: 'gibraltar_rounded_3d.svg',
    wave_3d: 'gibraltar_wave_3d.svg',
  },
  {
    id: 86,
    name: 'greece',
    emoji: '',
    location: 'greece_location.svg',
    flat_2d: 'greece_flat_2d.svg',
    rounded_2d: 'greece_rounded_2d.svg',
    wave_2d: 'greece_wave_2d.svg',
    flat_3d: 'greece_flat_3d.svg',
    rounded_3d: 'greece_rounded_3d.svg',
    wave_3d: 'greece_wave_3d.svg',
  },
  {
    id: 87,
    name: 'greenland',
    emoji: '',
    location: 'greenland_location.svg',
    flat_2d: 'greenland_flat_2d.svg',
    rounded_2d: 'greenland_rounded_2d.svg',
    wave_2d: 'greenland_wave_2d.svg',
    flat_3d: 'greenland_flat_3d.svg',
    rounded_3d: 'greenland_rounded_3d.svg',
    wave_3d: 'greenland_wave_3d.svg',
  },
  {
    id: 88,
    name: 'grenada',
    emoji: '',
    location: 'grenada_location.svg',
    flat_2d: 'grenada_flat_2d.svg',
    rounded_2d: 'grenada_rounded_2d.svg',
    wave_2d: 'grenada_wave_2d.svg',
    flat_3d: 'grenada_flat_3d.svg',
    rounded_3d: 'grenada_rounded_3d.svg',
    wave_3d: 'grenada_wave_3d.svg',
  },
  {
    id: 89,
    name: 'guadeloupe',
    emoji: '',
    location: 'guadeloupe_location.svg',
    flat_2d: 'guadeloupe_flat_2d.svg',
    rounded_2d: 'guadeloupe_rounded_2d.svg',
    wave_2d: 'guadeloupe_wave_2d.svg',
    flat_3d: 'guadeloupe_flat_3d.svg',
    rounded_3d: 'guadeloupe_rounded_3d.svg',
    wave_3d: 'guadeloupe_wave_3d.svg',
  },
  {
    id: 90,
    name: 'guam',
    emoji: '',
    location: 'guam_location.svg',
    flat_2d: 'guam_flat_2d.svg',
    rounded_2d: 'guam_rounded_2d.svg',
    wave_2d: 'guam_wave_2d.svg',
    flat_3d: 'guam_flat_3d.svg',
    rounded_3d: 'guam_rounded_3d.svg',
    wave_3d: 'guam_wave_3d.svg',
  },
  {
    id: 91,
    name: 'guatemala',
    emoji: '',
    location: 'guatemala_location.svg',
    flat_2d: 'guatemala_flat_2d.svg',
    rounded_2d: 'guatemala_rounded_2d.svg',
    wave_2d: 'guatemala_wave_2d.svg',
    flat_3d: 'guatemala_flat_3d.svg',
    rounded_3d: 'guatemala_rounded_3d.svg',
    wave_3d: 'guatemala_wave_3d.svg',
  },
  {
    id: 92,
    name: 'guernsey',
    emoji: '',
    location: 'guernsey_location.svg',
    flat_2d: 'guernsey_flat_2d.svg',
    rounded_2d: 'guernsey_rounded_2d.svg',
    wave_2d: 'guernsey_wave_2d.svg',
    flat_3d: 'guernsey_flat_3d.svg',
    rounded_3d: 'guernsey_rounded_3d.svg',
    wave_3d: 'guernsey_wave_3d.svg',
  },
  {
    id: 93,
    name: 'guinea',
    emoji: '',
    location: 'guinea_location.svg',
    flat_2d: 'guinea_flat_2d.svg',
    rounded_2d: 'guinea_rounded_2d.svg',
    wave_2d: 'guinea_wave_2d.svg',
    flat_3d: 'guinea_flat_3d.svg',
    rounded_3d: 'guinea_rounded_3d.svg',
    wave_3d: 'guinea_wave_3d.svg',
  },
  {
    id: 94,
    name: 'guinea_bissau',
    emoji: '',
    location: 'guinea_bissau_location.svg',
    flat_2d: 'guinea_bissau_flat_2d.svg',
    rounded_2d: 'guinea_bissau_rounded_2d.svg',
    wave_2d: 'guinea_bissau_wave_2d.svg',
    flat_3d: 'guinea_bissau_flat_3d.svg',
    rounded_3d: 'guinea_bissau_rounded_3d.svg',
    wave_3d: 'guinea_bissau_wave_3d.svg',
  },
  {
    id: 95,
    name: 'guyana',
    emoji: '',
    location: 'guyana_location.svg',
    flat_2d: 'guyana_flat_2d.svg',
    rounded_2d: 'guyana_rounded_2d.svg',
    wave_2d: 'guyana_wave_2d.svg',
    flat_3d: 'guyana_flat_3d.svg',
    rounded_3d: 'guyana_rounded_3d.svg',
    wave_3d: 'guyana_wave_3d.svg',
  },
  {
    id: 96,
    name: 'haiti',
    emoji: '',
    location: 'haiti_location.svg',
    flat_2d: 'haiti_flat_2d.svg',
    rounded_2d: 'haiti_rounded_2d.svg',
    wave_2d: 'haiti_wave_2d.svg',
    flat_3d: 'haiti_flat_3d.svg',
    rounded_3d: 'haiti_rounded_3d.svg',
    wave_3d: 'haiti_wave_3d.svg',
  },
  {
    id: 97,
    name: 'heard_and_mc_donald_islands',
    emoji: '',
    location: 'heard_and_mc_donald_islands_location.svg',
    flat_2d: 'heard_and_mc_donald_islands_flat_2d.svg',
    rounded_2d: 'heard_and_mc_donald_islands_rounded_2d.svg',
    wave_2d: 'heard_and_mc_donald_islands_wave_2d.svg',
    flat_3d: 'heard_and_mc_donald_islands_flat_3d.svg',
    rounded_3d: 'heard_and_mc_donald_islands_rounded_3d.svg',
    wave_3d: 'heard_and_mc_donald_islands_wave_3d.svg',
  },
  {
    id: 98,
    name: 'honduras',
    emoji: '',
    location: 'honduras_location.svg',
    flat_2d: 'honduras_flat_2d.svg',
    rounded_2d: 'honduras_rounded_2d.svg',
    wave_2d: 'honduras_wave_2d.svg',
    flat_3d: 'honduras_flat_3d.svg',
    rounded_3d: 'honduras_rounded_3d.svg',
    wave_3d: 'honduras_wave_3d.svg',
  },
  {
    id: 99,
    name: 'hong_kong',
    emoji: '',
    location: 'hong_kong_location.svg',
    flat_2d: 'hong_kong_flat_2d.svg',
    rounded_2d: 'hong_kong_rounded_2d.svg',
    wave_2d: 'hong_kong_wave_2d.svg',
    flat_3d: 'hong_kong_flat_3d.svg',
    rounded_3d: 'hong_kong_rounded_3d.svg',
    wave_3d: 'hong_kong_wave_3d.svg',
  },
  {
    id: 100,
    name: 'hungary',
    emoji: '',
    location: 'hungary_location.svg',
    flat_2d: 'hungary_flat_2d.svg',
    rounded_2d: 'hungary_rounded_2d.svg',
    wave_2d: 'hungary_wave_2d.svg',
    flat_3d: 'hungary_flat_3d.svg',
    rounded_3d: 'hungary_rounded_3d.svg',
    wave_3d: 'hungary_wave_3d.svg',
  },
  {
    id: 101,
    name: 'iceland',
    emoji: '',
    location: 'iceland_location.svg',
    flat_2d: 'iceland_flat_2d.svg',
    rounded_2d: 'iceland_rounded_2d.svg',
    wave_2d: 'iceland_wave_2d.svg',
    flat_3d: 'iceland_flat_3d.svg',
    rounded_3d: 'iceland_rounded_3d.svg',
    wave_3d: 'iceland_wave_3d.svg',
  },
  {
    id: 102,
    name: 'india',
    emoji: '',
    location: 'india_location.svg',
    flat_2d: 'india_flat_2d.svg',
    rounded_2d: 'india_rounded_2d.svg',
    wave_2d: 'india_wave_2d.svg',
    flat_3d: 'india_flat_3d.svg',
    rounded_3d: 'india_rounded_3d.svg',
    wave_3d: 'india_wave_3d.svg',
  },
  {
    id: 103,
    name: 'indonesia',
    emoji: '',
    location: 'indonesia_location.svg',
    flat_2d: 'indonesia_flat_2d.svg',
    rounded_2d: 'indonesia_rounded_2d.svg',
    wave_2d: 'indonesia_wave_2d.svg',
    flat_3d: 'indonesia_flat_3d.svg',
    rounded_3d: 'indonesia_rounded_3d.svg',
    wave_3d: 'indonesia_wave_3d.svg',
  },
  {
    id: 104,
    name: 'iran',
    emoji: '',
    location: 'iran_location.svg',
    flat_2d: 'iran_flat_2d.svg',
    rounded_2d: 'iran_rounded_2d.svg',
    wave_2d: 'iran_wave_2d.svg',
    flat_3d: 'iran_flat_3d.svg',
    rounded_3d: 'iran_rounded_3d.svg',
    wave_3d: 'iran_wave_3d.svg',
  },
  {
    id: 105,
    name: 'iraq',
    emoji: '',
    location: 'iraq_location.svg',
    flat_2d: 'iraq_flat_2d.svg',
    rounded_2d: 'iraq_rounded_2d.svg',
    wave_2d: 'iraq_wave_2d.svg',
    flat_3d: 'iraq_flat_3d.svg',
    rounded_3d: 'iraq_rounded_3d.svg',
    wave_3d: 'iraq_wave_3d.svg',
  },
  {
    id: 106,
    name: 'ireland',
    emoji: '',
    location: 'ireland_location.svg',
    flat_2d: 'ireland_flat_2d.svg',
    rounded_2d: 'ireland_rounded_2d.svg',
    wave_2d: 'ireland_wave_2d.svg',
    flat_3d: 'ireland_flat_3d.svg',
    rounded_3d: 'ireland_rounded_3d.svg',
    wave_3d: 'ireland_wave_3d.svg',
  },
  {
    id: 107,
    name: 'isle_of_man',
    emoji: '',
    location: 'isle_of_man_location.svg',
    flat_2d: 'isle_of_man_flat_2d.svg',
    rounded_2d: 'isle_of_man_rounded_2d.svg',
    wave_2d: 'isle_of_man_wave_2d.svg',
    flat_3d: 'isle_of_man_flat_3d.svg',
    rounded_3d: 'isle_of_man_rounded_3d.svg',
    wave_3d: 'isle_of_man_wave_3d.svg',
  },
  {
    id: 108,
    name: 'israel',
    emoji: '',
    location: 'israel_location.svg',
    flat_2d: 'israel_flat_2d.svg',
    rounded_2d: 'israel_rounded_2d.svg',
    wave_2d: 'israel_wave_2d.svg',
    flat_3d: 'israel_flat_3d.svg',
    rounded_3d: 'israel_rounded_3d.svg',
    wave_3d: 'israel_wave_3d.svg',
  },
  {
    id: 109,
    name: 'italy',
    emoji: '',
    location: 'italy_location.svg',
    flat_2d: 'italy_flat_2d.svg',
    rounded_2d: 'italy_rounded_2d.svg',
    wave_2d: 'italy_wave_2d.svg',
    flat_3d: 'italy_flat_3d.svg',
    rounded_3d: 'italy_rounded_3d.svg',
    wave_3d: 'italy_wave_3d.svg',
  },
  {
    id: 110,
    name: 'ivory_coast',
    emoji: '',
    location: 'ivory_coast_location.svg',
    flat_2d: 'ivory_coast_flat_2d.svg',
    rounded_2d: 'ivory_coast_rounded_2d.svg',
    wave_2d: 'ivory_coast_wave_2d.svg',
    flat_3d: 'ivory_coast_flat_3d.svg',
    rounded_3d: 'ivory_coast_rounded_3d.svg',
    wave_3d: 'ivory_coast_wave_3d.svg',
  },
  {
    id: 111,
    name: 'jamaica',
    emoji: '',
    location: 'jamaica_location.svg',
    flat_2d: 'jamaica_flat_2d.svg',
    rounded_2d: 'jamaica_rounded_2d.svg',
    wave_2d: 'jamaica_wave_2d.svg',
    flat_3d: 'jamaica_flat_3d.svg',
    rounded_3d: 'jamaica_rounded_3d.svg',
    wave_3d: 'jamaica_wave_3d.svg',
  },
  {
    id: 112,
    name: 'japan',
    emoji: '',
    location: 'japan_location.svg',
    flat_2d: 'japan_flat_2d.svg',
    rounded_2d: 'japan_rounded_2d.svg',
    wave_2d: 'japan_wave_2d.svg',
    flat_3d: 'japan_flat_3d.svg',
    rounded_3d: 'japan_rounded_3d.svg',
    wave_3d: 'japan_wave_3d.svg',
  },
  {
    id: 113,
    name: 'jersey',
    emoji: '',
    location: 'jersey_location.svg',
    flat_2d: 'jersey_flat_2d.svg',
    rounded_2d: 'jersey_rounded_2d.svg',
    wave_2d: 'jersey_wave_2d.svg',
    flat_3d: 'jersey_flat_3d.svg',
    rounded_3d: 'jersey_rounded_3d.svg',
    wave_3d: 'jersey_wave_3d.svg',
  },
  {
    id: 114,
    name: 'jordan',
    emoji: '',
    location: 'jordan_location.svg',
    flat_2d: 'jordan_flat_2d.svg',
    rounded_2d: 'jordan_rounded_2d.svg',
    wave_2d: 'jordan_wave_2d.svg',
    flat_3d: 'jordan_flat_3d.svg',
    rounded_3d: 'jordan_rounded_3d.svg',
    wave_3d: 'jordan_wave_3d.svg',
  },
  {
    id: 115,
    name: 'kazakhstan',
    emoji: '',
    location: 'kazakhstan_location.svg',
    flat_2d: 'kazakhstan_flat_2d.svg',
    rounded_2d: 'kazakhstan_rounded_2d.svg',
    wave_2d: 'kazakhstan_wave_2d.svg',
    flat_3d: 'kazakhstan_flat_3d.svg',
    rounded_3d: 'kazakhstan_rounded_3d.svg',
    wave_3d: 'kazakhstan_wave_3d.svg',
  },
  {
    id: 116,
    name: 'kenya',
    emoji: '',
    location: 'kenya_location.svg',
    flat_2d: 'kenya_flat_2d.svg',
    rounded_2d: 'kenya_rounded_2d.svg',
    wave_2d: 'kenya_wave_2d.svg',
    flat_3d: 'kenya_flat_3d.svg',
    rounded_3d: 'kenya_rounded_3d.svg',
    wave_3d: 'kenya_wave_3d.svg',
  },
  {
    id: 117,
    name: 'kiribati',
    emoji: '',
    location: 'kiribati_location.svg',
    flat_2d: 'kiribati_flat_2d.svg',
    rounded_2d: 'kiribati_rounded_2d.svg',
    wave_2d: 'kiribati_wave_2d.svg',
    flat_3d: 'kiribati_flat_3d.svg',
    rounded_3d: 'kiribati_rounded_3d.svg',
    wave_3d: 'kiribati_wave_3d.svg',
  },
  {
    id: 118,
    name: 'kosovo',
    emoji: '',
    location: 'kosovo_location.svg',
    flat_2d: 'kosovo_flat_2d.svg',
    rounded_2d: 'kosovo_rounded_2d.svg',
    wave_2d: 'kosovo_wave_2d.svg',
    flat_3d: 'kosovo_flat_3d.svg',
    rounded_3d: 'kosovo_rounded_3d.svg',
    wave_3d: 'kosovo_wave_3d.svg',
  },
  {
    id: 119,
    name: 'kuwait',
    emoji: '',
    location: 'kuwait_location.svg',
    flat_2d: 'kuwait_flat_2d.svg',
    rounded_2d: 'kuwait_rounded_2d.svg',
    wave_2d: 'kuwait_wave_2d.svg',
    flat_3d: 'kuwait_flat_3d.svg',
    rounded_3d: 'kuwait_rounded_3d.svg',
    wave_3d: 'kuwait_wave_3d.svg',
  },
  {
    id: 120,
    name: 'kyrgyzstan',
    emoji: '',
    location: 'kyrgyzstan_location.svg',
    flat_2d: 'kyrgyzstan_flat_2d.svg',
    rounded_2d: 'kyrgyzstan_rounded_2d.svg',
    wave_2d: 'kyrgyzstan_wave_2d.svg',
    flat_3d: 'kyrgyzstan_flat_3d.svg',
    rounded_3d: 'kyrgyzstan_rounded_3d.svg',
    wave_3d: 'kyrgyzstan_wave_3d.svg',
  },
  {
    id: 121,
    name: 'laos',
    emoji: '',
    location: 'laos_location.svg',
    flat_2d: 'laos_flat_2d.svg',
    rounded_2d: 'laos_rounded_2d.svg',
    wave_2d: 'laos_wave_2d.svg',
    flat_3d: 'laos_flat_3d.svg',
    rounded_3d: 'laos_rounded_3d.svg',
    wave_3d: 'laos_wave_3d.svg',
  },
  {
    id: 122,
    name: 'latvia',
    emoji: '',
    location: 'latvia_location.svg',
    flat_2d: 'latvia_flat_2d.svg',
    rounded_2d: 'latvia_rounded_2d.svg',
    wave_2d: 'latvia_wave_2d.svg',
    flat_3d: 'latvia_flat_3d.svg',
    rounded_3d: 'latvia_rounded_3d.svg',
    wave_3d: 'latvia_wave_3d.svg',
  },
  {
    id: 123,
    name: 'lebanon',
    emoji: '',
    location: 'lebanon_location.svg',
    flat_2d: 'lebanon_flat_2d.svg',
    rounded_2d: 'lebanon_rounded_2d.svg',
    wave_2d: 'lebanon_wave_2d.svg',
    flat_3d: 'lebanon_flat_3d.svg',
    rounded_3d: 'lebanon_rounded_3d.svg',
    wave_3d: 'lebanon_wave_3d.svg',
  },
  {
    id: 124,
    name: 'lesotho',
    emoji: '',
    location: 'lesotho_location.svg',
    flat_2d: 'lesotho_flat_2d.svg',
    rounded_2d: 'lesotho_rounded_2d.svg',
    wave_2d: 'lesotho_wave_2d.svg',
    flat_3d: 'lesotho_flat_3d.svg',
    rounded_3d: 'lesotho_rounded_3d.svg',
    wave_3d: 'lesotho_wave_3d.svg',
  },
  {
    id: 125,
    name: 'liberia',
    emoji: '',
    location: 'liberia_location.svg',
    flat_2d: 'liberia_flat_2d.svg',
    rounded_2d: 'liberia_rounded_2d.svg',
    wave_2d: 'liberia_wave_2d.svg',
    flat_3d: 'liberia_flat_3d.svg',
    rounded_3d: 'liberia_rounded_3d.svg',
    wave_3d: 'liberia_wave_3d.svg',
  },
  {
    id: 126,
    name: 'libya',
    emoji: '',
    location: 'libya_location.svg',
    flat_2d: 'libya_flat_2d.svg',
    rounded_2d: 'libya_rounded_2d.svg',
    wave_2d: 'libya_wave_2d.svg',
    flat_3d: 'libya_flat_3d.svg',
    rounded_3d: 'libya_rounded_3d.svg',
    wave_3d: 'libya_wave_3d.svg',
  },
  {
    id: 127,
    name: 'liechtenstein',
    emoji: '',
    location: 'liechtenstein_location.svg',
    flat_2d: 'liechtenstein_flat_2d.svg',
    rounded_2d: 'liechtenstein_rounded_2d.svg',
    wave_2d: 'liechtenstein_wave_2d.svg',
    flat_3d: 'liechtenstein_flat_3d.svg',
    rounded_3d: 'liechtenstein_rounded_3d.svg',
    wave_3d: 'liechtenstein_wave_3d.svg',
  },
  {
    id: 128,
    name: 'lithuania',
    emoji: '',
    location: 'lithuania_location.svg',
    flat_2d: 'lithuania_flat_2d.svg',
    rounded_2d: 'lithuania_rounded_2d.svg',
    wave_2d: 'lithuania_wave_2d.svg',
    flat_3d: 'lithuania_flat_3d.svg',
    rounded_3d: 'lithuania_rounded_3d.svg',
    wave_3d: 'lithuania_wave_3d.svg',
  },
  {
    id: 129,
    name: 'luxembourg',
    emoji: '',
    location: 'luxembourg_location.svg',
    flat_2d: 'luxembourg_flat_2d.svg',
    rounded_2d: 'luxembourg_rounded_2d.svg',
    wave_2d: 'luxembourg_wave_2d.svg',
    flat_3d: 'luxembourg_flat_3d.svg',
    rounded_3d: 'luxembourg_rounded_3d.svg',
    wave_3d: 'luxembourg_wave_3d.svg',
  },
  {
    id: 130,
    name: 'macao',
    emoji: '',
    location: 'macao_location.svg',
    flat_2d: 'macao_flat_2d.svg',
    rounded_2d: 'macao_rounded_2d.svg',
    wave_2d: 'macao_wave_2d.svg',
    flat_3d: 'macao_flat_3d.svg',
    rounded_3d: 'macao_rounded_3d.svg',
    wave_3d: 'macao_wave_3d.svg',
  },
  {
    id: 131,
    name: 'madagascar',
    emoji: '',
    location: 'madagascar_location.svg',
    flat_2d: 'madagascar_flat_2d.svg',
    rounded_2d: 'madagascar_rounded_2d.svg',
    wave_2d: 'madagascar_wave_2d.svg',
    flat_3d: 'madagascar_flat_3d.svg',
    rounded_3d: 'madagascar_rounded_3d.svg',
    wave_3d: 'madagascar_wave_3d.svg',
  },
  {
    id: 132,
    name: 'malawi',
    emoji: '',
    location: 'malawi_location.svg',
    flat_2d: 'malawi_flat_2d.svg',
    rounded_2d: 'malawi_rounded_2d.svg',
    wave_2d: 'malawi_wave_2d.svg',
    flat_3d: 'malawi_flat_3d.svg',
    rounded_3d: 'malawi_rounded_3d.svg',
    wave_3d: 'malawi_wave_3d.svg',
  },
  {
    id: 133,
    name: 'malaysia',
    emoji: '',
    location: 'malaysia_location.svg',
    flat_2d: 'malaysia_flat_2d.svg',
    rounded_2d: 'malaysia_rounded_2d.svg',
    wave_2d: 'malaysia_wave_2d.svg',
    flat_3d: 'malaysia_flat_3d.svg',
    rounded_3d: 'malaysia_rounded_3d.svg',
    wave_3d: 'malaysia_wave_3d.svg',
  },
  {
    id: 134,
    name: 'maldives',
    emoji: '',
    location: 'maldives_location.svg',
    flat_2d: 'maldives_flat_2d.svg',
    rounded_2d: 'maldives_rounded_2d.svg',
    wave_2d: 'maldives_wave_2d.svg',
    flat_3d: 'maldives_flat_3d.svg',
    rounded_3d: 'maldives_rounded_3d.svg',
    wave_3d: 'maldives_wave_3d.svg',
  },
  {
    id: 135,
    name: 'mali',
    emoji: '',
    location: 'mali_location.svg',
    flat_2d: 'mali_flat_2d.svg',
    rounded_2d: 'mali_rounded_2d.svg',
    wave_2d: 'mali_wave_2d.svg',
    flat_3d: 'mali_flat_3d.svg',
    rounded_3d: 'mali_rounded_3d.svg',
    wave_3d: 'mali_wave_3d.svg',
  },
  {
    id: 136,
    name: 'malta',
    emoji: '',
    location: 'malta_location.svg',
    flat_2d: 'malta_flat_2d.svg',
    rounded_2d: 'malta_rounded_2d.svg',
    wave_2d: 'malta_wave_2d.svg',
    flat_3d: 'malta_flat_3d.svg',
    rounded_3d: 'malta_rounded_3d.svg',
    wave_3d: 'malta_wave_3d.svg',
  },
  {
    id: 137,
    name: 'marshall_islands',
    emoji: '',
    location: 'marshall_islands_location.svg',
    flat_2d: 'marshall_islands_flat_2d.svg',
    rounded_2d: 'marshall_islands_rounded_2d.svg',
    wave_2d: 'marshall_islands_wave_2d.svg',
    flat_3d: 'marshall_islands_flat_3d.svg',
    rounded_3d: 'marshall_islands_rounded_3d.svg',
    wave_3d: 'marshall_islands_wave_3d.svg',
  },
  {
    id: 138,
    name: 'martinique',
    emoji: '',
    location: 'martinique_location.svg',
    flat_2d: 'martinique_flat_2d.svg',
    rounded_2d: 'martinique_rounded_2d.svg',
    wave_2d: 'martinique_wave_2d.svg',
    flat_3d: 'martinique_flat_3d.svg',
    rounded_3d: 'martinique_rounded_3d.svg',
    wave_3d: 'martinique_wave_3d.svg',
  },
  {
    id: 139,
    name: 'mauritania',
    emoji: '',
    location: 'mauritania_location.svg',
    flat_2d: 'mauritania_flat_2d.svg',
    rounded_2d: 'mauritania_rounded_2d.svg',
    wave_2d: 'mauritania_wave_2d.svg',
    flat_3d: 'mauritania_flat_3d.svg',
    rounded_3d: 'mauritania_rounded_3d.svg',
    wave_3d: 'mauritania_wave_3d.svg',
  },
  {
    id: 140,
    name: 'mauritius',
    emoji: '',
    location: 'mauritius_location.svg',
    flat_2d: 'mauritius_flat_2d.svg',
    rounded_2d: 'mauritius_rounded_2d.svg',
    wave_2d: 'mauritius_wave_2d.svg',
    flat_3d: 'mauritius_flat_3d.svg',
    rounded_3d: 'mauritius_rounded_3d.svg',
    wave_3d: 'mauritius_wave_3d.svg',
  },
  {
    id: 141,
    name: 'mayotte',
    emoji: '',
    location: 'mayotte_location.svg',
    flat_2d: 'mayotte_flat_2d.svg',
    rounded_2d: 'mayotte_rounded_2d.svg',
    wave_2d: 'mayotte_wave_2d.svg',
    flat_3d: 'mayotte_flat_3d.svg',
    rounded_3d: 'mayotte_rounded_3d.svg',
    wave_3d: 'mayotte_wave_3d.svg',
  },
  {
    id: 142,
    name: 'mexico',
    emoji: '',
    location: 'mexico_location.svg',
    flat_2d: 'mexico_flat_2d.svg',
    rounded_2d: 'mexico_rounded_2d.svg',
    wave_2d: 'mexico_wave_2d.svg',
    flat_3d: 'mexico_flat_3d.svg',
    rounded_3d: 'mexico_rounded_3d.svg',
    wave_3d: 'mexico_wave_3d.svg',
  },
  {
    id: 143,
    name: 'micronesia',
    emoji: '',
    location: 'micronesia_location.svg',
    flat_2d: 'micronesia_flat_2d.svg',
    rounded_2d: 'micronesia_rounded_2d.svg',
    wave_2d: 'micronesia_wave_2d.svg',
    flat_3d: 'micronesia_flat_3d.svg',
    rounded_3d: 'micronesia_rounded_3d.svg',
    wave_3d: 'micronesia_wave_3d.svg',
  },
  {
    id: 144,
    name: 'moldova',
    emoji: '',
    location: 'moldova_location.svg',
    flat_2d: 'moldova_flat_2d.svg',
    rounded_2d: 'moldova_rounded_2d.svg',
    wave_2d: 'moldova_wave_2d.svg',
    flat_3d: 'moldova_flat_3d.svg',
    rounded_3d: 'moldova_rounded_3d.svg',
    wave_3d: 'moldova_wave_3d.svg',
  },
  {
    id: 145,
    name: 'monaco',
    emoji: '',
    location: 'monaco_location.svg',
    flat_2d: 'monaco_flat_2d.svg',
    rounded_2d: 'monaco_rounded_2d.svg',
    wave_2d: 'monaco_wave_2d.svg',
    flat_3d: 'monaco_flat_3d.svg',
    rounded_3d: 'monaco_rounded_3d.svg',
    wave_3d: 'monaco_wave_3d.svg',
  },
  {
    id: 146,
    name: 'mongolia',
    emoji: '',
    location: 'mongolia_location.svg',
    flat_2d: 'mongolia_flat_2d.svg',
    rounded_2d: 'mongolia_rounded_2d.svg',
    wave_2d: 'mongolia_wave_2d.svg',
    flat_3d: 'mongolia_flat_3d.svg',
    rounded_3d: 'mongolia_rounded_3d.svg',
    wave_3d: 'mongolia_wave_3d.svg',
  },
  {
    id: 147,
    name: 'montenegro',
    emoji: '',
    location: 'montenegro_location.svg',
    flat_2d: 'montenegro_flat_2d.svg',
    rounded_2d: 'montenegro_rounded_2d.svg',
    wave_2d: 'montenegro_wave_2d.svg',
    flat_3d: 'montenegro_flat_3d.svg',
    rounded_3d: 'montenegro_rounded_3d.svg',
    wave_3d: 'montenegro_wave_3d.svg',
  },
  {
    id: 148,
    name: 'montserrat',
    emoji: '',
    location: 'montserrat_location.svg',
    flat_2d: 'montserrat_flat_2d.svg',
    rounded_2d: 'montserrat_rounded_2d.svg',
    wave_2d: 'montserrat_wave_2d.svg',
    flat_3d: 'montserrat_flat_3d.svg',
    rounded_3d: 'montserrat_rounded_3d.svg',
    wave_3d: 'montserrat_wave_3d.svg',
  },
  {
    id: 149,
    name: 'morocco',
    emoji: '',
    location: 'morocco_location.svg',
    flat_2d: 'morocco_flat_2d.svg',
    rounded_2d: 'morocco_rounded_2d.svg',
    wave_2d: 'morocco_wave_2d.svg',
    flat_3d: 'morocco_flat_3d.svg',
    rounded_3d: 'morocco_rounded_3d.svg',
    wave_3d: 'morocco_wave_3d.svg',
  },
  {
    id: 150,
    name: 'mozambique',
    emoji: '',
    location: 'mozambique_location.svg',
    flat_2d: 'mozambique_flat_2d.svg',
    rounded_2d: 'mozambique_rounded_2d.svg',
    wave_2d: 'mozambique_wave_2d.svg',
    flat_3d: 'mozambique_flat_3d.svg',
    rounded_3d: 'mozambique_rounded_3d.svg',
    wave_3d: 'mozambique_wave_3d.svg',
  },
  {
    id: 151,
    name: 'myanmar',
    emoji: '',
    location: 'myanmar_location.svg',
    flat_2d: 'myanmar_flat_2d.svg',
    rounded_2d: 'myanmar_rounded_2d.svg',
    wave_2d: 'myanmar_wave_2d.svg',
    flat_3d: 'myanmar_flat_3d.svg',
    rounded_3d: 'myanmar_rounded_3d.svg',
    wave_3d: 'myanmar_wave_3d.svg',
  },
  {
    id: 152,
    name: 'namibia',
    emoji: '',
    location: 'namibia_location.svg',
    flat_2d: 'namibia_flat_2d.svg',
    rounded_2d: 'namibia_rounded_2d.svg',
    wave_2d: 'namibia_wave_2d.svg',
    flat_3d: 'namibia_flat_3d.svg',
    rounded_3d: 'namibia_rounded_3d.svg',
    wave_3d: 'namibia_wave_3d.svg',
  },
  {
    id: 153,
    name: 'nauru',
    emoji: '',
    location: 'nauru_location.svg',
    flat_2d: 'nauru_flat_2d.svg',
    rounded_2d: 'nauru_rounded_2d.svg',
    wave_2d: 'nauru_wave_2d.svg',
    flat_3d: 'nauru_flat_3d.svg',
    rounded_3d: 'nauru_rounded_3d.svg',
    wave_3d: 'nauru_wave_3d.svg',
  },
  {
    id: 154,
    name: 'nepal',
    emoji: '',
    location: 'nepal_location.svg',
    flat_2d: 'nepal_flat_2d.svg',
    rounded_2d: 'nepal_rounded_2d.svg',
    wave_2d: 'nepal_wave_2d.svg',
    flat_3d: 'nepal_flat_3d.svg',
    rounded_3d: 'nepal_rounded_3d.svg',
    wave_3d: 'nepal_wave_3d.svg',
  },
  {
    id: 155,
    name: 'new_caledonia',
    emoji: '',
    location: 'new_caledonia_location.svg',
    flat_2d: 'new_caledonia_flat_2d.svg',
    rounded_2d: 'new_caledonia_rounded_2d.svg',
    wave_2d: 'new_caledonia_wave_2d.svg',
    flat_3d: 'new_caledonia_flat_3d.svg',
    rounded_3d: 'new_caledonia_rounded_3d.svg',
    wave_3d: 'new_caledonia_wave_3d.svg',
  },
  {
    id: 156,
    name: 'new_zealand',
    emoji: '',
    location: 'new_zealand_location.svg',
    flat_2d: 'new_zealand_flat_2d.svg',
    rounded_2d: 'new_zealand_rounded_2d.svg',
    wave_2d: 'new_zealand_wave_2d.svg',
    flat_3d: 'new_zealand_flat_3d.svg',
    rounded_3d: 'new_zealand_rounded_3d.svg',
    wave_3d: 'new_zealand_wave_3d.svg',
  },
  {
    id: 157,
    name: 'nicaragua',
    emoji: '',
    location: 'nicaragua_location.svg',
    flat_2d: 'nicaragua_flat_2d.svg',
    rounded_2d: 'nicaragua_rounded_2d.svg',
    wave_2d: 'nicaragua_wave_2d.svg',
    flat_3d: 'nicaragua_flat_3d.svg',
    rounded_3d: 'nicaragua_rounded_3d.svg',
    wave_3d: 'nicaragua_wave_3d.svg',
  },
  {
    id: 158,
    name: 'niger',
    emoji: '',
    location: 'niger_location.svg',
    flat_2d: 'niger_flat_2d.svg',
    rounded_2d: 'niger_rounded_2d.svg',
    wave_2d: 'niger_wave_2d.svg',
    flat_3d: 'niger_flat_3d.svg',
    rounded_3d: 'niger_rounded_3d.svg',
    wave_3d: 'niger_wave_3d.svg',
  },
  {
    id: 159,
    name: 'nigeria',
    emoji: '',
    location: 'nigeria_location.svg',
    flat_2d: 'nigeria_flat_2d.svg',
    rounded_2d: 'nigeria_rounded_2d.svg',
    wave_2d: 'nigeria_wave_2d.svg',
    flat_3d: 'nigeria_flat_3d.svg',
    rounded_3d: 'nigeria_rounded_3d.svg',
    wave_3d: 'nigeria_wave_3d.svg',
  },
  {
    id: 160,
    name: 'niue',
    emoji: '',
    location: 'niue_location.svg',
    flat_2d: 'niue_flat_2d.svg',
    rounded_2d: 'niue_rounded_2d.svg',
    wave_2d: 'niue_wave_2d.svg',
    flat_3d: 'niue_flat_3d.svg',
    rounded_3d: 'niue_rounded_3d.svg',
    wave_3d: 'niue_wave_3d.svg',
  },
  {
    id: 161,
    name: 'norfolk_island',
    emoji: '',
    location: 'norfolk_island_location.svg',
    flat_2d: 'norfolk_island_flat_2d.svg',
    rounded_2d: 'norfolk_island_rounded_2d.svg',
    wave_2d: 'norfolk_island_wave_2d.svg',
    flat_3d: 'norfolk_island_flat_3d.svg',
    rounded_3d: 'norfolk_island_rounded_3d.svg',
    wave_3d: 'norfolk_island_wave_3d.svg',
  },
  {
    id: 162,
    name: 'north_korea',
    emoji: '',
    location: 'north_korea_location.svg',
    flat_2d: 'north_korea_flat_2d.svg',
    rounded_2d: 'north_korea_rounded_2d.svg',
    wave_2d: 'north_korea_wave_2d.svg',
    flat_3d: 'north_korea_flat_3d.svg',
    rounded_3d: 'north_korea_rounded_3d.svg',
    wave_3d: 'north_korea_wave_3d.svg',
  },
  {
    id: 163,
    name: 'north_macedonia',
    emoji: '',
    location: 'north_macedonia_location.svg',
    flat_2d: 'north_macedonia_flat_2d.svg',
    rounded_2d: 'north_macedonia_rounded_2d.svg',
    wave_2d: 'north_macedonia_wave_2d.svg',
    flat_3d: 'north_macedonia_flat_3d.svg',
    rounded_3d: 'north_macedonia_rounded_3d.svg',
    wave_3d: 'north_macedonia_wave_3d.svg',
  },
  {
    id: 164,
    name: 'northern_mariana_islands',
    emoji: '',
    location: 'northern_mariana_islands_location.svg',
    flat_2d: 'northern_mariana_islands_flat_2d.svg',
    rounded_2d: 'northern_mariana_islands_rounded_2d.svg',
    wave_2d: 'northern_mariana_islands_wave_2d.svg',
    flat_3d: 'northern_mariana_islands_flat_3d.svg',
    rounded_3d: 'northern_mariana_islands_rounded_3d.svg',
    wave_3d: 'northern_mariana_islands_wave_3d.svg',
  },
  {
    id: 165,
    name: 'norway',
    emoji: '',
    location: 'norway_location.svg',
    flat_2d: 'norway_flat_2d.svg',
    rounded_2d: 'norway_rounded_2d.svg',
    wave_2d: 'norway_wave_2d.svg',
    flat_3d: 'norway_flat_3d.svg',
    rounded_3d: 'norway_rounded_3d.svg',
    wave_3d: 'norway_wave_3d.svg',
  },
  {
    id: 166,
    name: 'oman',
    emoji: '',
    location: 'oman_location.svg',
    flat_2d: 'oman_flat_2d.svg',
    rounded_2d: 'oman_rounded_2d.svg',
    wave_2d: 'oman_wave_2d.svg',
    flat_3d: 'oman_flat_3d.svg',
    rounded_3d: 'oman_rounded_3d.svg',
    wave_3d: 'oman_wave_3d.svg',
  },
  {
    id: 167,
    name: 'pakistan',
    emoji: '',
    location: 'pakistan_location.svg',
    flat_2d: 'pakistan_flat_2d.svg',
    rounded_2d: 'pakistan_rounded_2d.svg',
    wave_2d: 'pakistan_wave_2d.svg',
    flat_3d: 'pakistan_flat_3d.svg',
    rounded_3d: 'pakistan_rounded_3d.svg',
    wave_3d: 'pakistan_wave_3d.svg',
  },
  {
    id: 168,
    name: 'palau',
    emoji: '',
    location: 'palau_location.svg',
    flat_2d: 'palau_flat_2d.svg',
    rounded_2d: 'palau_rounded_2d.svg',
    wave_2d: 'palau_wave_2d.svg',
    flat_3d: 'palau_flat_3d.svg',
    rounded_3d: 'palau_rounded_3d.svg',
    wave_3d: 'palau_wave_3d.svg',
  },
  {
    id: 169,
    name: 'palestine',
    emoji: '',
    location: 'palestine_location.svg',
    flat_2d: 'palestine_flat_2d.svg',
    rounded_2d: 'palestine_rounded_2d.svg',
    wave_2d: 'palestine_wave_2d.svg',
    flat_3d: 'palestine_flat_3d.svg',
    rounded_3d: 'palestine_rounded_3d.svg',
    wave_3d: 'palestine_wave_3d.svg',
  },
  {
    id: 170,
    name: 'panama',
    emoji: '',
    location: 'panama_location.svg',
    flat_2d: 'panama_flat_2d.svg',
    rounded_2d: 'panama_rounded_2d.svg',
    wave_2d: 'panama_wave_2d.svg',
    flat_3d: 'panama_flat_3d.svg',
    rounded_3d: 'panama_rounded_3d.svg',
    wave_3d: 'panama_wave_3d.svg',
  },
  {
    id: 171,
    name: 'papua_new_guinea',
    emoji: '',
    location: 'papua_new_guinea_location.svg',
    flat_2d: 'papua_new_guinea_flat_2d.svg',
    rounded_2d: 'papua_new_guinea_rounded_2d.svg',
    wave_2d: 'papua_new_guinea_wave_2d.svg',
    flat_3d: 'papua_new_guinea_flat_3d.svg',
    rounded_3d: 'papua_new_guinea_rounded_3d.svg',
    wave_3d: 'papua_new_guinea_wave_3d.svg',
  },
  {
    id: 172,
    name: 'paraguay',
    emoji: '',
    location: 'paraguay_location.svg',
    flat_2d: 'paraguay_flat_2d.svg',
    rounded_2d: 'paraguay_rounded_2d.svg',
    wave_2d: 'paraguay_wave_2d.svg',
    flat_3d: 'paraguay_flat_3d.svg',
    rounded_3d: 'paraguay_rounded_3d.svg',
    wave_3d: 'paraguay_wave_3d.svg',
  },
  {
    id: 173,
    name: 'peru',
    emoji: '',
    location: 'peru_location.svg',
    flat_2d: 'peru_flat_2d.svg',
    rounded_2d: 'peru_rounded_2d.svg',
    wave_2d: 'peru_wave_2d.svg',
    flat_3d: 'peru_flat_3d.svg',
    rounded_3d: 'peru_rounded_3d.svg',
    wave_3d: 'peru_wave_3d.svg',
  },
  {
    id: 174,
    name: 'philippines',
    emoji: '',
    location: 'philippines_location.svg',
    flat_2d: 'philippines_flat_2d.svg',
    rounded_2d: 'philippines_rounded_2d.svg',
    wave_2d: 'philippines_wave_2d.svg',
    flat_3d: 'philippines_flat_3d.svg',
    rounded_3d: 'philippines_rounded_3d.svg',
    wave_3d: 'philippines_wave_3d.svg',
  },
  {
    id: 175,
    name: 'pitcairn_islands',
    emoji: '',
    location: 'pitcairn_islands_location.svg',
    flat_2d: 'pitcairn_islands_flat_2d.svg',
    rounded_2d: 'pitcairn_islands_rounded_2d.svg',
    wave_2d: 'pitcairn_islands_wave_2d.svg',
    flat_3d: 'pitcairn_islands_flat_3d.svg',
    rounded_3d: 'pitcairn_islands_rounded_3d.svg',
    wave_3d: 'pitcairn_islands_wave_3d.svg',
  },
  {
    id: 176,
    name: 'poland',
    emoji: '',
    location: 'poland_location.svg',
    flat_2d: 'poland_flat_2d.svg',
    rounded_2d: 'poland_rounded_2d.svg',
    wave_2d: 'poland_wave_2d.svg',
    flat_3d: 'poland_flat_3d.svg',
    rounded_3d: 'poland_rounded_3d.svg',
    wave_3d: 'poland_wave_3d.svg',
  },
  {
    id: 177,
    name: 'portugal',
    emoji: '',
    location: 'portugal_location.svg',
    flat_2d: 'portugal_flat_2d.svg',
    rounded_2d: 'portugal_rounded_2d.svg',
    wave_2d: 'portugal_wave_2d.svg',
    flat_3d: 'portugal_flat_3d.svg',
    rounded_3d: 'portugal_rounded_3d.svg',
    wave_3d: 'portugal_wave_3d.svg',
  },
  {
    id: 178,
    name: 'puerto_rico',
    emoji: '',
    location: 'puerto_rico_location.svg',
    flat_2d: 'puerto_rico_flat_2d.svg',
    rounded_2d: 'puerto_rico_rounded_2d.svg',
    wave_2d: 'puerto_rico_wave_2d.svg',
    flat_3d: 'puerto_rico_flat_3d.svg',
    rounded_3d: 'puerto_rico_rounded_3d.svg',
    wave_3d: 'puerto_rico_wave_3d.svg',
  },
  {
    id: 179,
    name: 'qatar',
    emoji: '',
    location: 'qatar_location.svg',
    flat_2d: 'qatar_flat_2d.svg',
    rounded_2d: 'qatar_rounded_2d.svg',
    wave_2d: 'qatar_wave_2d.svg',
    flat_3d: 'qatar_flat_3d.svg',
    rounded_3d: 'qatar_rounded_3d.svg',
    wave_3d: 'qatar_wave_3d.svg',
  },
  {
    id: 180,
    name: 'reunion',
    emoji: '',
    location: 'reunion_location.svg',
    flat_2d: 'reunion_flat_2d.svg',
    rounded_2d: 'reunion_rounded_2d.svg',
    wave_2d: 'reunion_wave_2d.svg',
    flat_3d: 'reunion_flat_3d.svg',
    rounded_3d: 'reunion_rounded_3d.svg',
    wave_3d: 'reunion_wave_3d.svg',
  },
  {
    id: 181,
    name: 'romania',
    emoji: '',
    location: 'romania_location.svg',
    flat_2d: 'romania_flat_2d.svg',
    rounded_2d: 'romania_rounded_2d.svg',
    wave_2d: 'romania_wave_2d.svg',
    flat_3d: 'romania_flat_3d.svg',
    rounded_3d: 'romania_rounded_3d.svg',
    wave_3d: 'romania_wave_3d.svg',
  },
  {
    id: 182,
    name: 'russia',
    emoji: '',
    location: 'russia_location.svg',
    flat_2d: 'russia_flat_2d.svg',
    rounded_2d: 'russia_rounded_2d.svg',
    wave_2d: 'russia_wave_2d.svg',
    flat_3d: 'russia_flat_3d.svg',
    rounded_3d: 'russia_rounded_3d.svg',
    wave_3d: 'russia_wave_3d.svg',
  },
  {
    id: 183,
    name: 'rwanda',
    emoji: '',
    location: 'rwanda_location.svg',
    flat_2d: 'rwanda_flat_2d.svg',
    rounded_2d: 'rwanda_rounded_2d.svg',
    wave_2d: 'rwanda_wave_2d.svg',
    flat_3d: 'rwanda_flat_3d.svg',
    rounded_3d: 'rwanda_rounded_3d.svg',
    wave_3d: 'rwanda_wave_3d.svg',
  },
  {
    id: 184,
    name: 'saint_barthelemy',
    emoji: '',
    location: 'saint_barthelemy_location.svg',
    flat_2d: 'saint_barthelemy_flat_2d.svg',
    rounded_2d: 'saint_barthelemy_rounded_2d.svg',
    wave_2d: 'saint_barthelemy_wave_2d.svg',
    flat_3d: 'saint_barthelemy_flat_3d.svg',
    rounded_3d: 'saint_barthelemy_rounded_3d.svg',
    wave_3d: 'saint_barthelemy_wave_3d.svg',
  },
  {
    id: 185,
    name: 'saint_helena',
    emoji: '',
    location: 'saint_helena_location.svg',
    flat_2d: 'saint_helena_flat_2d.svg',
    rounded_2d: 'saint_helena_rounded_2d.svg',
    wave_2d: 'saint_helena_wave_2d.svg',
    flat_3d: 'saint_helena_flat_3d.svg',
    rounded_3d: 'saint_helena_rounded_3d.svg',
    wave_3d: 'saint_helena_wave_3d.svg',
  },
  {
    id: 186,
    name: 'saint_lucia',
    emoji: '',
    location: 'saint_lucia_location.svg',
    flat_2d: 'saint_lucia_flat_2d.svg',
    rounded_2d: 'saint_lucia_rounded_2d.svg',
    wave_2d: 'saint_lucia_wave_2d.svg',
    flat_3d: 'saint_lucia_flat_3d.svg',
    rounded_3d: 'saint_lucia_rounded_3d.svg',
    wave_3d: 'saint_lucia_wave_3d.svg',
  },
  {
    id: 187,
    name: 'saint_martin',
    emoji: '',
    location: 'saint_martin_location.svg',
    flat_2d: 'saint_martin_flat_2d.svg',
    rounded_2d: 'saint_martin_rounded_2d.svg',
    wave_2d: 'saint_martin_wave_2d.svg',
    flat_3d: 'saint_martin_flat_3d.svg',
    rounded_3d: 'saint_martin_rounded_3d.svg',
    wave_3d: 'saint_martin_wave_3d.svg',
  },
  {
    id: 188,
    name: 'saint_pierre_and_miquelon',
    emoji: '',
    location: 'saint_pierre_and_miquelon_location.svg',
    flat_2d: 'saint_pierre_and_miquelon_flat_2d.svg',
    rounded_2d: 'saint_pierre_and_miquelon_rounded_2d.svg',
    wave_2d: 'saint_pierre_and_miquelon_wave_2d.svg',
    flat_3d: 'saint_pierre_and_miquelon_flat_3d.svg',
    rounded_3d: 'saint_pierre_and_miquelon_rounded_3d.svg',
    wave_3d: 'saint_pierre_and_miquelon_wave_3d.svg',
  },
  {
    id: 189,
    name: 'samoa',
    emoji: '',
    location: 'samoa_location.svg',
    flat_2d: 'samoa_flat_2d.svg',
    rounded_2d: 'samoa_rounded_2d.svg',
    wave_2d: 'samoa_wave_2d.svg',
    flat_3d: 'samoa_flat_3d.svg',
    rounded_3d: 'samoa_rounded_3d.svg',
    wave_3d: 'samoa_wave_3d.svg',
  },
  {
    id: 190,
    name: 'san_marino',
    emoji: '',
    location: 'san_marino_location.svg',
    flat_2d: 'san_marino_flat_2d.svg',
    rounded_2d: 'san_marino_rounded_2d.svg',
    wave_2d: 'san_marino_wave_2d.svg',
    flat_3d: 'san_marino_flat_3d.svg',
    rounded_3d: 'san_marino_rounded_3d.svg',
    wave_3d: 'san_marino_wave_3d.svg',
  },
  {
    id: 191,
    name: 'so_tome_and_principe',
    emoji: '',
    location: 'so_tome_and_principe_location.svg',
    flat_2d: 'so_tome_and_principe_flat_2d.svg',
    rounded_2d: 'so_tome_and_principe_rounded_2d.svg',
    wave_2d: 'so_tome_and_principe_wave_2d.svg',
    flat_3d: 'so_tome_and_principe_flat_3d.svg',
    rounded_3d: 'so_tome_and_principe_rounded_3d.svg',
    wave_3d: 'so_tome_and_principe_wave_3d.svg',
  },
  {
    id: 192,
    name: 'saudi_arabia',
    emoji: '',
    location: 'saudi_arabia_location.svg',
    flat_2d: 'saudi_arabia_flat_2d.svg',
    rounded_2d: 'saudi_arabia_rounded_2d.svg',
    wave_2d: 'saudi_arabia_wave_2d.svg',
    flat_3d: 'saudi_arabia_flat_3d.svg',
    rounded_3d: 'saudi_arabia_rounded_3d.svg',
    wave_3d: 'saudi_arabia_wave_3d.svg',
  },
  {
    id: 193,
    name: 'senegal',
    emoji: '',
    location: 'senegal_location.svg',
    flat_2d: 'senegal_flat_2d.svg',
    rounded_2d: 'senegal_rounded_2d.svg',
    wave_2d: 'senegal_wave_2d.svg',
    flat_3d: 'senegal_flat_3d.svg',
    rounded_3d: 'senegal_rounded_3d.svg',
    wave_3d: 'senegal_wave_3d.svg',
  },
  {
    id: 194,
    name: 'serbia',
    emoji: '',
    location: 'serbia_location.svg',
    flat_2d: 'serbia_flat_2d.svg',
    rounded_2d: 'serbia_rounded_2d.svg',
    wave_2d: 'serbia_wave_2d.svg',
    flat_3d: 'serbia_flat_3d.svg',
    rounded_3d: 'serbia_rounded_3d.svg',
    wave_3d: 'serbia_wave_3d.svg',
  },
  {
    id: 195,
    name: 'seychelles',
    emoji: '',
    location: 'seychelles_location.svg',
    flat_2d: 'seychelles_flat_2d.svg',
    rounded_2d: 'seychelles_rounded_2d.svg',
    wave_2d: 'seychelles_wave_2d.svg',
    flat_3d: 'seychelles_flat_3d.svg',
    rounded_3d: 'seychelles_rounded_3d.svg',
    wave_3d: 'seychelles_wave_3d.svg',
  },
  {
    id: 196,
    name: 'sierra_leone',
    emoji: '',
    location: 'sierra_leone_location.svg',
    flat_2d: 'sierra_leone_flat_2d.svg',
    rounded_2d: 'sierra_leone_rounded_2d.svg',
    wave_2d: 'sierra_leone_wave_2d.svg',
    flat_3d: 'sierra_leone_flat_3d.svg',
    rounded_3d: 'sierra_leone_rounded_3d.svg',
    wave_3d: 'sierra_leone_wave_3d.svg',
  },
  {
    id: 197,
    name: 'singapore',
    emoji: '',
    location: 'singapore_location.svg',
    flat_2d: 'singapore_flat_2d.svg',
    rounded_2d: 'singapore_rounded_2d.svg',
    wave_2d: 'singapore_wave_2d.svg',
    flat_3d: 'singapore_flat_3d.svg',
    rounded_3d: 'singapore_rounded_3d.svg',
    wave_3d: 'singapore_wave_3d.svg',
  },
  {
    id: 198,
    name: 'sint_maarten',
    emoji: '',
    location: 'sint_maarten_location.svg',
    flat_2d: 'sint_maarten_flat_2d.svg',
    rounded_2d: 'sint_maarten_rounded_2d.svg',
    wave_2d: 'sint_maarten_wave_2d.svg',
    flat_3d: 'sint_maarten_flat_3d.svg',
    rounded_3d: 'sint_maarten_rounded_3d.svg',
    wave_3d: 'sint_maarten_wave_3d.svg',
  },
  {
    id: 199,
    name: 'slovakia',
    emoji: '',
    location: 'slovakia_location.svg',
    flat_2d: 'slovakia_flat_2d.svg',
    rounded_2d: 'slovakia_rounded_2d.svg',
    wave_2d: 'slovakia_wave_2d.svg',
    flat_3d: 'slovakia_flat_3d.svg',
    rounded_3d: 'slovakia_rounded_3d.svg',
    wave_3d: 'slovakia_wave_3d.svg',
  },
  {
    id: 200,
    name: 'slovenia',
    emoji: '',
    location: 'slovenia_location.svg',
    flat_2d: 'slovenia_flat_2d.svg',
    rounded_2d: 'slovenia_rounded_2d.svg',
    wave_2d: 'slovenia_wave_2d.svg',
    flat_3d: 'slovenia_flat_3d.svg',
    rounded_3d: 'slovenia_rounded_3d.svg',
    wave_3d: 'slovenia_wave_3d.svg',
  },
  {
    id: 201,
    name: 'solomon_islands',
    emoji: '',
    location: 'solomon_islands_location.svg',
    flat_2d: 'solomon_islands_flat_2d.svg',
    rounded_2d: 'solomon_islands_rounded_2d.svg',
    wave_2d: 'solomon_islands_wave_2d.svg',
    flat_3d: 'solomon_islands_flat_3d.svg',
    rounded_3d: 'solomon_islands_rounded_3d.svg',
    wave_3d: 'solomon_islands_wave_3d.svg',
  },
  {
    id: 202,
    name: 'somalia',
    emoji: '',
    location: 'somalia_location.svg',
    flat_2d: 'somalia_flat_2d.svg',
    rounded_2d: 'somalia_rounded_2d.svg',
    wave_2d: 'somalia_wave_2d.svg',
    flat_3d: 'somalia_flat_3d.svg',
    rounded_3d: 'somalia_rounded_3d.svg',
    wave_3d: 'somalia_wave_3d.svg',
  },
  {
    id: 203,
    name: 'south_africa',
    emoji: '',
    location: 'south_africa_location.svg',
    flat_2d: 'south_africa_flat_2d.svg',
    rounded_2d: 'south_africa_rounded_2d.svg',
    wave_2d: 'south_africa_wave_2d.svg',
    flat_3d: 'south_africa_flat_3d.svg',
    rounded_3d: 'south_africa_rounded_3d.svg',
    wave_3d: 'south_africa_wave_3d.svg',
  },
  {
    id: 204,
    name: 'south_georgia_and_south_sandwich_islands',
    emoji: '',
    location: 'south_georgia_and_south_sandwich_islands_location.svg',
    flat_2d: 'south_georgia_and_south_sandwich_islands_flat_2d.svg',
    rounded_2d: 'south_georgia_and_south_sandwich_islands_rounded_2d.svg',
    wave_2d: 'south_georgia_and_south_sandwich_islands_wave_2d.svg',
    flat_3d: 'south_georgia_and_south_sandwich_islands_flat_3d.svg',
    rounded_3d: 'south_georgia_and_south_sandwich_islands_rounded_3d.svg',
    wave_3d: 'south_georgia_and_south_sandwich_islands_wave_3d.svg',
  },
  {
    id: 205,
    name: 'south_korea',
    emoji: '',
    location: 'south_korea_location.svg',
    flat_2d: 'south_korea_flat_2d.svg',
    rounded_2d: 'south_korea_rounded_2d.svg',
    wave_2d: 'south_korea_wave_2d.svg',
    flat_3d: 'south_korea_flat_3d.svg',
    rounded_3d: 'south_korea_rounded_3d.svg',
    wave_3d: 'south_korea_wave_3d.svg',
  },
  {
    id: 206,
    name: 'south_sudan',
    emoji: '',
    location: 'south_sudan_location.svg',
    flat_2d: 'south_sudan_flat_2d.svg',
    rounded_2d: 'south_sudan_rounded_2d.svg',
    wave_2d: 'south_sudan_wave_2d.svg',
    flat_3d: 'south_sudan_flat_3d.svg',
    rounded_3d: 'south_sudan_rounded_3d.svg',
    wave_3d: 'south_sudan_wave_3d.svg',
  },
  {
    id: 207,
    name: 'spain',
    emoji: '',
    location: 'spain_location.svg',
    flat_2d: 'spain_flat_2d.svg',
    rounded_2d: 'spain_rounded_2d.svg',
    wave_2d: 'spain_wave_2d.svg',
    flat_3d: 'spain_flat_3d.svg',
    rounded_3d: 'spain_rounded_3d.svg',
    wave_3d: 'spain_wave_3d.svg',
  },
  {
    id: 208,
    name: 'sri_lanka',
    emoji: '',
    location: 'sri_lanka_location.svg',
    flat_2d: 'sri_lanka_flat_2d.svg',
    rounded_2d: 'sri_lanka_rounded_2d.svg',
    wave_2d: 'sri_lanka_wave_2d.svg',
    flat_3d: 'sri_lanka_flat_3d.svg',
    rounded_3d: 'sri_lanka_rounded_3d.svg',
    wave_3d: 'sri_lanka_wave_3d.svg',
  },
  {
    id: 209,
    name: 'st_kitts_and_nevis',
    emoji: '',
    location: 'st_kitts_and_nevis_location.svg',
    flat_2d: 'st_kitts_and_nevis_flat_2d.svg',
    rounded_2d: 'st_kitts_and_nevis_rounded_2d.svg',
    wave_2d: 'st_kitts_and_nevis_wave_2d.svg',
    flat_3d: 'st_kitts_and_nevis_flat_3d.svg',
    rounded_3d: 'st_kitts_and_nevis_rounded_3d.svg',
    wave_3d: 'st_kitts_and_nevis_wave_3d.svg',
  },
  {
    id: 210,
    name: 'st_vincent_and_grenadines',
    emoji: '',
    location: 'st_vincent_and_grenadines_location.svg',
    flat_2d: 'st_vincent_and_grenadines_flat_2d.svg',
    rounded_2d: 'st_vincent_and_grenadines_rounded_2d.svg',
    wave_2d: 'st_vincent_and_grenadines_wave_2d.svg',
    flat_3d: 'st_vincent_and_grenadines_flat_3d.svg',
    rounded_3d: 'st_vincent_and_grenadines_rounded_3d.svg',
    wave_3d: 'st_vincent_and_grenadines_wave_3d.svg',
  },
  {
    id: 211,
    name: 'sudan',
    emoji: '',
    location: 'sudan_location.svg',
    flat_2d: 'sudan_flat_2d.svg',
    rounded_2d: 'sudan_rounded_2d.svg',
    wave_2d: 'sudan_wave_2d.svg',
    flat_3d: 'sudan_flat_3d.svg',
    rounded_3d: 'sudan_rounded_3d.svg',
    wave_3d: 'sudan_wave_3d.svg',
  },
  {
    id: 212,
    name: 'suriname',
    emoji: '',
    location: 'suriname_location.svg',
    flat_2d: 'suriname_flat_2d.svg',
    rounded_2d: 'suriname_rounded_2d.svg',
    wave_2d: 'suriname_wave_2d.svg',
    flat_3d: 'suriname_flat_3d.svg',
    rounded_3d: 'suriname_rounded_3d.svg',
    wave_3d: 'suriname_wave_3d.svg',
  },
  {
    id: 213,
    name: 'svalbard_and_jan_mayen',
    emoji: '',
    location: 'svalbard_and_jan_mayen_location.svg',
    flat_2d: 'svalbard_and_jan_mayen_flat_2d.svg',
    rounded_2d: 'svalbard_and_jan_mayen_rounded_2d.svg',
    wave_2d: 'svalbard_and_jan_mayen_wave_2d.svg',
    flat_3d: 'svalbard_and_jan_mayen_flat_3d.svg',
    rounded_3d: 'svalbard_and_jan_mayen_rounded_3d.svg',
    wave_3d: 'svalbard_and_jan_mayen_wave_3d.svg',
  },
  {
    id: 214,
    name: 'sweden',
    emoji: '',
    location: 'sweden_location.svg',
    flat_2d: 'sweden_flat_2d.svg',
    rounded_2d: 'sweden_rounded_2d.svg',
    wave_2d: 'sweden_wave_2d.svg',
    flat_3d: 'sweden_flat_3d.svg',
    rounded_3d: 'sweden_rounded_3d.svg',
    wave_3d: 'sweden_wave_3d.svg',
  },
  {
    id: 215,
    name: 'switzerland',
    emoji: '',
    location: 'switzerland_location.svg',
    flat_2d: 'switzerland_flat_2d.svg',
    rounded_2d: 'switzerland_rounded_2d.svg',
    wave_2d: 'switzerland_wave_2d.svg',
    flat_3d: 'switzerland_flat_3d.svg',
    rounded_3d: 'switzerland_rounded_3d.svg',
    wave_3d: 'switzerland_wave_3d.svg',
  },
  {
    id: 216,
    name: 'syria',
    emoji: '',
    location: 'syria_location.svg',
    flat_2d: 'syria_flat_2d.svg',
    rounded_2d: 'syria_rounded_2d.svg',
    wave_2d: 'syria_wave_2d.svg',
    flat_3d: 'syria_flat_3d.svg',
    rounded_3d: 'syria_rounded_3d.svg',
    wave_3d: 'syria_wave_3d.svg',
  },
  {
    id: 217,
    name: 'taiwan',
    emoji: '',
    location: 'taiwan_location.svg',
    flat_2d: 'taiwan_flat_2d.svg',
    rounded_2d: 'taiwan_rounded_2d.svg',
    wave_2d: 'taiwan_wave_2d.svg',
    flat_3d: 'taiwan_flat_3d.svg',
    rounded_3d: 'taiwan_rounded_3d.svg',
    wave_3d: 'taiwan_wave_3d.svg',
  },
  {
    id: 218,
    name: 'tajikistan',
    emoji: '',
    location: 'tajikistan_location.svg',
    flat_2d: 'tajikistan_flat_2d.svg',
    rounded_2d: 'tajikistan_rounded_2d.svg',
    wave_2d: 'tajikistan_wave_2d.svg',
    flat_3d: 'tajikistan_flat_3d.svg',
    rounded_3d: 'tajikistan_rounded_3d.svg',
    wave_3d: 'tajikistan_wave_3d.svg',
  },
  {
    id: 219,
    name: 'tanzania',
    emoji: '',
    location: 'tanzania_location.svg',
    flat_2d: 'tanzania_flat_2d.svg',
    rounded_2d: 'tanzania_rounded_2d.svg',
    wave_2d: 'tanzania_wave_2d.svg',
    flat_3d: 'tanzania_flat_3d.svg',
    rounded_3d: 'tanzania_rounded_3d.svg',
    wave_3d: 'tanzania_wave_3d.svg',
  },
  {
    id: 220,
    name: 'thailand',
    emoji: '',
    location: 'thailand_location.svg',
    flat_2d: 'thailand_flat_2d.svg',
    rounded_2d: 'thailand_rounded_2d.svg',
    wave_2d: 'thailand_wave_2d.svg',
    flat_3d: 'thailand_flat_3d.svg',
    rounded_3d: 'thailand_rounded_3d.svg',
    wave_3d: 'thailand_wave_3d.svg',
  },
  {
    id: 221,
    name: 'the_gambia',
    emoji: '',
    location: 'the_gambia_location.svg',
    flat_2d: 'the_gambia_flat_2d.svg',
    rounded_2d: 'the_gambia_rounded_2d.svg',
    wave_2d: 'the_gambia_wave_2d.svg',
    flat_3d: 'the_gambia_flat_3d.svg',
    rounded_3d: 'the_gambia_rounded_3d.svg',
    wave_3d: 'the_gambia_wave_3d.svg',
  },
  {
    id: 222,
    name: 'the_netherlands',
    emoji: '',
    location: 'the_netherlands_location.svg',
    flat_2d: 'the_netherlands_flat_2d.svg',
    rounded_2d: 'the_netherlands_rounded_2d.svg',
    wave_2d: 'the_netherlands_wave_2d.svg',
    flat_3d: 'the_netherlands_flat_3d.svg',
    rounded_3d: 'the_netherlands_rounded_3d.svg',
    wave_3d: 'the_netherlands_wave_3d.svg',
  },
  {
    id: 223,
    name: 'timor_leste',
    emoji: '',
    location: 'timor_leste_location.svg',
    flat_2d: 'timor_leste_flat_2d.svg',
    rounded_2d: 'timor_leste_rounded_2d.svg',
    wave_2d: 'timor_leste_wave_2d.svg',
    flat_3d: 'timor_leste_flat_3d.svg',
    rounded_3d: 'timor_leste_rounded_3d.svg',
    wave_3d: 'timor_leste_wave_3d.svg',
  },
  {
    id: 224,
    name: 'togo',
    emoji: '',
    location: 'togo_location.svg',
    flat_2d: 'togo_flat_2d.svg',
    rounded_2d: 'togo_rounded_2d.svg',
    wave_2d: 'togo_wave_2d.svg',
    flat_3d: 'togo_flat_3d.svg',
    rounded_3d: 'togo_rounded_3d.svg',
    wave_3d: 'togo_wave_3d.svg',
  },
  {
    id: 225,
    name: 'tokelau',
    emoji: '',
    location: 'tokelau_location.svg',
    flat_2d: 'tokelau_flat_2d.svg',
    rounded_2d: 'tokelau_rounded_2d.svg',
    wave_2d: 'tokelau_wave_2d.svg',
    flat_3d: 'tokelau_flat_3d.svg',
    rounded_3d: 'tokelau_rounded_3d.svg',
    wave_3d: 'tokelau_wave_3d.svg',
  },
  {
    id: 226,
    name: 'tonga',
    emoji: '',
    location: 'tonga_location.svg',
    flat_2d: 'tonga_flat_2d.svg',
    rounded_2d: 'tonga_rounded_2d.svg',
    wave_2d: 'tonga_wave_2d.svg',
    flat_3d: 'tonga_flat_3d.svg',
    rounded_3d: 'tonga_rounded_3d.svg',
    wave_3d: 'tonga_wave_3d.svg',
  },
  {
    id: 227,
    name: 'trinidad_and_tobago',
    emoji: '',
    location: 'trinidad_and_tobago_location.svg',
    flat_2d: 'trinidad_and_tobago_flat_2d.svg',
    rounded_2d: 'trinidad_and_tobago_rounded_2d.svg',
    wave_2d: 'trinidad_and_tobago_wave_2d.svg',
    flat_3d: 'trinidad_and_tobago_flat_3d.svg',
    rounded_3d: 'trinidad_and_tobago_rounded_3d.svg',
    wave_3d: 'trinidad_and_tobago_wave_3d.svg',
  },
  {
    id: 228,
    name: 'tunisia',
    emoji: '',
    location: 'tunisia_location.svg',
    flat_2d: 'tunisia_flat_2d.svg',
    rounded_2d: 'tunisia_rounded_2d.svg',
    wave_2d: 'tunisia_wave_2d.svg',
    flat_3d: 'tunisia_flat_3d.svg',
    rounded_3d: 'tunisia_rounded_3d.svg',
    wave_3d: 'tunisia_wave_3d.svg',
  },
  {
    id: 229,
    name: 'turkiye',
    emoji: '',
    location: 'turkiye_location.svg',
    flat_2d: 'turkiye_flat_2d.svg',
    rounded_2d: 'turkiye_rounded_2d.svg',
    wave_2d: 'turkiye_wave_2d.svg',
    flat_3d: 'turkiye_flat_3d.svg',
    rounded_3d: 'turkiye_rounded_3d.svg',
    wave_3d: 'turkiye_wave_3d.svg',
  },
  {
    id: 230,
    name: 'turkmenistan',
    emoji: '',
    location: 'turkmenistan_location.svg',
    flat_2d: 'turkmenistan_flat_2d.svg',
    rounded_2d: 'turkmenistan_rounded_2d.svg',
    wave_2d: 'turkmenistan_wave_2d.svg',
    flat_3d: 'turkmenistan_flat_3d.svg',
    rounded_3d: 'turkmenistan_rounded_3d.svg',
    wave_3d: 'turkmenistan_wave_3d.svg',
  },
  {
    id: 231,
    name: 'turks_and_caicos_islands',
    emoji: '',
    location: 'turks_and_caicos_islands_location.svg',
    flat_2d: 'turks_and_caicos_islands_flat_2d.svg',
    rounded_2d: 'turks_and_caicos_islands_rounded_2d.svg',
    wave_2d: 'turks_and_caicos_islands_wave_2d.svg',
    flat_3d: 'turks_and_caicos_islands_flat_3d.svg',
    rounded_3d: 'turks_and_caicos_islands_rounded_3d.svg',
    wave_3d: 'turks_and_caicos_islands_wave_3d.svg',
  },
  {
    id: 232,
    name: 'tuvalu',
    emoji: '',
    location: 'tuvalu_location.svg',
    flat_2d: 'tuvalu_flat_2d.svg',
    rounded_2d: 'tuvalu_rounded_2d.svg',
    wave_2d: 'tuvalu_wave_2d.svg',
    flat_3d: 'tuvalu_flat_3d.svg',
    rounded_3d: 'tuvalu_rounded_3d.svg',
    wave_3d: 'tuvalu_wave_3d.svg',
  },
  {
    id: 233,
    name: 'u_s_outlying_islands',
    emoji: '',
    location: 'u_s_outlying_islands_location.svg',
    flat_2d: 'u_s_outlying_islands_flat_2d.svg',
    rounded_2d: 'u_s_outlying_islands_rounded_2d.svg',
    wave_2d: 'u_s_outlying_islands_wave_2d.svg',
    flat_3d: 'u_s_outlying_islands_flat_3d.svg',
    rounded_3d: 'u_s_outlying_islands_rounded_3d.svg',
    wave_3d: 'u_s_outlying_islands_wave_3d.svg',
  },
  {
    id: 234,
    name: 'u_s_virgin_islands',
    emoji: '',
    location: 'u_s_virgin_islands_location.svg',
    flat_2d: 'u_s_virgin_islands_flat_2d.svg',
    rounded_2d: 'u_s_virgin_islands_rounded_2d.svg',
    wave_2d: 'u_s_virgin_islands_wave_2d.svg',
    flat_3d: 'u_s_virgin_islands_flat_3d.svg',
    rounded_3d: 'u_s_virgin_islands_rounded_3d.svg',
    wave_3d: 'u_s_virgin_islands_wave_3d.svg',
  },
  {
    id: 235,
    name: 'uganda',
    emoji: '',
    location: 'uganda_location.svg',
    flat_2d: 'uganda_flat_2d.svg',
    rounded_2d: 'uganda_rounded_2d.svg',
    wave_2d: 'uganda_wave_2d.svg',
    flat_3d: 'uganda_flat_3d.svg',
    rounded_3d: 'uganda_rounded_3d.svg',
    wave_3d: 'uganda_wave_3d.svg',
  },
  {
    id: 236,
    name: 'ukraine',
    emoji: '',
    location: 'ukraine_location.svg',
    flat_2d: 'ukraine_flat_2d.svg',
    rounded_2d: 'ukraine_rounded_2d.svg',
    wave_2d: 'ukraine_wave_2d.svg',
    flat_3d: 'ukraine_flat_3d.svg',
    rounded_3d: 'ukraine_rounded_3d.svg',
    wave_3d: 'ukraine_wave_3d.svg',
  },
  {
    id: 237,
    name: 'united_arab_emirates',
    emoji: '',
    location: 'united_arab_emirates_location.svg',
    flat_2d: 'united_arab_emirates_flat_2d.svg',
    rounded_2d: 'united_arab_emirates_rounded_2d.svg',
    wave_2d: 'united_arab_emirates_wave_2d.svg',
    flat_3d: 'united_arab_emirates_flat_3d.svg',
    rounded_3d: 'united_arab_emirates_rounded_3d.svg',
    wave_3d: 'united_arab_emirates_wave_3d.svg',
  },
  {
    id: 238,
    name: 'united_kingdom',
    emoji: '',
    location: 'united_kingdom_location.svg',
    flat_2d: 'united_kingdom_flat_2d.svg',
    rounded_2d: 'united_kingdom_rounded_2d.svg',
    wave_2d: 'united_kingdom_wave_2d.svg',
    flat_3d: 'united_kingdom_flat_3d.svg',
    rounded_3d: 'united_kingdom_rounded_3d.svg',
    wave_3d: 'united_kingdom_wave_3d.svg',
  },
  {
    id: 239,
    name: 'united_states',
    emoji: '',
    location: 'united_states_location.svg',
    flat_2d: 'united_states_flat_2d.svg',
    rounded_2d: 'united_states_rounded_2d.svg',
    wave_2d: 'united_states_wave_2d.svg',
    flat_3d: 'united_states_flat_3d.svg',
    rounded_3d: 'united_states_rounded_3d.svg',
    wave_3d: 'united_states_wave_3d.svg',
  },
  {
    id: 240,
    name: 'uruguay',
    emoji: '',
    location: 'uruguay_location.svg',
    flat_2d: 'uruguay_flat_2d.svg',
    rounded_2d: 'uruguay_rounded_2d.svg',
    wave_2d: 'uruguay_wave_2d.svg',
    flat_3d: 'uruguay_flat_3d.svg',
    rounded_3d: 'uruguay_rounded_3d.svg',
    wave_3d: 'uruguay_wave_3d.svg',
  },
  {
    id: 241,
    name: 'uzbekistan',
    emoji: '',
    location: 'uzbekistan_location.svg',
    flat_2d: 'uzbekistan_flat_2d.svg',
    rounded_2d: 'uzbekistan_rounded_2d.svg',
    wave_2d: 'uzbekistan_wave_2d.svg',
    flat_3d: 'uzbekistan_flat_3d.svg',
    rounded_3d: 'uzbekistan_rounded_3d.svg',
    wave_3d: 'uzbekistan_wave_3d.svg',
  },
  {
    id: 242,
    name: 'vanuatu',
    emoji: '',
    location: 'vanuatu_location.svg',
    flat_2d: 'vanuatu_flat_2d.svg',
    rounded_2d: 'vanuatu_rounded_2d.svg',
    wave_2d: 'vanuatu_wave_2d.svg',
    flat_3d: 'vanuatu_flat_3d.svg',
    rounded_3d: 'vanuatu_rounded_3d.svg',
    wave_3d: 'vanuatu_wave_3d.svg',
  },
  {
    id: 243,
    name: 'vatican_city',
    emoji: '',
    location: 'vatican_city_location.svg',
    flat_2d: 'vatican_city_flat_2d.svg',
    rounded_2d: 'vatican_city_rounded_2d.svg',
    wave_2d: 'vatican_city_wave_2d.svg',
    flat_3d: 'vatican_city_flat_3d.svg',
    rounded_3d: 'vatican_city_rounded_3d.svg',
    wave_3d: 'vatican_city_wave_3d.svg',
  },
  {
    id: 244,
    name: 'venezuela',
    emoji: '',
    location: 'venezuela_location.svg',
    flat_2d: 'venezuela_flat_2d.svg',
    rounded_2d: 'venezuela_rounded_2d.svg',
    wave_2d: 'venezuela_wave_2d.svg',
    flat_3d: 'venezuela_flat_3d.svg',
    rounded_3d: 'venezuela_rounded_3d.svg',
    wave_3d: 'venezuela_wave_3d.svg',
  },
  {
    id: 245,
    name: 'vietnam',
    emoji: '',
    location: 'vietnam_location.svg',
    flat_2d: 'vietnam_flat_2d.svg',
    rounded_2d: 'vietnam_rounded_2d.svg',
    wave_2d: 'vietnam_wave_2d.svg',
    flat_3d: 'vietnam_flat_3d.svg',
    rounded_3d: 'vietnam_rounded_3d.svg',
    wave_3d: 'vietnam_wave_3d.svg',
  },
  {
    id: 246,
    name: 'wallis_and_futuna',
    emoji: '',
    location: 'wallis_and_futuna_location.svg',
    flat_2d: 'wallis_and_futuna_flat_2d.svg',
    rounded_2d: 'wallis_and_futuna_rounded_2d.svg',
    wave_2d: 'wallis_and_futuna_wave_2d.svg',
    flat_3d: 'wallis_and_futuna_flat_3d.svg',
    rounded_3d: 'wallis_and_futuna_rounded_3d.svg',
    wave_3d: 'wallis_and_futuna_wave_3d.svg',
  },
  {
    id: 247,
    name: 'western_sahara',
    emoji: '',
    location: 'western_sahara_location.svg',
    flat_2d: 'western_sahara_flat_2d.svg',
    rounded_2d: 'western_sahara_rounded_2d.svg',
    wave_2d: 'western_sahara_wave_2d.svg',
    flat_3d: 'western_sahara_flat_3d.svg',
    rounded_3d: 'western_sahara_rounded_3d.svg',
    wave_3d: 'western_sahara_wave_3d.svg',
  },
  {
    id: 248,
    name: 'yemen',
    emoji: '',
    location: 'yemen_location.svg',
    flat_2d: 'yemen_flat_2d.svg',
    rounded_2d: 'yemen_rounded_2d.svg',
    wave_2d: 'yemen_wave_2d.svg',
    flat_3d: 'yemen_flat_3d.svg',
    rounded_3d: 'yemen_rounded_3d.svg',
    wave_3d: 'yemen_wave_3d.svg',
  },
  {
    id: 249,
    name: 'zambia',
    emoji: '',
    location: 'zambia_location.svg',
    flat_2d: 'zambia_flat_2d.svg',
    rounded_2d: 'zambia_rounded_2d.svg',
    wave_2d: 'zambia_wave_2d.svg',
    flat_3d: 'zambia_flat_3d.svg',
    rounded_3d: 'zambia_rounded_3d.svg',
    wave_3d: 'zambia_wave_3d.svg',
  },
  {
    id: 250,
    name: 'zimbabwe',
    emoji: '',
    location: 'zimbabwe_location.svg',
    flat_2d: 'zimbabwe_flat_2d.svg',
    rounded_2d: 'zimbabwe_rounded_2d.svg',
    wave_2d: 'zimbabwe_wave_2d.svg',
    flat_3d: 'zimbabwe_flat_3d.svg',
    rounded_3d: 'zimbabwe_rounded_3d.svg',
    wave_3d: 'zimbabwe_wave_3d.svg',
  },
];

module.exports = {
  up: async (queryInterface) => {
    const batchSize = 10;
    for (let i = 0; i < flags.length; i += batchSize) {
      const batch = flags.slice(i, i + batchSize);
      for (const flag of batch) {
        await queryInterface.bulkInsert('data_flags', [flag], {
          updateOnDuplicate: [
            'name',
            'location',
            'flat_2d',
            'rounded_2d',
            'wave_2d',
            'flat_3d',
            'rounded_3d',
            'wave_3d',
          ],
        });
      }
    }
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('data_flags', null, {});
  },
};
