'use strict';

module.exports = {
  get: () => {
    const subDivisions = [
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Badakhshan',
          de: 'Badakhshan',
          it: 'Badakhshan',
          ja: 'バダフシャーン',
          ko: '바다흐샨',
          zh: '巴达赫尚',
          pt: 'Badakhshan',
          ru: 'Бадахшан',
          es: 'Badakhshan',
          fr: 'Badakhshan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Badghis',
          de: 'Badghis',
          it: 'Badghis',
          ja: 'バードギース',
          ko: '바드기스',
          zh: '巴德吉斯',
          pt: 'Badghis',
          ru: 'Бадагис',
          es: 'Badghis',
          fr: 'Badghis',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Baghlan',
          de: 'Baghlan',
          it: 'Baghlan',
          ja: 'バグラン',
          ko: '바글란',
          zh: '巴格兰',
          pt: 'Baghlan',
          ru: 'Баглан',
          es: 'Baghlan',
          fr: 'Baghlan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Balkh',
          de: 'Balkh',
          it: 'Balkh',
          ja: 'バルフ',
          ko: '발크',
          zh: '巴尔赫',
          pt: 'Balkh',
          ru: 'Балх',
          es: 'Balkh',
          fr: 'Balkh',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Bamyan',
          de: 'Bamyan',
          it: 'Bamyan',
          ja: 'バーミヤン',
          ko: '바미안',
          zh: '巴米扬',
          pt: 'Bamyan',
          ru: 'Бамиан',
          es: 'Bamyan',
          fr: 'Bamyan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Daykundi',
          de: 'Daykundi',
          it: 'Daykundi',
          ja: 'ダイクンディ',
          ko: '다이쿤디',
          zh: '代孔迪',
          pt: 'Daykundi',
          ru: 'Дайкунди',
          es: 'Daykundi',
          fr: 'Daykundi',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Farah',
          de: 'Farah',
          it: 'Farah',
          ja: 'ファラー',
          ko: '파라',
          zh: '法拉',
          pt: 'Farah',
          ru: 'Фарах',
          es: 'Farah',
          fr: 'Farah',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Faryab',
          de: 'Faryab',
          it: 'Faryab',
          ja: 'ファルヤブ',
          ko: '파리야브',
          zh: '法里亚布',
          pt: 'Faryab',
          ru: 'Фарьяб',
          es: 'Faryab',
          fr: 'Faryab',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Ghazni',
          de: 'Ghazni',
          it: 'Ghazni',
          ja: 'ガズニ',
          ko: '가즈니',
          zh: '加兹尼',
          pt: 'Ghazni',
          ru: 'Газни',
          es: 'Ghazni',
          fr: 'Ghazni',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Ghor',
          de: 'Ghor',
          it: 'Ghor',
          ja: 'ゴール',
          ko: '고르',
          zh: '戈尔',
          pt: 'Ghor',
          ru: 'Гор',
          es: 'Ghor',
          fr: 'Ghor',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Helmand',
          de: 'Helmand',
          it: 'Helmand',
          ja: 'ヘルマンド',
          ko: '헬만드',
          zh: '赫尔曼德',
          pt: 'Helmand',
          ru: 'Гильменд',
          es: 'Helmand',
          fr: 'Helmand',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Herat',
          de: 'Herat',
          it: 'Herat',
          ja: 'ヘラート',
          ko: '헤라트',
          zh: '赫拉特',
          pt: 'Herat',
          ru: 'Герат',
          es: 'Herat',
          fr: 'Herat',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Jowzjan',
          de: 'Jowzjan',
          it: 'Jowzjan',
          ja: 'ジョウズジャン',
          ko: '조우즈잔',
          zh: '朱兹詹',
          pt: 'Jowzjan',
          ru: 'Джаузджан',
          es: 'Jowzjan',
          fr: 'Jowzjan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Kabul',
          de: 'Kabul',
          it: 'Kabul',
          ja: 'カーブル',
          ko: '카불',
          zh: '喀布尔',
          pt: 'Cabul',
          ru: 'Кабул',
          es: 'Kabul',
          fr: 'Kaboul',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Kandahar',
          de: 'Kandahar',
          it: 'Kandahar',
          ja: 'カンダハール',
          ko: '칸다하르',
          zh: '坎大哈',
          pt: 'Candaar',
          ru: 'Кандагар',
          es: 'Kandahar',
          fr: 'Kandahar',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Kapisa',
          de: 'Kapisa',
          it: 'Kapisa',
          ja: 'カピサ',
          ko: '카피사',
          zh: '卡皮萨',
          pt: 'Kapisa',
          ru: 'Каписa',
          es: 'Kapisa',
          fr: 'Kapisa',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Khost',
          de: 'Khost',
          it: 'Khost',
          ja: 'ホスト',
          ko: '호스트',
          zh: '霍斯特',
          pt: 'Khost',
          ru: 'Хост',
          es: 'Khost',
          fr: 'Khost',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Kunar',
          de: 'Kunar',
          it: 'Kunar',
          ja: 'クナール',
          ko: '쿠나르',
          zh: '库纳尔',
          pt: 'Kunar',
          ru: 'Кунар',
          es: 'Kunar',
          fr: 'Kunar',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Kunduz',
          de: 'Kunduz',
          it: 'Kunduz',
          ja: 'クンドゥーズ',
          ko: '쿤두즈',
          zh: '昆都士',
          pt: 'Kunduz',
          ru: 'Кундуз',
          es: 'Kunduz',
          fr: 'Kunduz',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Laghman',
          de: 'Laghman',
          it: 'Laghman',
          ja: 'ラグマーン',
          ko: '라그만',
          zh: '拉格曼',
          pt: 'Laghman',
          ru: 'Лагман',
          es: 'Laghman',
          fr: 'Laghman',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Logar',
          de: 'Logar',
          it: 'Logar',
          ja: 'ロガル',
          ko: '로가르',
          zh: '卢格尔',
          pt: 'Logar',
          ru: 'Логар',
          es: 'Logar',
          fr: 'Logar',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Nangarhar',
          de: 'Nangarhar',
          it: 'Nangarhar',
          ja: 'ナンガルハール',
          ko: '낭가르하르',
          zh: '楠格哈尔',
          pt: 'Nangarhar',
          ru: 'Нангархар',
          es: 'Nangarhar',
          fr: 'Nangarhar',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Nimruz',
          de: 'Nimruz',
          it: 'Nimruz',
          ja: 'ニムルーズ',
          ko: '님루즈',
          zh: '尼姆鲁兹',
          pt: 'Nimruz',
          ru: 'Нимруз',
          es: 'Nimruz',
          fr: 'Nimruz',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Nuristan',
          de: 'Nuristan',
          it: 'Nuristan',
          ja: 'ヌリストン',
          ko: '누리스탄',
          zh: '努里斯坦',
          pt: 'Nuristan',
          ru: 'Нуристан',
          es: 'Nuristan',
          fr: 'Nuristan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Uruzgan',
          de: 'Uruzgan',
          it: 'Uruzgan',
          ja: 'ウルズガーン',
          ko: '우루즈간',
          zh: '乌鲁兹甘',
          pt: 'Uruzgan',
          ru: 'Урузган',
          es: 'Uruzgan',
          fr: 'Uruzgan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Paktia',
          de: 'Paktia',
          it: 'Paktia',
          ja: 'パクティア',
          ko: '팍티아',
          zh: '帕克蒂亚',
          pt: 'Paktia',
          ru: 'Пактия',
          es: 'Paktia',
          fr: 'Paktia',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Paktika',
          de: 'Paktika',
          it: 'Paktika',
          ja: 'パクティカ',
          ko: '팍티카',
          zh: '帕克蒂卡',
          pt: 'Paktika',
          ru: 'Пактика',
          es: 'Paktika',
          fr: 'Paktika',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Panjshir',
          de: 'Panjshir',
          it: 'Panjshir',
          ja: 'パンジシール',
          ko: '판지시르',
          zh: '潘杰希尔',
          pt: 'Panjshir',
          ru: 'Панджшер',
          es: 'Panjshir',
          fr: 'Panjshir',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Parwan',
          de: 'Parwan',
          it: 'Parwan',
          ja: 'パルワーン',
          ko: '파르완',
          zh: '帕尔万',
          pt: 'Parwan',
          ru: 'Парван',
          es: 'Parwan',
          fr: 'Parwan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Samangan',
          de: 'Samangan',
          it: 'Samangan',
          ja: 'サマンガーン',
          ko: '사망간',
          zh: '萨曼甘',
          pt: 'Samangan',
          ru: 'Саманган',
          es: 'Samangan',
          fr: 'Samangan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Sar-e Pol',
          de: 'Sar-e Pol',
          it: 'Sar-e Pol',
          ja: 'サレポル',
          ko: '사레폴',
          zh: '萨尔普勒',
          pt: 'Sar-e Pol',
          ru: 'Сари-Пуль',
          es: 'Sar-e Pol',
          fr: 'Sar-e Pol',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Takhar',
          de: 'Takhar',
          it: 'Takhar',
          ja: 'タハール',
          ko: '타하르',
          zh: '塔哈尔',
          pt: 'Takhar',
          ru: 'Тахар',
          es: 'Takhar',
          fr: 'Takhar',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Wardak',
          de: 'Wardak',
          it: 'Wardak',
          ja: 'ワルダク',
          ko: '와르다크',
          zh: '瓦尔达克',
          pt: 'Wardak',
          ru: 'Вардак',
          es: 'Wardak',
          fr: 'Wardak',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Zabul',
          de: 'Zabul',
          it: 'Zabul',
          ja: 'ザーブル',
          ko: '자불',
          zh: '扎布尔',
          pt: 'Zabul',
          ru: 'Забуль',
          es: 'Zabul',
          fr: 'Zabul',
        },
        denomination: 'providence',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Berat',
          de: 'Berat',
          it: 'Berat',
          ja: 'ベラト州',
          ko: '베라트주',
          zh: '培拉特州',
          pt: 'Berat',
          ru: 'Берат',
          es: 'Berat',
          fr: 'Berat',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Dibër',
          de: 'Dibër',
          it: 'Dibër',
          ja: 'ディブラ州',
          ko: '디버르주',
          zh: '第巴尔州',
          pt: 'Dibër',
          ru: 'Дибра',
          es: 'Dibër',
          fr: 'Dibër',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Durrës',
          de: 'Durrës',
          it: 'Durrës',
          ja: 'ドゥラス州',
          ko: '두러스주',
          zh: '杜勒斯州',
          pt: 'Durrës',
          ru: 'Дуррес',
          es: 'Durrës',
          fr: 'Durrës',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Elbasan',
          de: 'Elbasan',
          it: 'Elbasan',
          ja: 'エルバサン州',
          ko: '엘바산주',
          zh: '艾巴申州',
          pt: 'Elbasan',
          ru: 'Эльбасан',
          es: 'Elbasan',
          fr: 'Elbasan',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Fier',
          de: 'Fier',
          it: 'Fier',
          ja: 'フィエル州',
          ko: '피에르주',
          zh: '非夏尔州',
          pt: 'Fier',
          ru: 'Фиери',
          es: 'Fier',
          fr: 'Fier',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Gjirokastër',
          de: 'Gjirokastër',
          it: 'Gjirokastër',
          ja: 'ジロカストラ州',
          ko: '지로카스터르주',
          zh: '吉罗卡斯特州',
          pt: 'Gjirokastër',
          ru: 'Гирокастра',
          es: 'Gjirokastër',
          fr: 'Gjirokastër',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Korçë',
          de: 'Korçë',
          it: 'Korçë',
          ja: 'コルチャ州',
          ko: '코르처주',
          zh: '科赤州',
          pt: 'Korçë',
          ru: 'Корча',
          es: 'Korçë',
          fr: 'Korçë',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Kukës',
          de: 'Kukës',
          it: 'Kukës',
          ja: 'クケス州',
          ko: '쿠커스주',
          zh: '库克斯州',
          pt: 'Kukës',
          ru: 'Кукес',
          es: 'Kukës',
          fr: 'Kukës',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Lezhë',
          de: 'Lezhë',
          it: 'Lezhë',
          ja: 'レジャ州',
          ko: '레저주',
          zh: '列泽州',
          pt: 'Lezhë',
          ru: 'Лежа',
          es: 'Lezhë',
          fr: 'Lezhë',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Shkodër',
          de: 'Shkodër',
          it: 'Shkodër',
          ja: 'シュコドラ州',
          ko: '슈코더르주',
          zh: '士科德州',
          pt: 'Shkodër',
          ru: 'Шкодер',
          es: 'Shkodër',
          fr: 'Shkodër',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Tirana',
          de: 'Tirana',
          it: 'Tirana',
          ja: 'ティラナ州',
          ko: '티라나주',
          zh: '地拉那州',
          pt: 'Tirana',
          ru: 'Тирана',
          es: 'Tirana',
          fr: 'Tirana',
        },
        denomination: 'counties',
      },
      {
        country_id: 2,
        capital_id: null,
        name: {
          en: 'Vlorë',
          de: 'Vlorë',
          it: 'Vlorë',
          ja: 'ヴロラ州',
          ko: '블로러주',
          zh: '夫罗勒州',
          pt: 'Vlorë',
          ru: 'Влёра',
          es: 'Vlorë',
          fr: 'Vlorë',
        },
        denomination: 'counties',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Adrar',
          de: 'Adrar',
          it: 'Adrar',
          ja: 'アドラール',
          ko: '아드라르',
          zh: '阿德拉尔',
          pt: 'Adrar',
          ru: 'Адрар',
          es: 'Adrar',
          fr: 'Adrar',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Chlef',
          de: 'Chlef',
          it: 'Chlef',
          ja: 'シュレフ',
          ko: '슐레프',
          zh: '谢里夫',
          pt: 'Chlef',
          ru: 'Эш-Шелифф',
          es: 'Chlef',
          fr: 'Chlef',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Laghouat',
          de: 'Laghouat',
          it: 'Laghouat',
          ja: 'ラグアット',
          ko: '라구아트',
          zh: '艾格瓦特',
          pt: 'Laghouat',
          ru: 'Лагуат',
          es: 'Laghouat',
          fr: 'Laghouat',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Oum el Bouaghi',
          de: 'Oum el Bouaghi',
          it: 'Oum el Bouaghi',
          ja: 'ウメル・ブアーギ',
          ko: '움엘부아기',
          zh: '乌姆布瓦吉',
          pt: 'Oum el Bouaghi',
          ru: 'Умм-эль-Буаги',
          es: 'Oum el Bouaghi',
          fr: 'Oum el Bouaghi',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Batna',
          de: 'Batna',
          it: 'Batna',
          ja: 'バトナ',
          ko: '바트나',
          zh: '巴特纳',
          pt: 'Batna',
          ru: 'Батна',
          es: 'Batna',
          fr: 'Batna',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Béjaïa',
          de: 'Béjaïa',
          it: 'Béjaïa',
          ja: 'ベジャイア',
          ko: '베자이아',
          zh: '贝贾亚',
          pt: 'Béjaïa',
          ru: 'Беджая',
          es: 'Béjaïa',
          fr: 'Béjaïa',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Biskra',
          de: 'Biskra',
          it: 'Biskra',
          ja: 'ビスクラ',
          ko: '비스크라',
          zh: '比斯克拉',
          pt: 'Biskra',
          ru: 'Бискра',
          es: 'Biskra',
          fr: 'Biskra',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Béchar',
          de: 'Béchar',
          it: 'Béchar',
          ja: 'ベシャール',
          ko: '베샤르',
          zh: '贝沙尔',
          pt: 'Béchar',
          ru: 'Бешар',
          es: 'Béchar',
          fr: 'Béchar',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Blida',
          de: 'Blida',
          it: 'Blida',
          ja: 'ブリダ',
          ko: '블리다',
          zh: '卜利达',
          pt: 'Blida',
          ru: 'Блида',
          es: 'Blida',
          fr: 'Blida',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Bouira',
          de: 'Bouira',
          it: 'Bouira',
          ja: 'ブイラ',
          ko: '부이라',
          zh: '布维拉',
          pt: 'Bouira',
          ru: 'Буира',
          es: 'Bouira',
          fr: 'Bouira',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Tamanrasset',
          de: 'Tamanrasset',
          it: 'Tamanrasset',
          ja: 'タマンラセット',
          ko: '타만라세트',
          zh: '塔曼拉塞特',
          pt: 'Tamanrasset',
          ru: 'Таманрассет',
          es: 'Tamanrasset',
          fr: 'Tamanrasset',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Tébessa',
          de: 'Tébessa',
          it: 'Tébessa',
          ja: 'テベッサ',
          ko: '테베사',
          zh: '泰贝萨',
          pt: 'Tébessa',
          ru: 'Тебесса',
          es: 'Tébessa',
          fr: 'Tébessa',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Tlemcen',
          de: 'Tlemcen',
          it: 'Tlemcen',
          ja: 'トレムセン',
          ko: '틀렘센',
          zh: '特莱姆森',
          pt: 'Tlemcen',
          ru: 'Тлемсен',
          es: 'Tlemcen',
          fr: 'Tlemcen',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Tiaret',
          de: 'Tiaret',
          it: 'Tiaret',
          ja: 'ティアレット',
          ko: '티아레',
          zh: '提亚雷特',
          pt: 'Tiaret',
          ru: 'Тиарет',
          es: 'Tiaret',
          fr: 'Tiaret',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Tizi Ouzou',
          de: 'Tizi Ouzou',
          it: 'Tizi Ouzou',
          ja: 'ティジ・ウズー',
          ko: '티지우주',
          zh: '提济乌祖',
          pt: 'Tizi Ouzou',
          ru: 'Тизи-Узу',
          es: 'Tizi Ouzou',
          fr: 'Tizi Ouzou',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Algiers',
          de: 'Algier',
          it: 'Algeri',
          ja: 'アルジェ',
          ko: '알제',
          zh: '阿尔及尔',
          pt: 'Argel',
          ru: 'Алжир',
          es: 'Argel',
          fr: 'Alger',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Djelfa',
          de: 'Djelfa',
          it: 'Djelfa',
          ja: 'ジェルファ',
          ko: '젤파',
          zh: '杰勒法',
          pt: 'Djelfa',
          ru: 'Джельфа',
          es: 'Djelfa',
          fr: 'Djelfa',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Jijel',
          de: 'Jijel',
          it: 'Jijel',
          ja: 'ジジェル',
          ko: '지젤',
          zh: '吉杰勒',
          pt: 'Jijel',
          ru: 'Джиджель',
          es: 'Jijel',
          fr: 'Jijel',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Sétif',
          de: 'Sétif',
          it: 'Sétif',
          ja: 'セティフ',
          ko: '세티프',
          zh: '塞提夫',
          pt: 'Sétif',
          ru: 'Сетиф',
          es: 'Sétif',
          fr: 'Sétif',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Saïda',
          de: 'Saïda',
          it: 'Saïda',
          ja: 'サイダ',
          ko: '사이다',
          zh: '赛伊达',
          pt: 'Saïda',
          ru: 'Саида',
          es: 'Saïda',
          fr: 'Saïda',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Skikda',
          de: 'Skikda',
          it: 'Skikda',
          ja: 'スキクダ',
          ko: '스킥다',
          zh: '斯基克达',
          pt: 'Skikda',
          ru: 'Скикда',
          es: 'Skikda',
          fr: 'Skikda',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Sidi Bel Abbès',
          de: 'Sidi Bel Abbès',
          it: 'Sidi Bel Abbès',
          ja: 'シディ・ベル・アッベス',
          ko: '시디벨아베스',
          zh: '西迪贝勒阿巴斯',
          pt: 'Sidi Bel Abbès',
          ru: 'Сиди-Бель-Аббес',
          es: 'Sidi Bel Abbès',
          fr: 'Sidi Bel Abbès',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Annaba',
          de: 'Annaba',
          it: 'Annaba',
          ja: 'アンナバ',
          ko: '안나바',
          zh: '安纳巴',
          pt: 'Annaba',
          ru: 'Аннаба',
          es: 'Annaba',
          fr: 'Annaba',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Guelma',
          de: 'Guelma',
          it: 'Guelma',
          ja: 'ゲルマ',
          ko: '겔마',
          zh: '盖勒马',
          pt: 'Guelma',
          ru: 'Гельма',
          es: 'Guelma',
          fr: 'Guelma',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Constantine',
          de: 'Constantine',
          it: 'Costantina',
          ja: 'コンスタンティーヌ',
          ko: '콩스탕틴',
          zh: '君士坦丁',
          pt: 'Constantina',
          ru: 'Константина',
          es: 'Constantina',
          fr: 'Constantine',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Médéa',
          de: 'Médéa',
          it: 'Médéa',
          ja: 'メデア',
          ko: '메데아',
          zh: '麦迪亚',
          pt: 'Médéa',
          ru: 'Медеа',
          es: 'Médéa',
          fr: 'Médéa',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Mostaganem',
          de: 'Mostaganem',
          it: 'Mostaganem',
          ja: 'モスタガネム',
          ko: '모스타가넴',
          zh: '穆斯塔加奈姆',
          pt: 'Mostaganem',
          ru: 'Мостаганем',
          es: 'Mostaganem',
          fr: 'Mostaganem',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: "M'sila",
          de: "M'sila",
          it: "M'sila",
          ja: 'ムシラ',
          ko: '음실라',
          zh: '姆西拉',
          pt: "M'sila",
          ru: 'Мсила',
          es: "M'sila",
          fr: "M'sila",
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Mascara',
          de: 'Mascara',
          it: 'Mascara',
          ja: 'マスカラ',
          ko: '마스카라',
          zh: '穆阿斯凯尔',
          pt: 'Mascara',
          ru: 'Маскара',
          es: 'Mascara',
          fr: 'Mascara',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Ouargla',
          de: 'Ouargla',
          it: 'Ouargla',
          ja: 'ワルグラ',
          ko: '우아르글라',
          zh: '瓦尔格拉',
          pt: 'Ouargla',
          ru: 'Уаргла',
          es: 'Ouargla',
          fr: 'Ouargla',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Oran',
          de: 'Oran',
          it: 'Orano',
          ja: 'オラン',
          ko: '오랑',
          zh: '奥兰',
          pt: 'Orão',
          ru: 'Оран',
          es: 'Orán',
          fr: 'Oran',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'El Bayadh',
          de: 'El Bayadh',
          it: 'El Bayadh',
          ja: 'エル・バヤード',
          ko: '엘바야드',
          zh: '巴亚兹',
          pt: 'El Bayadh',
          ru: 'Эль-Баяд',
          es: 'El Bayadh',
          fr: 'El Bayadh',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Illizi',
          de: 'Illizi',
          it: 'Illizi',
          ja: 'イリジ',
          ko: '일리지',
          zh: '伊利济',
          pt: 'Illizi',
          ru: 'Иллизи',
          es: 'Illizi',
          fr: 'Illizi',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Bordj Bou Arréridj',
          de: 'Bordj Bou Arréridj',
          it: 'Bordj Bou Arréridj',
          ja: 'ボルジ・ブ・アレリジ',
          ko: '보르즈부아레리즈',
          zh: '布阿拉里季堡',
          pt: 'Bordj Bou Arréridj',
          ru: 'Бордж-Бу-Арреридж',
          es: 'Bordj Bou Arréridj',
          fr: 'Bordj Bou Arréridj',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Boumerdès',
          de: 'Boumerdès',
          it: 'Boumerdès',
          ja: 'ブメルデス',
          ko: '부메르데스',
          zh: '布米尔达斯',
          pt: 'Boumerdès',
          ru: 'Бумердес',
          es: 'Boumerdès',
          fr: 'Boumerdès',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'El Tarf',
          de: 'El Tarf',
          it: 'El Tarf',
          ja: 'エル・タルフ',
          ko: '엘타르프',
          zh: '塔里夫',
          pt: 'El Tarf',
          ru: 'Эль-Тарф',
          es: 'El Tarf',
          fr: 'El Tarf',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Tindouf',
          de: 'Tindouf',
          it: 'Tindouf',
          ja: 'ティンドゥフ',
          ko: '틴두프',
          zh: '廷杜夫',
          pt: 'Tindouf',
          ru: 'Тиндуф',
          es: 'Tindouf',
          fr: 'Tindouf',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Tissemsilt',
          de: 'Tissemsilt',
          it: 'Tissemsilt',
          ja: 'ティセムシルト',
          ko: '티셈실트',
          zh: '提塞姆西勒特',
          pt: 'Tissemsilt',
          ru: 'Тисемсильт',
          es: 'Tissemsilt',
          fr: 'Tissemsilt',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'El Oued',
          de: 'El Oued',
          it: 'El Oued',
          ja: 'エル・ウェッド',
          ko: '엘우에드',
          zh: '瓦迪',
          pt: 'El Oued',
          ru: 'Эль-Уэд',
          es: 'El Oued',
          fr: 'El Oued',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Khenchela',
          de: 'Khenchela',
          it: 'Khenchela',
          ja: 'ヘンシュラ',
          ko: '켄셸라',
          zh: '汉舍莱',
          pt: 'Khenchela',
          ru: 'Хеншела',
          es: 'Khenchela',
          fr: 'Khenchela',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Souk Ahras',
          de: 'Souk Ahras',
          it: 'Souk Ahras',
          ja: 'スーク・アフラース',
          ko: '수크아라스',
          zh: '苏格艾赫拉斯',
          pt: 'Souk Ahras',
          ru: 'Сук-Ахрас',
          es: 'Souk Ahras',
          fr: 'Souk Ahras',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Tipaza',
          de: 'Tipaza',
          it: 'Tipaza',
          ja: 'ティパザ',
          ko: '티파자',
          zh: '提帕萨',
          pt: 'Tipaza',
          ru: 'Типаза',
          es: 'Tipaza',
          fr: 'Tipaza',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Mila',
          de: 'Mila',
          it: 'Mila',
          ja: 'ミラ',
          ko: '밀라',
          zh: '米拉',
          pt: 'Mila',
          ru: 'Мила',
          es: 'Mila',
          fr: 'Mila',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Aïn Defla',
          de: 'Aïn Defla',
          it: 'Aïn Defla',
          ja: 'アインデフラ',
          ko: '아인데플라',
          zh: '艾因迪夫拉',
          pt: 'Aïn Defla',
          ru: 'Айн-Дефла',
          es: 'Aïn Defla',
          fr: 'Aïn Defla',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Naâma',
          de: 'Naâma',
          it: 'Naâma',
          ja: 'ナーマ',
          ko: '나마',
          zh: '纳马',
          pt: 'Naâma',
          ru: 'Наама',
          es: 'Naâma',
          fr: 'Naâma',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Aïn Témouchent',
          de: 'Aïn Témouchent',
          it: 'Aïn Témouchent',
          ja: 'アイン・ティムシェント',
          ko: '아인테무셴트',
          zh: '艾因泰穆尚特',
          pt: 'Aïn Témouchent',
          ru: 'Айн-Темушент',
          es: 'Aïn Témouchent',
          fr: 'Aïn Témouchent',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Ghardaïa',
          de: 'Ghardaïa',
          it: 'Ghardaïa',
          ja: 'ガルダイア',
          ko: '가르다이아',
          zh: '盖尔达耶',
          pt: 'Ghardaïa',
          ru: 'Гардая',
          es: 'Ghardaïa',
          fr: 'Ghardaïa',
        },
        denomination: 'provinces',
      },
      {
        country_id: 3,
        capital_id: null,
        name: {
          en: 'Relizane',
          de: 'Relizane',
          it: 'Relizane',
          ja: 'ルリザンヌ',
          ko: '렐리잔',
          zh: '埃利赞',
          pt: 'Relizane',
          ru: 'Гализан (Релизан)',
          es: 'Relizane',
          fr: 'Relizane',
        },
        denomination: 'provinces',
      },
      {
        country_id: 4,
        capital_id: null,
        name: {
          en: 'Western District',
          de: 'Western District',
          it: 'Western District',
          ja: 'ウェスタン地区',
          ko: '웨스턴 디스트릭트',
          zh: '西部区',
          pt: 'Western District',
          ru: 'Уэстерн Дистрикт',
          es: 'Western District',
          fr: 'Western District',
        },
        denomination: 'districts',
      },
      {
        country_id: 4,
        capital_id: null,
        name: {
          en: 'Eastern District',
          de: 'Eastern District',
          it: 'Eastern District',
          ja: 'イースタン地区',
          ko: '이스턴 디스트릭트',
          zh: '东部区',
          pt: 'Eastern District',
          ru: 'Истерн Дистрикт',
          es: 'Eastern District',
          fr: 'Eastern District',
        },
        denomination: 'districts',
      },
      {
        country_id: 4,
        capital_id: null,
        name: {
          en: 'Manuʻa District',
          de: 'Manuʻa District',
          it: 'Manuʻa District',
          ja: 'マヌア地区',
          ko: '마누아 디스트릭트',
          zh: '马努阿区',
          pt: 'Manuʻa District',
          ru: 'Мануа Дистрикт',
          es: 'Manuʻa District',
          fr: 'Manuʻa District',
        },
        denomination: 'districts',
      },
      {
        country_id: 4,
        capital_id: null,
        name: {
          en: 'Swains Island',
          de: 'Swains Island',
          it: 'Swains Island',
          ja: 'スウェインズ島',
          ko: '스웨인스 아일랜드',
          zh: '斯温斯岛',
          pt: 'Swains Island',
          ru: 'Свейнс Айленд',
          es: 'Swains Island',
          fr: 'Swains Island',
        },
        denomination: 'districts',
      },
      {
        country_id: 4,
        capital_id: null,
        name: {
          en: 'Rose Atoll',
          de: 'Rose Atoll',
          it: 'Rose Atoll',
          ja: 'ローズ環礁',
          ko: '로즈 환초',
          zh: '罗斯环礁',
          pt: 'Rose Atoll',
          ru: 'Роуз Атолл',
          es: 'Rose Atoll',
          fr: 'Rose Atoll',
        },
        denomination: 'districts',
      },
      {
        country_id: 5,
        capital_id: null,
        name: {
          en: 'Andorra la Vella',
          de: 'Andorra la Vella',
          it: 'Andorra la Vella',
          ja: 'アンドラ・ラ・ベリャ',
          ko: '안도라라베야',
          zh: '安道尔城',
          pt: 'Andorra-a-Velha',
          ru: 'Андорра-ла-Велья',
          es: 'Andorra la Vieja',
          fr: 'Andorre-la-Vieille',
        },
        denomination: 'parishes',
      },
      {
        country_id: 5,
        capital_id: null,
        name: {
          en: 'Canillo',
          de: 'Canillo',
          it: 'Canillo',
          ja: 'カニーリョ',
          ko: '카닐료',
          zh: '卡尼略',
          pt: 'Canillo',
          ru: 'Канильо',
          es: 'Canillo',
          fr: 'Canillo',
        },
        denomination: 'parishes',
      },
      {
        country_id: 5,
        capital_id: null,
        name: {
          en: 'Encamp',
          de: 'Encamp',
          it: 'Encamp',
          ja: 'エンカンプ',
          ko: '엔캠프',
          zh: '恩坎普',
          pt: 'Encamp',
          ru: 'Энкамп',
          es: 'Encamp',
          fr: 'Encamp',
        },
        denomination: 'parishes',
      },
      {
        country_id: 5,
        capital_id: null,
        name: {
          en: 'Escaldes-Engordany',
          de: 'Escaldes-Engordany',
          it: 'Escaldes-Engordany',
          ja: 'エスカルデス・エンゴルダニ',
          ko: '에스칼데스엔고르다니',
          zh: '埃斯卡尔德斯-恩戈尔达尼',
          pt: 'Escaldes-Engordany',
          ru: 'Эскальдес-Энгордань',
          es: 'Escaldes-Engordany',
          fr: 'Escaldes-Engordany',
        },
        denomination: 'parishes',
      },
      {
        country_id: 5,
        capital_id: null,
        name: {
          en: 'La Massana',
          de: 'La Massana',
          it: 'La Massana',
          ja: 'ラ・マサナ',
          ko: '라 마사나',
          zh: '拉马萨纳',
          pt: 'La Massana',
          ru: 'Ла-Массана',
          es: 'La Massana',
          fr: 'La Massana',
        },
        denomination: 'parishes',
      },
      {
        country_id: 5,
        capital_id: null,
        name: {
          en: 'Ordino',
          de: 'Ordino',
          it: 'Ordino',
          ja: 'オルディノ',
          ko: '오르디노',
          zh: '奥尔迪诺',
          pt: 'Ordino',
          ru: 'Ордино',
          es: 'Ordino',
          fr: 'Ordino',
        },
        denomination: 'parishes',
      },
      {
        country_id: 5,
        capital_id: null,
        name: {
          en: 'Sant Julià de Lòria',
          de: 'Sant Julià de Lòria',
          it: 'Sant Julià de Lòria',
          ja: 'サン・ジュリア・デ・ロリア',
          ko: '산 줄리아 데 로리아',
          zh: '圣胡利娅-德洛里亚',
          pt: 'Sant Julià de Lòria',
          ru: 'Сан-Жулья-де-Лория',
          es: 'San Juliá de Loria',
          fr: 'Saint-Julie-de-Loria',
        },
        denomination: 'parishes',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Bengo',
          de: 'Bengo',
          it: 'Bengo',
          ja: 'ベンゴ州',
          ko: '벵구주',
          zh: '本戈省',
          pt: 'Bengo',
          ru: 'Бенго',
          es: 'Bengo',
          fr: 'Bengo',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Benguela',
          de: 'Benguela',
          it: 'Benguela',
          ja: 'ベンゲラ州',
          ko: '벵겔라주',
          zh: '本格拉省',
          pt: 'Benguela',
          ru: 'Бенгела',
          es: 'Benguela',
          fr: 'Benguela',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Bié',
          de: 'Bié',
          it: 'Bié',
          ja: 'ビエ州',
          ko: '비에주',
          zh: '比耶省',
          pt: 'Bié',
          ru: 'Бие',
          es: 'Bié',
          fr: 'Bié',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Cabinda',
          de: 'Cabinda',
          it: 'Cabinda',
          ja: 'カビンダ州',
          ko: '카빈다주',
          zh: '卡宾达省',
          pt: 'Cabinda',
          ru: 'Кабинда',
          es: 'Cabinda',
          fr: 'Cabinda',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Cuando Cubango',
          de: 'Cuando Cubango',
          it: 'Cuando Cubango',
          ja: 'クアンド・クバンゴ州',
          ko: '쿠안두쿠방구주',
          zh: '宽多-库邦戈省',
          pt: 'Cuando Cubango',
          ru: 'Квандо-Кубанго',
          es: 'Cuando Cubango',
          fr: 'Cuando Cubango',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Cuanza Norte',
          de: 'Cuanza Norte',
          it: 'Cuanza Norte',
          ja: 'クアンザ・ノルテ州',
          ko: '쿠안자노르트 주',
          zh: '北宽扎省',
          pt: 'Cuanza Norte',
          ru: 'Северная Кванза',
          es: 'Cuanza Norte',
          fr: 'Cuanza Norte',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Cuanza Sul',
          de: 'Cuanza Sul',
          it: 'Cuanza Sul',
          ja: 'クアンザ・スル州',
          ko: '쿠안자술주',
          zh: '南宽扎省',
          pt: 'Cuanza Sul',
          ru: 'Южная Кванза',
          es: 'Cuanza Sul',
          fr: 'Cuanza Sul',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Cunene',
          de: 'Cunene',
          it: 'Cunene',
          ja: 'クネネ州',
          ko: '쿠네느주',
          zh: '库内内省',
          pt: 'Cunene',
          ru: 'Кунене',
          es: 'Cunene',
          fr: 'Cunene',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Huambo',
          de: 'Huambo',
          it: 'Huambo',
          ja: 'ウアンボ州',
          ko: '우암부주',
          zh: '万博省',
          pt: 'Huambo',
          ru: 'Уамбо',
          es: 'Huambo',
          fr: 'Huambo',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Huíla',
          de: 'Huíla',
          it: 'Huíla',
          ja: 'ウイラ州',
          ko: '우일라 주',
          zh: '威拉省',
          pt: 'Huíla',
          ru: 'Уила',
          es: 'Huíla',
          fr: 'Huíla',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Luanda',
          de: 'Luanda',
          it: 'Luanda',
          ja: 'ルアンダ州',
          ko: '루안다주',
          zh: '罗安达省',
          pt: 'Luanda',
          ru: 'Луанда',
          es: 'Luanda',
          fr: 'Luanda',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Lunda Norte',
          de: 'Lunda Norte',
          it: 'Lunda Norte',
          ja: 'ルンダ・ノルテ州',
          ko: '룬다노르트주',
          zh: '北隆达省',
          pt: 'Lunda Norte',
          ru: 'Северная Лунда',
          es: 'Lunda Norte',
          fr: 'Lunda Norte',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Lunda Sul',
          de: 'Lunda Sul',
          it: 'Lunda Sul',
          ja: 'ルンダ・スル州',
          ko: '룬다술주',
          zh: '南隆达省',
          pt: 'Lunda Sul',
          ru: 'Южная Лунда',
          es: 'Lunda Sul',
          fr: 'Lunda Sul',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Malanje',
          de: 'Malanje',
          it: 'Malanje',
          ja: 'マランジェ州',
          ko: '말란즈주',
          zh: '马兰热省',
          pt: 'Malanje',
          ru: 'Маланже',
          es: 'Malanje',
          fr: 'Malanje',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Moxico',
          de: 'Moxico',
          it: 'Moxico',
          ja: 'モシコ州',
          ko: '모시쿠주',
          zh: '莫希科省',
          pt: 'Moxico',
          ru: 'Мошико',
          es: 'Moxico',
          fr: 'Moxico',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Namibe',
          de: 'Namibe',
          it: 'Namibe',
          ja: 'ナミベ州',
          ko: '나미브주',
          zh: '纳米贝省',
          pt: 'Namibe',
          ru: 'Намибе',
          es: 'Namibe',
          fr: 'Namibe',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Uíge',
          de: 'Uíge',
          it: 'Uíge',
          ja: 'ウイジェ州',
          ko: '우이즈주',
          zh: '威热省',
          pt: 'Uíge',
          ru: 'Уиже',
          es: 'Uíge',
          fr: 'Uíge',
        },
        denomination: 'provinces',
      },
      {
        country_id: 6,
        capital_id: null,
        name: {
          en: 'Zaire',
          de: 'Zaire',
          it: 'Zaire',
          ja: 'ザイーレ州',
          ko: '자이르주',
          zh: '萨伊省',
          pt: 'Zaire',
          ru: 'Заире',
          es: 'Zaire',
          fr: 'Zaire',
        },
        denomination: 'provinces',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'Blowing Point',
          de: 'Blowing Point',
          it: 'Blowing Point',
          ja: 'ブローイング・ポイント',
          ko: '블로잉 포인트',
          zh: '布洛因波因特',
          pt: 'Blowing Point',
          ru: 'Блоуинг-Пойнт',
          es: 'Blowing Point',
          fr: 'Blowing Point',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'East End',
          de: 'East End',
          it: 'East End',
          ja: 'イースト・エンド',
          ko: '이스트 엔드',
          zh: '东端',
          pt: 'East End',
          ru: 'Ист-Энд',
          es: 'East End',
          fr: 'East End',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'George Hill',
          de: 'George Hill',
          it: 'George Hill',
          ja: 'ジョージ・ヒル',
          ko: '조지 힐',
          zh: '乔治希尔',
          pt: 'George Hill',
          ru: 'Джордж-Хилл',
          es: 'George Hill',
          fr: 'George Hill',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'Island Harbour',
          de: 'Island Harbour',
          it: 'Island Harbour',
          ja: 'アイランド・ハーバー',
          ko: '아일랜드 하버',
          zh: '岛港',
          pt: 'Island Harbour',
          ru: 'Айленд-Харбор',
          es: 'Island Harbour',
          fr: 'Island Harbour',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'North Hill',
          de: 'North Hill',
          it: 'North Hill',
          ja: 'ノース・ヒル',
          ko: '노스 힐',
          zh: '北山',
          pt: 'North Hill',
          ru: 'Норт-Хилл',
          es: 'North Hill',
          fr: 'North Hill',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'North Side',
          de: 'North Side',
          it: 'North Side',
          ja: 'ノース・サイド',
          ko: '노스 사이드',
          zh: '北侧',
          pt: 'North Side',
          ru: 'Норт-Сайд',
          es: 'North Side',
          fr: 'North Side',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'Sandy Ground',
          de: 'Sandy Ground',
          it: 'Sandy Ground',
          ja: 'サンディ・グラウンド',
          ko: '샌디 그라운드',
          zh: '桑迪地面',
          pt: 'Sandy Ground',
          ru: 'Сэнди-Граунд',
          es: 'Sandy Ground',
          fr: 'Sandy Ground',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'Sandy Hill',
          de: 'Sandy Hill',
          it: 'Sandy Hill',
          ja: 'サンディ・ヒル',
          ko: '샌디 힐',
          zh: '桑迪希尔',
          pt: 'Sandy Hill',
          ru: 'Сэнди-Хилл',
          es: 'Sandy Hill',
          fr: 'Sandy Hill',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'South Hill',
          de: 'South Hill',
          it: 'South Hill',
          ja: 'サウス・ヒル',
          ko: '사우스 힐',
          zh: '南山',
          pt: 'South Hill',
          ru: 'Саут-Хилл',
          es: 'South Hill',
          fr: 'South Hill',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'Stoney Ground',
          de: 'Stoney Ground',
          it: 'Stoney Ground',
          ja: 'ストーニー・グラウンド',
          ko: '스토니 그라운드',
          zh: '斯托尼地面',
          pt: 'Stoney Ground',
          ru: 'Стоуни-Граунд',
          es: 'Stoney Ground',
          fr: 'Stoney Ground',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'The Farrington',
          de: 'The Farrington',
          it: 'The Farrington',
          ja: 'ザ・ファリントン',
          ko: '더 패링턴',
          zh: '法林顿',
          pt: 'The Farrington',
          ru: 'Фаррингтон',
          es: 'The Farrington',
          fr: 'The Farrington',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'The Quarter',
          de: 'The Quarter',
          it: 'The Quarter',
          ja: 'ザ・クォーター',
          ko: '더 쿼터',
          zh: '夸特',
          pt: 'The Quarter',
          ru: 'Куортер',
          es: 'The Quarter',
          fr: 'The Quarter',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'The Valley',
          de: 'The Valley',
          it: 'The Valley',
          ja: 'ザ・バレー',
          ko: '더 밸리',
          zh: '瓦利',
          pt: 'The Valley',
          ru: 'Валли',
          es: 'The Valley',
          fr: 'The Valley',
        },
        denomination: 'districts',
      },
      {
        country_id: 7,
        capital_id: null,
        name: {
          en: 'West End',
          de: 'West End',
          it: 'West End',
          ja: 'ウェスト・エンド',
          ko: '웨스트 엔드',
          zh: '西端',
          pt: 'West End',
          ru: 'Уэст-Энд',
          es: 'West End',
          fr: 'West End',
        },
        denomination: 'districts',
      },
    ];

    return subDivisions;
  },

  up: async (queryInterface) => {
    const batchSize = 50;
    const subDivisions = this.get();

    for (let i = 0; i < subDivisions.length; i += batchSize) {
      const batch = subDivisions.slice(i, i + batchSize);
      for (const subDivision of batch) {
        await queryInterface.bulkInsert('', [subDivision], {
          updateOnDuplicate: [],
        });
      }
    }
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('geo_countries', null, {});
  },
};
