'use strict';

module.exports = {
  get: () => {
    const subDivisions = [
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Badakhshan',
          de: 'Badakhshan',
          it: 'Badakhshan',
          ja: 'バダフシャーン',
          ko: '바다흐샨',
          zh: '巴达赫尚',
          pt: 'Badakhshan',
          ru: 'Бадахшан',
          es: 'Badakhshan',
          fr: 'Badakhshan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Badghis',
          de: 'Badghis',
          it: 'Badghis',
          ja: 'バードギース',
          ko: '바드기스',
          zh: '巴德吉斯',
          pt: 'Badghis',
          ru: 'Бадагис',
          es: 'Badghis',
          fr: 'Badghis',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Baghlan',
          de: 'Baghlan',
          it: 'Baghlan',
          ja: 'バグラン',
          ko: '바글란',
          zh: '巴格兰',
          pt: 'Baghlan',
          ru: 'Баглан',
          es: 'Baghlan',
          fr: 'Baghlan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Balkh',
          de: 'Balkh',
          it: 'Balkh',
          ja: 'バルフ',
          ko: '발크',
          zh: '巴尔赫',
          pt: 'Balkh',
          ru: 'Балх',
          es: 'Balkh',
          fr: 'Balkh',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Bamyan',
          de: 'Bamyan',
          it: 'Bamyan',
          ja: 'バーミヤン',
          ko: '바미안',
          zh: '巴米扬',
          pt: 'Bamyan',
          ru: 'Бамиан',
          es: 'Bamyan',
          fr: 'Bamyan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Daykundi',
          de: 'Daykundi',
          it: 'Daykundi',
          ja: 'ダイクンディ',
          ko: '다이쿤디',
          zh: '代孔迪',
          pt: 'Daykundi',
          ru: 'Дайкунди',
          es: 'Daykundi',
          fr: 'Daykundi',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Farah',
          de: 'Farah',
          it: 'Farah',
          ja: 'ファラー',
          ko: '파라',
          zh: '法拉',
          pt: 'Farah',
          ru: 'Фарах',
          es: 'Farah',
          fr: 'Farah',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Faryab',
          de: 'Faryab',
          it: 'Faryab',
          ja: 'ファルヤブ',
          ko: '파리야브',
          zh: '法里亚布',
          pt: 'Faryab',
          ru: 'Фарьяб',
          es: 'Faryab',
          fr: 'Faryab',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Ghazni',
          de: 'Ghazni',
          it: 'Ghazni',
          ja: 'ガズニ',
          ko: '가즈니',
          zh: '加兹尼',
          pt: 'Ghazni',
          ru: 'Газни',
          es: 'Ghazni',
          fr: 'Ghazni',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Ghor',
          de: 'Ghor',
          it: 'Ghor',
          ja: 'ゴール',
          ko: '고르',
          zh: '戈尔',
          pt: 'Ghor',
          ru: 'Гор',
          es: 'Ghor',
          fr: 'Ghor',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Helmand',
          de: 'Helmand',
          it: 'Helmand',
          ja: 'ヘルマンド',
          ko: '헬만드',
          zh: '赫尔曼德',
          pt: 'Helmand',
          ru: 'Гильменд',
          es: 'Helmand',
          fr: 'Helmand',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Herat',
          de: 'Herat',
          it: 'Herat',
          ja: 'ヘラート',
          ko: '헤라트',
          zh: '赫拉特',
          pt: 'Herat',
          ru: 'Герат',
          es: 'Herat',
          fr: 'Herat',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Jowzjan',
          de: 'Jowzjan',
          it: 'Jowzjan',
          ja: 'ジョウズジャン',
          ko: '조우즈잔',
          zh: '朱兹詹',
          pt: 'Jowzjan',
          ru: 'Джаузджан',
          es: 'Jowzjan',
          fr: 'Jowzjan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Kabul',
          de: 'Kabul',
          it: 'Kabul',
          ja: 'カーブル',
          ko: '카불',
          zh: '喀布尔',
          pt: 'Cabul',
          ru: 'Кабул',
          es: 'Kabul',
          fr: 'Kaboul',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Kandahar',
          de: 'Kandahar',
          it: 'Kandahar',
          ja: 'カンダハール',
          ko: '칸다하르',
          zh: '坎大哈',
          pt: 'Candaar',
          ru: 'Кандагар',
          es: 'Kandahar',
          fr: 'Kandahar',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Kapisa',
          de: 'Kapisa',
          it: 'Kapisa',
          ja: 'カピサ',
          ko: '카피사',
          zh: '卡皮萨',
          pt: 'Kapisa',
          ru: 'Каписa',
          es: 'Kapisa',
          fr: 'Kapisa',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Khost',
          de: 'Khost',
          it: 'Khost',
          ja: 'ホスト',
          ko: '호스트',
          zh: '霍斯特',
          pt: 'Khost',
          ru: 'Хост',
          es: 'Khost',
          fr: 'Khost',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Kunar',
          de: 'Kunar',
          it: 'Kunar',
          ja: 'クナール',
          ko: '쿠나르',
          zh: '库纳尔',
          pt: 'Kunar',
          ru: 'Кунар',
          es: 'Kunar',
          fr: 'Kunar',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Kunduz',
          de: 'Kunduz',
          it: 'Kunduz',
          ja: 'クンドゥーズ',
          ko: '쿤두즈',
          zh: '昆都士',
          pt: 'Kunduz',
          ru: 'Кундуз',
          es: 'Kunduz',
          fr: 'Kunduz',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Laghman',
          de: 'Laghman',
          it: 'Laghman',
          ja: 'ラグマーン',
          ko: '라그만',
          zh: '拉格曼',
          pt: 'Laghman',
          ru: 'Лагман',
          es: 'Laghman',
          fr: 'Laghman',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Logar',
          de: 'Logar',
          it: 'Logar',
          ja: 'ロガル',
          ko: '로가르',
          zh: '卢格尔',
          pt: 'Logar',
          ru: 'Логар',
          es: 'Logar',
          fr: 'Logar',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Nangarhar',
          de: 'Nangarhar',
          it: 'Nangarhar',
          ja: 'ナンガルハール',
          ko: '낭가르하르',
          zh: '楠格哈尔',
          pt: 'Nangarhar',
          ru: 'Нангархар',
          es: 'Nangarhar',
          fr: 'Nangarhar',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Nimruz',
          de: 'Nimruz',
          it: 'Nimruz',
          ja: 'ニムルーズ',
          ko: '님루즈',
          zh: '尼姆鲁兹',
          pt: 'Nimruz',
          ru: 'Нимруз',
          es: 'Nimruz',
          fr: 'Nimruz',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Nuristan',
          de: 'Nuristan',
          it: 'Nuristan',
          ja: 'ヌリストン',
          ko: '누리스탄',
          zh: '努里斯坦',
          pt: 'Nuristan',
          ru: 'Нуристан',
          es: 'Nuristan',
          fr: 'Nuristan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Uruzgan',
          de: 'Uruzgan',
          it: 'Uruzgan',
          ja: 'ウルズガーン',
          ko: '우루즈간',
          zh: '乌鲁兹甘',
          pt: 'Uruzgan',
          ru: 'Урузган',
          es: 'Uruzgan',
          fr: 'Uruzgan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Paktia',
          de: 'Paktia',
          it: 'Paktia',
          ja: 'パクティア',
          ko: '팍티아',
          zh: '帕克蒂亚',
          pt: 'Paktia',
          ru: 'Пактия',
          es: 'Paktia',
          fr: 'Paktia',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Paktika',
          de: 'Paktika',
          it: 'Paktika',
          ja: 'パクティカ',
          ko: '팍티카',
          zh: '帕克蒂卡',
          pt: 'Paktika',
          ru: 'Пактика',
          es: 'Paktika',
          fr: 'Paktika',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Panjshir',
          de: 'Panjshir',
          it: 'Panjshir',
          ja: 'パンジシール',
          ko: '판지시르',
          zh: '潘杰希尔',
          pt: 'Panjshir',
          ru: 'Панджшер',
          es: 'Panjshir',
          fr: 'Panjshir',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Parwan',
          de: 'Parwan',
          it: 'Parwan',
          ja: 'パルワーン',
          ko: '파르완',
          zh: '帕尔万',
          pt: 'Parwan',
          ru: 'Парван',
          es: 'Parwan',
          fr: 'Parwan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Samangan',
          de: 'Samangan',
          it: 'Samangan',
          ja: 'サマンガーン',
          ko: '사망간',
          zh: '萨曼甘',
          pt: 'Samangan',
          ru: 'Саманган',
          es: 'Samangan',
          fr: 'Samangan',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Sar-e Pol',
          de: 'Sar-e Pol',
          it: 'Sar-e Pol',
          ja: 'サレポル',
          ko: '사레폴',
          zh: '萨尔普勒',
          pt: 'Sar-e Pol',
          ru: 'Сари-Пуль',
          es: 'Sar-e Pol',
          fr: 'Sar-e Pol',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Takhar',
          de: 'Takhar',
          it: 'Takhar',
          ja: 'タハール',
          ko: '타하르',
          zh: '塔哈尔',
          pt: 'Takhar',
          ru: 'Тахар',
          es: 'Takhar',
          fr: 'Takhar',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Wardak',
          de: 'Wardak',
          it: 'Wardak',
          ja: 'ワルダク',
          ko: '와르다크',
          zh: '瓦尔达克',
          pt: 'Wardak',
          ru: 'Вардак',
          es: 'Wardak',
          fr: 'Wardak',
        },
        denomination: 'providence',
      },
      {
        country_id: 1,
        capital_id: null,
        name: {
          en: 'Zabul',
          de: 'Zabul',
          it: 'Zabul',
          ja: 'ザーブル',
          ko: '자불',
          zh: '扎布尔',
          pt: 'Zabul',
          ru: 'Забуль',
          es: 'Zabul',
          fr: 'Zabul',
        },
        denomination: 'providence',
      },
    ];

    return subDivisions;
  },

  up: async (queryInterface) => {
    const batchSize = 50;
    const subDivisions = this.get();

    for (let i = 0; i < subDivisions.length; i += batchSize) {
      const batch = subDivisions.slice(i, i + batchSize);
      for (const subDivision of batch) {
        await queryInterface.bulkInsert('', [subDivision], {
          updateOnDuplicate: [],
        });
      }
    }
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('geo_countries', null, {});
  },
};
