'use strict';

module.exports = {
  get: () => {
    const languages = [
      {
        id: 1,
        id_flag: null,
        abbreviation: 'af',
        version: null,
        name: JSON.stringify({
          en: 'Afrikaans',
          de: 'Afrikaans',
          it: 'Afrikaans',
          ja: 'アフリカーンス語',
          ko: '아프리칸스어',
          zh: '南非荷兰语',
          pt: 'Africâner',
          ru: 'Африкаанс',
          es: 'Afrikáans',
          fr: 'Afrikaans',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 2,
        id_flag: null,
        abbreviation: 'sq',
        version: null,
        name: JSON.stringify({
          en: 'Albanian',
          de: 'Albanisch',
          it: 'Albanese',
          ja: 'アルバニア語',
          ko: '알바니아어',
          zh: '阿尔巴尼亚语',
          pt: 'Albanês',
          ru: 'Албанский',
          es: 'Albanés',
          fr: 'Albanais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 3,
        id_flag: null,
        abbreviation: 'am',
        version: null,
        name: JSON.stringify({
          en: 'Amharic',
          de: 'Amharisch',
          it: 'Amarico',
          ja: 'アムハラ語',
          ko: '암하라어',
          zh: '阿姆哈拉语',
          pt: 'Amárico',
          ru: 'Амхарский',
          es: 'Amárico',
          fr: 'Amharique',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 4,
        id_flag: null,
        abbreviation: 'ar',
        version: null,
        name: JSON.stringify({
          en: 'Arabic',
          de: 'Arabisch',
          it: 'Arabo',
          ja: 'アラビア語',
          ko: '아랍어',
          zh: '阿拉伯语',
          pt: 'Árabe',
          ru: 'Арабский',
          es: 'Árabe',
          fr: 'Arabe',
        }),
        description: null,
        orientation: 'R2L',
        public: 0,
      },
      {
        id: 5,
        id_flag: null,
        abbreviation: 'hy',
        version: null,
        name: JSON.stringify({
          en: 'Armenian',
          de: 'Armenisch',
          it: 'Armeno',
          ja: 'アルメニア語',
          ko: '아르메니아어',
          zh: '亚美尼亚语',
          pt: 'Armênio',
          ru: 'Армянский',
          es: 'Armenio',
          fr: 'Arménien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 6,
        id_flag: null,
        abbreviation: 'ay',
        version: null,
        name: JSON.stringify({
          en: 'Aymara',
          de: 'Aymara',
          it: 'Aymara',
          ja: 'アイマラ語',
          ko: '아이마라어',
          zh: '艾马拉语',
          pt: 'Aimará',
          ru: 'Аймара',
          es: 'Aimara',
          fr: 'Aymara',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 7,
        id_flag: null,
        abbreviation: 'az',
        version: null,
        name: JSON.stringify({
          en: 'Azerbaijani',
          de: 'Aserbaidschanisch',
          it: 'Azero',
          ja: 'アゼルバイジャン語',
          ko: '아제르바이잔어',
          zh: '阿塞拜疆语',
          pt: 'Azerbaijano',
          ru: 'Азербайджанский',
          es: 'Azerí',
          fr: 'Azéri',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 8,
        id_flag: null,
        abbreviation: 'bm',
        version: null,
        name: JSON.stringify({
          en: 'Bambara',
          de: 'Bambara',
          it: 'Bambara',
          ja: 'バンバラ語',
          ko: '밤바라어',
          zh: '班巴拉语',
          pt: 'Bambara',
          ru: 'Бамбара',
          es: 'Bambara',
          fr: 'Bambara',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 9,
        id_flag: null,
        abbreviation: 'eu',
        version: null,
        name: JSON.stringify({
          en: 'Basque',
          de: 'Baskisch',
          it: 'Basco',
          ja: 'バスク語',
          ko: '바스크어',
          zh: '巴斯克语',
          pt: 'Basco',
          ru: 'Баскский',
          es: 'Vasco',
          fr: 'Basque',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 10,
        id_flag: null,
        abbreviation: 'be',
        version: null,
        name: JSON.stringify({
          en: 'Belarusian',
          de: 'Belarussisch',
          it: 'Bielorusso',
          ja: 'ベラルーシ語',
          ko: '벨라루스어',
          zh: '白俄罗斯语',
          pt: 'Bielorrusso',
          ru: 'Белорусский',
          es: 'Bielorruso',
          fr: 'Biélorusse',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 11,
        id_flag: null,
        abbreviation: 'bem',
        version: null,
        name: JSON.stringify({
          en: 'Bemba',
          de: 'Bemba',
          it: 'Bemba',
          ja: 'ベンバ語',
          ko: '벰바어',
          zh: '本巴语',
          pt: 'Bemba',
          ru: 'Бемба',
          es: 'Bemba',
          fr: 'Bemba',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 12,
        id_flag: null,
        abbreviation: 'bn',
        version: null,
        name: JSON.stringify({
          en: 'Bengali',
          de: 'Bengalisch',
          it: 'Bengali',
          ja: 'ベンガル語',
          ko: '벵골어',
          zh: '孟加拉语',
          pt: 'Bengali',
          ru: 'Бенгальский',
          es: 'Bengalí',
          fr: 'Bengali',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 13,
        id_flag: null,
        abbreviation: 'ber',
        version: null,
        name: JSON.stringify({
          en: 'Berber',
          de: 'Berbersprachen',
          it: 'Berbero',
          ja: 'ベルベル語',
          ko: '베르베르어',
          zh: '柏柏尔语',
          pt: 'Berbere',
          ru: 'Берберский',
          es: 'Bereber',
          fr: 'Berbère',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 14,
        id_flag: null,
        abbreviation: 'bho',
        version: null,
        name: JSON.stringify({
          en: 'Bhojpuri',
          de: 'Bhojpuri',
          it: 'Bhojpuri',
          ja: 'ボージュプリー語',
          ko: '보즈푸리어',
          zh: '博杰普尔语',
          pt: 'Bhojpuri',
          ru: 'Бходжпури',
          es: 'Bhojpuri',
          fr: 'Bhojpuri',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 15,
        id_flag: null,
        abbreviation: 'bi',
        version: null,
        name: JSON.stringify({
          en: 'Bislama',
          de: 'Bislama',
          it: 'Bislama',
          ja: 'ビスラマ語',
          ko: '비슬라마어',
          zh: '比斯拉马语',
          pt: 'Bislama',
          ru: 'Бислама',
          es: 'Bislama',
          fr: 'Bichelamar',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 16,
        id_flag: null,
        abbreviation: 'bs',
        version: null,
        name: JSON.stringify({
          en: 'Bosnian',
          de: 'Bosnisch',
          it: 'Bosniaco',
          ja: 'ボスニア語',
          ko: '보스니아어',
          zh: '波斯尼亚语',
          pt: 'Bósnio',
          ru: 'Боснийский',
          es: 'Bosnio',
          fr: 'Bosnien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 17,
        id_flag: null,
        abbreviation: 'bg',
        version: null,
        name: JSON.stringify({
          en: 'Bulgarian',
          de: 'Bulgarisch',
          it: 'Bulgaro',
          ja: 'ブルガリア語',
          ko: '불가리아어',
          zh: '保加利亚语',
          pt: 'Búlgaro',
          ru: 'Болгарский',
          es: 'Búlgaro',
          fr: 'Bulgare',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 18,
        id_flag: null,
        abbreviation: 'my',
        version: null,
        name: JSON.stringify({
          en: 'Burmese',
          de: 'Birmanisch',
          it: 'Birmano',
          ja: 'ビルマ語',
          ko: '버마어',
          zh: '缅甸语',
          pt: 'Birmanês',
          ru: 'Бирманский',
          es: 'Birmano',
          fr: 'Birman',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 19,
        id_flag: null,
        abbreviation: 'kea',
        version: null,
        name: JSON.stringify({
          en: 'Cape Verdean Creole',
          de: 'Kapverdisches Kreol',
          it: 'Creolo capoverdiano',
          ja: 'カーボベルデ・クレオール語',
          ko: '카보베르데 크리올어',
          zh: '佛得角克里奥尔语',
          pt: 'Crioulo cabo-verdiano',
          ru: 'Кабо-вердианский креольский',
          es: 'Criollo caboverdiano',
          fr: 'Créole cap-verdien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 20,
        id_flag: null,
        abbreviation: 'ca',
        version: null,
        name: JSON.stringify({
          en: 'Catalan',
          de: 'Katalanisch',
          it: 'Catalano',
          ja: 'カタロニア語',
          ko: '카탈루냐어',
          zh: '加泰罗尼亚语',
          pt: 'Catalão',
          ru: 'Каталанский',
          es: 'Catalán',
          fr: 'Catalan',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 21,
        id_flag: null,
        abbreviation: 'ch',
        version: null,
        name: JSON.stringify({
          en: 'Chamorro',
          de: 'Chamorro',
          it: 'Chamorro',
          ja: 'チャモロ語',
          ko: '차모로어',
          zh: '查莫罗语',
          pt: 'Chamorro',
          ru: 'Чаморро',
          es: 'Chamorro',
          fr: 'Chamorro',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 22,
        id_flag: null,
        abbreviation: 'ny',
        version: null,
        name: JSON.stringify({
          en: 'Chichewa',
          de: 'Chichewa',
          it: 'Chichewa',
          ja: 'チェチェワ語',
          ko: '치체와어',
          zh: '齐切瓦语',
          pt: 'Chichewa',
          ru: 'Чичева',
          es: 'Chichewa',
          fr: 'Chichewa',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 23,
        id_flag: null,
        abbreviation: 'zh',
        version: null,
        name: JSON.stringify({
          en: 'Mandarin Chinese',
          de: 'Chinesisch (Mandarin)',
          it: 'Cinese mandarino',
          ja: '中国語（北京語）',
          ko: '중국어 (만다린)',
          zh: '汉语（普通话）',
          pt: 'Chinês mandarim',
          ru: 'Китайский (мандарин)',
          es: 'Chino mandarín',
          fr: 'Chinois mandarin',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 24,
        id_flag: null,
        abbreviation: 'zh',
        version: 'HK',
        name: JSON.stringify({
          en: 'Cantonese Chinese',
          de: 'Kantonesisch',
          it: 'Cinese cantonese',
          ja: '広東語',
          ko: '광둥어',
          zh: '粤语',
          pt: 'Cantonês',
          ru: 'Кантонский',
          es: 'Cantonés',
          fr: 'Cantonais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 25,
        id_flag: null,
        abbreviation: 'swb',
        version: null,
        name: JSON.stringify({
          en: 'Comorian',
          de: 'Komorisch',
          it: 'Comoriano',
          ja: 'コモロ語',
          ko: '코모로어',
          zh: '科摩罗语',
          pt: 'Comorano',
          ru: 'Коморский',
          es: 'Comorense',
          fr: 'Comorien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 26,
        id_flag: null,
        abbreviation: 'rar',
        version: null,
        name: JSON.stringify({
          en: 'Cook Islands Maori',
          de: 'Cookinseln-Maori',
          it: 'Maori delle Isole Cook',
          ja: 'クック諸島マオリ語',
          ko: '쿡 제도 마오리어',
          zh: '库克群岛毛利语',
          pt: 'Maori das Ilhas Cook',
          ru: 'Маори островов Кука',
          es: 'Maorí de las Islas Cook',
          fr: 'Maori des îles Cook',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 27,
        id_flag: null,
        abbreviation: 'crs',
        version: null,
        name: JSON.stringify({
          en: 'Seychellois Creole',
          de: 'Seychellenkreol',
          it: 'Creolo delle Seychelles',
          ja: 'セーシェル・クレオール語',
          ko: '세이셸 크리올어',
          zh: '塞舌尔克里奥尔语',
          pt: 'Crioulo seichelense',
          ru: 'Сейшельский креольский',
          es: 'Criollo seychelense',
          fr: 'Créole seychellois',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 28,
        id_flag: null,
        abbreviation: 'hr',
        version: null,
        name: JSON.stringify({
          en: 'Croatian',
          de: 'Kroatisch',
          it: 'Croato',
          ja: 'クロアチア語',
          ko: '크로아티아어',
          zh: '克罗地亚语',
          pt: 'Croata',
          ru: 'Хорватский',
          es: 'Croata',
          fr: 'Croate',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 29,
        id_flag: null,
        abbreviation: 'cs',
        version: null,
        name: JSON.stringify({
          en: 'Czech',
          de: 'Tschechisch',
          it: 'Ceco',
          ja: 'チェコ語',
          ko: '체코어',
          zh: '捷克语',
          pt: 'Tcheco',
          ru: 'Чешский',
          es: 'Checo',
          fr: 'Tchèque',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 30,
        id_flag: null,
        abbreviation: 'da',
        version: null,
        name: JSON.stringify({
          en: 'Danish',
          de: 'Dänisch',
          it: 'Danese',
          ja: 'デンマーク語',
          ko: '덴마크어',
          zh: '丹麦语',
          pt: 'Dinamarquês',
          ru: 'Датский',
          es: 'Danés',
          fr: 'Danois',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 31,
        id_flag: null,
        abbreviation: 'fa',
        version: 'AF',
        name: JSON.stringify({
          en: 'Dari Persian',
          de: 'Dari',
          it: 'Dari',
          ja: 'ダリー語',
          ko: '다리어',
          zh: '达里波斯语',
          pt: 'Dari',
          ru: 'Дари',
          es: 'Dari',
          fr: 'Dari',
        }),
        description: null,
        orientation: 'R2L',
        public: 0,
      },
      {
        id: 32,
        id_flag: null,
        abbreviation: 'dv',
        version: null,
        name: JSON.stringify({
          en: 'Dhivehi',
          de: 'Dhivehi',
          it: 'Divehi',
          ja: 'ディベヒ語',
          ko: '디베히어',
          zh: '迪维希语',
          pt: 'Divehi',
          ru: 'Дивехи',
          es: 'Dhivehi',
          fr: 'Maldivien',
        }),
        description: null,
        orientation: 'R2L',
        public: 0,
      },
      {
        id: 33,
        id_flag: null,
        abbreviation: 'din',
        version: null,
        name: JSON.stringify({
          en: 'Dinka',
          de: 'Dinka',
          it: 'Dinka',
          ja: 'ディンカ語',
          ko: '딩카어',
          zh: '丁卡语',
          pt: 'Dinka',
          ru: 'Динка',
          es: 'Dinka',
          fr: 'Dinka',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 34,
        id_flag: null,
        abbreviation: 'dyu',
        version: null,
        name: JSON.stringify({
          en: 'Dyula',
          de: 'Dyula',
          it: 'Dioula',
          ja: 'ジュラ語',
          ko: '줄라어',
          zh: '迪乌拉语',
          pt: 'Diula',
          ru: 'Диула',
          es: 'Diula',
          fr: 'Dioula',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 35,
        id_flag: null,
        abbreviation: 'nl',
        version: null,
        name: JSON.stringify({
          en: 'Dutch',
          de: 'Niederländisch',
          it: 'Olandese',
          ja: 'オランダ語',
          ko: '네덜란드어',
          zh: '荷兰语',
          pt: 'Holandês',
          ru: 'Нидерландский',
          es: 'Neerlandés',
          fr: 'Néerlandais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 36,
        id_flag: null,
        abbreviation: 'dz',
        version: null,
        name: JSON.stringify({
          en: 'Dzongkha',
          de: 'Dzongkha',
          it: 'Dzongkha',
          ja: 'ゾンカ語',
          ko: '종카어',
          zh: '宗卡语',
          pt: 'Dzongkha',
          ru: 'Дзонг-кэ',
          es: 'Dzongkha',
          fr: 'Dzongkha',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 37,
        id_flag: null,
        abbreviation: 'en',
        version: null,
        name: JSON.stringify({
          en: 'English',
          de: 'Englisch',
          it: 'Inglese',
          ja: '英語',
          ko: '영어',
          zh: '英语',
          pt: 'Inglês',
          ru: 'Английский',
          es: 'Inglés',
          fr: 'Anglais',
        }),
        description: null,
        orientation: 'L2R',
        public: 1,
      },
      {
        id: 38,
        id_flag: null,
        abbreviation: 'et',
        version: null,
        name: JSON.stringify({
          en: 'Estonian',
          de: 'Estnisch',
          it: 'Estone',
          ja: 'エストニア語',
          ko: '에스토니아어',
          zh: '爱沙尼亚语',
          pt: 'Estoniano',
          ru: 'Эстонский',
          es: 'Estonio',
          fr: 'Estonien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 39,
        id_flag: null,
        abbreviation: 'ee',
        version: null,
        name: JSON.stringify({
          en: 'Ewe',
          de: 'Ewe',
          it: 'Ewe',
          ja: 'エウェ語',
          ko: '에웨어',
          zh: '埃维语',
          pt: 'Ewe',
          ru: 'Эве',
          es: 'Ewe',
          fr: 'Éwé',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 40,
        id_flag: null,
        abbreviation: 'fo',
        version: null,
        name: JSON.stringify({
          en: 'Faroese',
          de: 'Färöisch',
          it: 'Faroese',
          ja: 'フェロー語',
          ko: '페로어',
          zh: '法罗语',
          pt: 'Feroês',
          ru: 'Фарерский',
          es: 'Feroés',
          fr: 'Féroïen',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 41,
        id_flag: null,
        abbreviation: 'fj',
        version: null,
        name: JSON.stringify({
          en: 'Fijian',
          de: 'Fidschianisch',
          it: 'Figiano',
          ja: 'フィジー語',
          ko: '피지어',
          zh: '斐济语',
          pt: 'Fijiano',
          ru: 'Фиджийский',
          es: 'Fiyiano',
          fr: 'Fidjien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 42,
        id_flag: null,
        abbreviation: 'fil',
        version: null,
        name: JSON.stringify({
          en: 'Filipino',
          de: 'Filipino',
          it: 'Filippino',
          ja: 'フィリピノ語',
          ko: '필리핀어',
          zh: '菲律宾语',
          pt: 'Filipino',
          ru: 'Филиппинский',
          es: 'Filipino',
          fr: 'Filipino',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 43,
        id_flag: null,
        abbreviation: 'fi',
        version: null,
        name: JSON.stringify({
          en: 'Finnish',
          de: 'Finnisch',
          it: 'Finlandese',
          ja: 'フィンランド語',
          ko: '핀란드어',
          zh: '芬兰语',
          pt: 'Finlandês',
          ru: 'Финский',
          es: 'Finés',
          fr: 'Finnois',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 44,
        id_flag: null,
        abbreviation: 'fr',
        version: null,
        name: JSON.stringify({
          en: 'French',
          de: 'Französisch',
          it: 'Francese',
          ja: 'フランス語',
          ko: '프랑스어',
          zh: '法语',
          pt: 'Francês',
          ru: 'Французский',
          es: 'Francés',
          fr: 'Français',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 45,
        id_flag: null,
        abbreviation: 'ht',
        version: null,
        name: JSON.stringify({
          en: 'Haitian Creole',
          de: 'Haitianisch',
          it: 'Creolo haitiano',
          ja: 'ハイチ・クレオール語',
          ko: '아이티 크리올어',
          zh: '海地克里奥尔语',
          pt: 'Crioulo haitiano',
          ru: 'Гаитянский креольский',
          es: 'Criollo haitiano',
          fr: 'Créole haïtien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 46,
        id_flag: null,
        abbreviation: 'fy',
        version: null,
        name: JSON.stringify({
          en: 'Frisian',
          de: 'Friesisch',
          it: 'Frisone',
          ja: 'フリジア語',
          ko: '프리지아어',
          zh: '弗里西语',
          pt: 'Frísio',
          ru: 'Фризский',
          es: 'Frisio',
          fr: 'Frison',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 47,
        id_flag: null,
        abbreviation: 'fut',
        version: null,
        name: JSON.stringify({
          en: 'Futunan',
          de: 'Futunisch',
          it: 'Futunano',
          ja: 'フツナ語',
          ko: '푸투나어',
          zh: '富图纳语',
          pt: 'Futuniano',
          ru: 'Футунанский',
          es: 'Futunano',
          fr: 'Futunien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 48,
        id_flag: null,
        abbreviation: 'gl',
        version: null,
        name: JSON.stringify({
          en: 'Galician',
          de: 'Galicisch',
          it: 'Galiziano',
          ja: 'ガリシア語',
          ko: '갈리시아어',
          zh: '加利西亚语',
          pt: 'Galego',
          ru: 'Галисийский',
          es: 'Gallego',
          fr: 'Galicien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 49,
        id_flag: null,
        abbreviation: 'ka',
        version: null,
        name: JSON.stringify({
          en: 'Georgian',
          de: 'Georgisch',
          it: 'Georgiano',
          ja: 'グルジア語',
          ko: '조지아어',
          zh: '格鲁吉亚语',
          pt: 'Georgiano',
          ru: 'Грузинский',
          es: 'Georgiano',
          fr: 'Géorgien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 50,
        id_flag: null,
        abbreviation: 'de',
        version: null,
        name: JSON.stringify({
          en: 'German',
          de: 'Deutsch',
          it: 'Tedesco',
          ja: 'ドイツ語',
          ko: '독일어',
          zh: '德语',
          pt: 'Alemão',
          ru: 'Немецкий',
          es: 'Alemán',
          fr: 'Allemand',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 51,
        id_flag: null,
        abbreviation: 'gil',
        version: null,
        name: JSON.stringify({
          en: 'Gilbertese',
          de: 'Kiribatisch',
          it: 'Gilbertese',
          ja: 'キリバス語',
          ko: '키리바시어',
          zh: '吉尔伯特语',
          pt: 'Gilbertês',
          ru: 'Кирибати',
          es: 'Gilbertense',
          fr: 'Gilbertin',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 52,
        id_flag: null,
        abbreviation: 'el',
        version: null,
        name: JSON.stringify({
          en: 'Greek',
          de: 'Griechisch',
          it: 'Greco',
          ja: 'ギリシャ語',
          ko: '그리스어',
          zh: '希腊语',
          pt: 'Grego',
          ru: 'Греческий',
          es: 'Griego',
          fr: 'Grec',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 53,
        id_flag: null,
        abbreviation: 'kl',
        version: null,
        name: JSON.stringify({
          en: 'Greenlandic',
          de: 'Grönländisch',
          it: 'Groenlandese',
          ja: 'グリーンランド語',
          ko: '그린란드어',
          zh: '格陵兰语',
          pt: 'Groenlandês',
          ru: 'Гренландский',
          es: 'Groenlandés',
          fr: 'Groenlandais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 54,
        id_flag: null,
        abbreviation: 'gn',
        version: null,
        name: JSON.stringify({
          en: 'Guarani',
          de: 'Guaraní',
          it: 'Guaraní',
          ja: 'グアラニー語',
          ko: '과라니어',
          zh: '瓜拉尼语',
          pt: 'Guarani',
          ru: 'Гуарани',
          es: 'Guaraní',
          fr: 'Guarani',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 55,
        id_flag: null,
        abbreviation: 'ha',
        version: null,
        name: JSON.stringify({
          en: 'Hausa',
          de: 'Hausa',
          it: 'Hausa',
          ja: 'ハウサ語',
          ko: '하우사어',
          zh: '豪萨语',
          pt: 'Hauçá',
          ru: 'Хауса',
          es: 'Hausa',
          fr: 'Haoussa',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 56,
        id_flag: null,
        abbreviation: 'he',
        version: null,
        name: JSON.stringify({
          en: 'Hebrew',
          de: 'Hebräisch',
          it: 'Ebraico',
          ja: 'ヘブライ語',
          ko: '히브리어',
          zh: '希伯来语',
          pt: 'Hebraico',
          ru: 'Иврит',
          es: 'Hebreo',
          fr: 'Hébreu',
        }),
        description: null,
        orientation: 'R2L',
        public: 0,
      },
      {
        id: 57,
        id_flag: null,
        abbreviation: 'hz',
        version: null,
        name: JSON.stringify({
          en: 'Herero',
          de: 'Herero',
          it: 'Herero',
          ja: 'ヘレロ語',
          ko: '헤레로어',
          zh: '赫雷罗语',
          pt: 'Herero',
          ru: 'Гереро',
          es: 'Herero',
          fr: 'Herero',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 58,
        id_flag: null,
        abbreviation: 'hi',
        version: null,
        name: JSON.stringify({
          en: 'Hindi',
          de: 'Hindi',
          it: 'Hindi',
          ja: 'ヒンディー語',
          ko: '힌디어',
          zh: '印地语',
          pt: 'Hindi',
          ru: 'Хинди',
          es: 'Hindi',
          fr: 'Hindi',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 59,
        id_flag: null,
        abbreviation: 'hmo',
        version: null,
        name: JSON.stringify({
          en: 'Hiri Motu',
          de: 'Hiri Motu',
          it: 'Hiri Motu',
          ja: 'ヒリモツ語',
          ko: '히리 모투어',
          zh: '希里莫图语',
          pt: 'Hiri Motu',
          ru: 'Хиримоту',
          es: 'Hiri Motu',
          fr: 'Hiri motu',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 60,
        id_flag: null,
        abbreviation: 'hu',
        version: null,
        name: JSON.stringify({
          en: 'Hungarian',
          de: 'Ungarisch',
          it: 'Ungherese',
          ja: 'ハンガリー語',
          ko: '헝가리어',
          zh: '匈牙利语',
          pt: 'Húngaro',
          ru: 'Венгерский',
          es: 'Húngaro',
          fr: 'Hongrois',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 61,
        id_flag: null,
        abbreviation: 'is',
        version: null,
        name: JSON.stringify({
          en: 'Icelandic',
          de: 'Isländisch',
          it: 'Islandese',
          ja: 'アイスランド語',
          ko: '아이슬란드어',
          zh: '冰岛语',
          pt: 'Islandês',
          ru: 'Исландский',
          es: 'Islandés',
          fr: 'Islandais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 62,
        id_flag: null,
        abbreviation: 'ig',
        version: null,
        name: JSON.stringify({
          en: 'Igbo',
          de: 'Igbo',
          it: 'Igbo',
          ja: 'イボ語',
          ko: '이그보어',
          zh: '伊博语',
          pt: 'Igbo',
          ru: 'Игбо',
          es: 'Igbo',
          fr: 'Igbo',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 63,
        id_flag: null,
        abbreviation: 'id',
        version: null,
        name: JSON.stringify({
          en: 'Indonesian',
          de: 'Indonesisch',
          it: 'Indonesiano',
          ja: 'インドネシア語',
          ko: '인도네시아어',
          zh: '印度尼西亚语',
          pt: 'Indonésio',
          ru: 'Индонезийский',
          es: 'Indonesio',
          fr: 'Indonésien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 64,
        id_flag: null,
        abbreviation: 'ga',
        version: null,
        name: JSON.stringify({
          en: 'Irish',
          de: 'Irisch',
          it: 'Irlandese',
          ja: 'アイルランド語',
          ko: '아일랜드어',
          zh: '爱尔兰语',
          pt: 'Irlandês',
          ru: 'Ирландский',
          es: 'Irlandés',
          fr: 'Irlandais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 65,
        id_flag: null,
        abbreviation: 'it',
        version: null,
        name: JSON.stringify({
          en: 'Italian',
          de: 'Italienisch',
          it: 'Italiano',
          ja: 'イタリア語',
          ko: '이탈리아어',
          zh: '意大利语',
          pt: 'Italiano',
          ru: 'Итальянский',
          es: 'Italiano',
          fr: 'Italien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 66,
        id_flag: null,
        abbreviation: 'jam',
        version: null,
        name: JSON.stringify({
          en: 'Jamaican Patois',
          de: 'Jamaikanisch-Kreolisch',
          it: 'Patois giamaicano',
          ja: 'ジャマイカ・パトワ語',
          ko: '자메이카 파토아어',
          zh: '牙买加克里奥尔语',
          pt: 'Patuá jamaicano',
          ru: 'Ямайский креольский',
          es: 'Patois jamaicano',
          fr: 'Créole jamaïcain',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 67,
        id_flag: null,
        abbreviation: 'ja',
        version: null,
        name: JSON.stringify({
          en: 'Japanese',
          de: 'Japanisch',
          it: 'Giapponese',
          ja: '日本語',
          ko: '일본어',
          zh: '日语',
          pt: 'Japonês',
          ru: 'Японский',
          es: 'Japonés',
          fr: 'Japonais',
        }),
        description: null,
        orientation: 'T2BR2L',
        public: 0,
      },
      {
        id: 68,
        id_flag: null,
        abbreviation: 'jv',
        version: null,
        name: JSON.stringify({
          en: 'Javanese',
          de: 'Javanisch',
          it: 'Giavanese',
          ja: 'ジャワ語',
          ko: '자바어',
          zh: '爪哇语',
          pt: 'Javanês',
          ru: 'Яванский',
          es: 'Javanés',
          fr: 'Javanais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 69,
        id_flag: null,
        abbreviation: 'dyo',
        version: null,
        name: JSON.stringify({
          en: 'Jola',
          de: 'Diola',
          it: 'Jola',
          ja: 'ジョラ語',
          ko: '졸라어',
          zh: '朱拉语',
          pt: 'Jola',
          ru: 'Дьола',
          es: 'Jola',
          fr: 'Diola',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 70,
        id_flag: null,
        abbreviation: 'nrf',
        version: null,
        name: JSON.stringify({
          en: 'Jèrriais',
          de: 'Jèrriais',
          it: 'Jèrriais',
          ja: 'ジャージー語',
          ko: '저레이어',
          zh: '泽西语',
          pt: 'Jèrriais',
          ru: 'Джерриа',
          es: 'Jèrriais',
          fr: 'Jèrriais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 71,
        id_flag: null,
        abbreviation: 'quc',
        version: null,
        name: JSON.stringify({
          en: "K'iche'",
          de: 'Kʼicheʼ',
          it: 'Kʼicheʼ',
          ja: 'キチェ語',
          ko: '키체어',
          zh: '基切语',
          pt: 'Quiché',
          ru: 'Киче',
          es: 'Kʼicheʼ',
          fr: 'Kʼicheʼ',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 72,
        id_flag: null,
        abbreviation: 'kbp',
        version: null,
        name: JSON.stringify({
          en: 'Kabiye',
          de: 'Kabiyé',
          it: 'Kabiye',
          ja: 'カビエ語',
          ko: '카비예어',
          zh: '卡比耶语',
          pt: 'Kabiye',
          ru: 'Кабийе',
          es: 'Kabiye',
          fr: 'Kabiye',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 73,
        id_flag: null,
        abbreviation: 'knc',
        version: null,
        name: JSON.stringify({
          en: 'Kanak languages',
          de: 'Kanak-Sprachen',
          it: 'Lingue kanak',
          ja: 'カナク諸語',
          ko: '카나크 제어',
          zh: '卡纳克诸语言',
          pt: 'Línguas canacas',
          ru: 'Канакские языки',
          es: 'Lenguas kanak',
          fr: 'Langues kanak',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 74,
        id_flag: null,
        abbreviation: 'kk',
        version: null,
        name: JSON.stringify({
          en: 'Kazakh',
          de: 'Kasachisch',
          it: 'Kazako',
          ja: 'カザフ語',
          ko: '카자흐어',
          zh: '哈萨克语',
          pt: 'Cazaque',
          ru: 'Казахский',
          es: 'Kazajo',
          fr: 'Kazakh',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 75,
        id_flag: null,
        abbreviation: 'km',
        version: null,
        name: JSON.stringify({
          en: 'Khmer',
          de: 'Khmer',
          it: 'Khmer',
          ja: 'クメール語',
          ko: '크메르어',
          zh: '高棉语',
          pt: 'Khmer',
          ru: 'Кхмерский',
          es: 'Jemer',
          fr: 'Khmer',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 76,
        id_flag: null,
        abbreviation: 'naq',
        version: null,
        name: JSON.stringify({
          en: 'Khoekhoe',
          de: 'Khoekhoe',
          it: 'Khoekhoe',
          ja: 'コエコエ語',
          ko: '코에코에어',
          zh: '科伊科伊语',
          pt: 'Khoekhoe',
          ru: 'Кхойкхой',
          es: 'Khoekhoe',
          fr: 'Khoekhoe',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 77,
        id_flag: null,
        abbreviation: 'kg',
        version: null,
        name: JSON.stringify({
          en: 'Kongo',
          de: 'Kikongo',
          it: 'Kongo',
          ja: 'コンゴ語',
          ko: '콩고어',
          zh: '刚果语',
          pt: 'Kikongo',
          ru: 'Конго',
          es: 'Kikongo',
          fr: 'Kikongo',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 78,
        id_flag: null,
        abbreviation: 'rw',
        version: null,
        name: JSON.stringify({
          en: 'Kinyarwanda',
          de: 'Kinyarwanda',
          it: 'Kinyarwanda',
          ja: 'ルワンダ語',
          ko: '르완다어',
          zh: '卢旺达语',
          pt: 'Kinyarwanda',
          ru: 'Киньяруанда',
          es: 'Kinyarwanda',
          fr: 'Kinyarwanda',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 79,
        id_flag: null,
        abbreviation: 'rn',
        version: null,
        name: JSON.stringify({
          en: 'Kirundi',
          de: 'Kirundi',
          it: 'Kirundi',
          ja: 'ルンディ語',
          ko: '룬디어',
          zh: '隆迪语',
          pt: 'Kirundi',
          ru: 'Кирунди',
          es: 'Kirundi',
          fr: 'Kirundi',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 80,
        id_flag: null,
        abbreviation: 'ktu',
        version: null,
        name: JSON.stringify({
          en: 'Kituba',
          de: 'Kituba',
          it: 'Kituba',
          ja: 'キトゥバ語',
          ko: '키투바어',
          zh: '基图巴语',
          pt: 'Kituba',
          ru: 'Китуба',
          es: 'Kituba',
          fr: 'Kituba',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 81,
        id_flag: null,
        abbreviation: 'ko',
        version: null,
        name: JSON.stringify({
          en: 'Korean',
          de: 'Koreanisch',
          it: 'Coreano',
          ja: '韓国語',
          ko: '한국어',
          zh: '朝鲜语',
          pt: 'Coreano',
          ru: 'Корейский',
          es: 'Coreano',
          fr: 'Coréen',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 82,
        id_flag: null,
        abbreviation: 'kri',
        version: null,
        name: JSON.stringify({
          en: 'Krio',
          de: 'Krio',
          it: 'Krio',
          ja: 'クリオ語',
          ko: '크리오어',
          zh: '克里奥尔语',
          pt: 'Krio',
          ru: 'Крио',
          es: 'Krio',
          fr: 'Krio',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 83,
        id_flag: null,
        abbreviation: 'ku',
        version: null,
        name: JSON.stringify({
          en: 'Kurdish',
          de: 'Kurdisch',
          it: 'Curdo',
          ja: 'クルド語',
          ko: '쿠르드어',
          zh: '库尔德语',
          pt: 'Curdo',
          ru: 'Курдский',
          es: 'Kurdo',
          fr: 'Kurde',
        }),
        description: null,
        orientation: 'R2L',
        public: 0,
      },
      {
        id: 84,
        id_flag: null,
        abbreviation: 'gcf',
        version: null,
        name: JSON.stringify({
          en: 'Saint Lucian Creole',
          de: 'Saint-Lucia-Kreolisch',
          it: 'Creolo di Saint Lucia',
          ja: 'セントルシア・クレオール語',
          ko: '세인트루시아 크리올어',
          zh: '圣卢西亚克里奥尔语',
          pt: 'Crioulo de Santa Lúcia',
          ru: 'Сент-люсийский креольский',
          es: 'Criollo de Santa Lucía',
          fr: 'Créole saint-lucien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 85,
        id_flag: null,
        abbreviation: 'ky',
        version: null,
        name: JSON.stringify({
          en: 'Kyrgyz',
          de: 'Kirgisisch',
          it: 'Chirghiso',
          ja: 'キルギス語',
          ko: '키르기스어',
          zh: '吉尔吉斯语',
          pt: 'Quirguiz',
          ru: 'Киргизский',
          es: 'Kirguís',
          fr: 'Kirghize',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 86,
        id_flag: null,
        abbreviation: 'lo',
        version: null,
        name: JSON.stringify({
          en: 'Lao',
          de: 'Laotisch',
          it: 'Lao',
          ja: 'ラオ語',
          ko: '라오어',
          zh: '老挝语',
          pt: 'Laosiano',
          ru: 'Лаосский',
          es: 'Lao',
          fr: 'Lao',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 87,
        id_flag: null,
        abbreviation: 'la',
        version: null,
        name: JSON.stringify({
          en: 'Latin',
          de: 'Latein',
          it: 'Latino',
          ja: 'ラテン語',
          ko: '라틴어',
          zh: '拉丁语',
          pt: 'Latim',
          ru: 'Латинский',
          es: 'Latín',
          fr: 'Latin',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 88,
        id_flag: null,
        abbreviation: 'lv',
        version: null,
        name: JSON.stringify({
          en: 'Latvian',
          de: 'Lettisch',
          it: 'Lettone',
          ja: 'ラトビア語',
          ko: '라트비아어',
          zh: '拉脱维亚语',
          pt: 'Letão',
          ru: 'Латышский',
          es: 'Letón',
          fr: 'Letton',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 89,
        id_flag: null,
        abbreviation: 'lbm',
        version: null,
        name: JSON.stringify({
          en: 'Limba',
          de: 'Limba',
          it: 'Limba',
          ja: 'リンバ語',
          ko: '림바어',
          zh: '林巴语',
          pt: 'Limba',
          ru: 'Лимба',
          es: 'Limba',
          fr: 'Limba',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 90,
        id_flag: null,
        abbreviation: 'ln',
        version: null,
        name: JSON.stringify({
          en: 'Lingala',
          de: 'Lingala',
          it: 'Lingala',
          ja: 'リンガラ語',
          ko: '링갈라어',
          zh: '林加拉语',
          pt: 'Lingala',
          ru: 'Лингала',
          es: 'Lingala',
          fr: 'Lingala',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 91,
        id_flag: null,
        abbreviation: 'lt',
        version: null,
        name: JSON.stringify({
          en: 'Lithuanian',
          de: 'Litauisch',
          it: 'Lituano',
          ja: 'リトアニア語',
          ko: '리투아니아어',
          zh: '立陶宛语',
          pt: 'Lituano',
          ru: 'Литовский',
          es: 'Lituano',
          fr: 'Lituanien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 92,
        id_flag: null,
        abbreviation: 'lb',
        version: null,
        name: JSON.stringify({
          en: 'Luxembourgish',
          de: 'Luxemburgisch',
          it: 'Lussemburghese',
          ja: 'ルクセンブルク語',
          ko: '룩셈부르크어',
          zh: '卢森堡语',
          pt: 'Luxemburguês',
          ru: 'Люксембургский',
          es: 'Luxemburgués',
          fr: 'Luxembourgeois',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 93,
        id_flag: null,
        abbreviation: 'mk',
        version: null,
        name: JSON.stringify({
          en: 'Macedonian',
          de: 'Mazedonisch',
          it: 'Macedone',
          ja: 'マケドニア語',
          ko: '마케도니아어',
          zh: '马其顿语',
          pt: 'Macedônio',
          ru: 'Македонский',
          es: 'Macedonio',
          fr: 'Macédonien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 94,
        id_flag: null,
        abbreviation: 'mai',
        version: null,
        name: JSON.stringify({
          en: 'Maithili',
          de: 'Maithili',
          it: 'Maithili',
          ja: 'マイティリー語',
          ko: '마이틸리어',
          zh: '迈蒂利语',
          pt: 'Maithili',
          ru: 'Майтхили',
          es: 'Maithili',
          fr: 'Maithili',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 95,
        id_flag: null,
        abbreviation: 'mg',
        version: null,
        name: JSON.stringify({
          en: 'Malagasy',
          de: 'Malagasy',
          it: 'Malgascio',
          ja: 'マダガスカル語',
          ko: '말라가시어',
          zh: '马达加斯加语',
          pt: 'Malgaxe',
          ru: 'Малагасийский',
          es: 'Malgache',
          fr: 'Malgache',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 96,
        id_flag: null,
        abbreviation: 'ms',
        version: null,
        name: JSON.stringify({
          en: 'Malay',
          de: 'Malaiisch',
          it: 'Malese',
          ja: 'マレー語',
          ko: '말레이어',
          zh: '马来语',
          pt: 'Malaio',
          ru: 'Малайский',
          es: 'Malayo',
          fr: 'Malais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 97,
        id_flag: null,
        abbreviation: 'mt',
        version: null,
        name: JSON.stringify({
          en: 'Maltese',
          de: 'Maltesisch',
          it: 'Maltese',
          ja: 'マルタ語',
          ko: '몰타어',
          zh: '马耳他语',
          pt: 'Maltês',
          ru: 'Мальтийский',
          es: 'Maltés',
          fr: 'Maltais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 98,
        id_flag: null,
        abbreviation: 'mnk',
        version: null,
        name: JSON.stringify({
          en: 'Mandinka',
          de: 'Mandinka',
          it: 'Mandinka',
          ja: 'マンディンカ語',
          ko: '만딩카어',
          zh: '曼丁哥语',
          pt: 'Mandinka',
          ru: 'Мандинка',
          es: 'Mandinga',
          fr: 'Mandinka',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 99,
        id_flag: null,
        abbreviation: 'gv',
        version: null,
        name: JSON.stringify({
          en: 'Manx',
          de: 'Manx',
          it: 'Mannese',
          ja: 'マン島語',
          ko: '맨어',
          zh: '曼岛语',
          pt: 'Manx',
          ru: 'Мэнский',
          es: 'Manés',
          fr: 'Mannois',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 100,
        id_flag: null,
        abbreviation: 'mr',
        version: null,
        name: JSON.stringify({
          en: 'Marathi',
          de: 'Marathi',
          it: 'Marathi',
          ja: 'マラーティー語',
          ko: '마라티어',
          zh: '马拉地语',
          pt: 'Marati',
          ru: 'Маратхи',
          es: 'Marathi',
          fr: 'Marathi',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 101,
        id_flag: null,
        abbreviation: 'mh',
        version: null,
        name: JSON.stringify({
          en: 'Marshallese',
          de: 'Marshallesisch',
          it: 'Marshallese',
          ja: 'マーシャル語',
          ko: '마셜어',
          zh: '马绍尔语',
          pt: 'Marshalês',
          ru: 'Маршалльский',
          es: 'Marshalés',
          fr: 'Marshall',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 102,
        id_flag: null,
        abbreviation: 'mfe',
        version: null,
        name: JSON.stringify({
          en: 'Mauritian Creole',
          de: 'Mauritisch-Kreolisch',
          it: 'Creolo mauriziano',
          ja: 'モーリシャス・クレオール語',
          ko: '모리셔스 크리올어',
          zh: '毛里求斯克里奥尔语',
          pt: 'Crioulo mauriciano',
          ru: 'Маврикийский креольский',
          es: 'Criollo mauriciano',
          fr: 'Créole mauricien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 103,
        id_flag: null,
        abbreviation: 'men',
        version: null,
        name: JSON.stringify({
          en: 'Mende',
          de: 'Mende',
          it: 'Mende',
          ja: 'メンデ語',
          ko: '멘데어',
          zh: '门德语',
          pt: 'Mende',
          ru: 'Менде',
          es: 'Mende',
          fr: 'Mendé',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 104,
        id_flag: null,
        abbreviation: 'mn',
        version: null,
        name: JSON.stringify({
          en: 'Mongolian',
          de: 'Mongolisch',
          it: 'Mongolo',
          ja: 'モンゴル語',
          ko: '몽골어',
          zh: '蒙古语',
          pt: 'Mongol',
          ru: 'Монгольский',
          es: 'Mongol',
          fr: 'Mongol',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 105,
        id_flag: null,
        abbreviation: 'cnr',
        version: null,
        name: JSON.stringify({
          en: 'Montenegrin',
          de: 'Montenegrinisch',
          it: 'Montenegrino',
          ja: 'モンテネグロ語',
          ko: '몬테네그로어',
          zh: '黑山语',
          pt: 'Montenegrino',
          ru: 'Черногорский',
          es: 'Montenegrino',
          fr: 'Monténégrin',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 106,
        id_flag: null,
        abbreviation: 'mi',
        version: null,
        name: JSON.stringify({
          en: 'Māori',
          de: 'Māori',
          it: 'Maori',
          ja: 'マオリ語',
          ko: '마오리어',
          zh: '毛利语',
          pt: 'Maori',
          ru: 'Маори',
          es: 'Maorí',
          fr: 'Maori',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 107,
        id_flag: null,
        abbreviation: 'na',
        version: null,
        name: JSON.stringify({
          en: 'Nauruan',
          de: 'Nauruisch',
          it: 'Nauruano',
          ja: 'ナウル語',
          ko: '나우루어',
          zh: '瑙鲁语',
          pt: 'Nauruano',
          ru: 'Науру',
          es: 'Nauruano',
          fr: 'Nauruan',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 108,
        id_flag: null,
        abbreviation: 'ne',
        version: null,
        name: JSON.stringify({
          en: 'Nepali',
          de: 'Nepalesisch',
          it: 'Nepalese',
          ja: 'ネパール語',
          ko: '네팔어',
          zh: '尼泊尔语',
          pt: 'Nepalês',
          ru: 'Непальский',
          es: 'Nepalí',
          fr: 'Népalais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 109,
        id_flag: null,
        abbreviation: 'nzs',
        version: null,
        name: JSON.stringify({
          en: 'New Zealand Sign Language',
          de: 'Neuseeländische Gebärdensprache',
          it: 'Lingua dei segni neozelandese',
          ja: 'ニュージーランド手話',
          ko: '뉴질랜드 수화',
          zh: '新西兰手语',
          pt: 'Língua de sinais da Nova Zelândia',
          ru: 'Новозеландский жестовый язык',
          es: 'Lengua de señas de Nueva Zelanda',
          fr: 'Langue des signes néo-zélandaise',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 110,
        id_flag: null,
        abbreviation: 'niu',
        version: null,
        name: JSON.stringify({
          en: 'Niuean',
          de: 'Niueanisch',
          it: 'Niueano',
          ja: 'ニウエ語',
          ko: '니우에어',
          zh: '纽埃语',
          pt: 'Niueano',
          ru: 'Ниуэ',
          es: 'Niueano',
          fr: 'Niuéen',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 111,
        id_flag: null,
        abbreviation: 'none',
        version: null,
        name: JSON.stringify({
          en: 'None',
          de: 'Keine',
          it: 'Nessuna',
          ja: 'なし',
          ko: '없음',
          zh: '无',
          pt: 'Nenhum',
          ru: 'Нет',
          es: 'Ninguno',
          fr: 'Aucun',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 112,
        id_flag: null,
        abbreviation: 'pih',
        version: null,
        name: JSON.stringify({
          en: 'Norfolk',
          de: 'Norfolk',
          it: 'Norfolk',
          ja: 'ノーフォーク語',
          ko: '노퍽어',
          zh: '诺福克语',
          pt: 'Norfolk',
          ru: 'Норфолкский',
          es: 'Norfolk',
          fr: 'Norfolk',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 113,
        id_flag: null,
        abbreviation: 'no',
        version: null,
        name: JSON.stringify({
          en: 'Norwegian',
          de: 'Norwegisch',
          it: 'Norvegese',
          ja: 'ノルウェー語',
          ko: '노르웨이어',
          zh: '挪威语',
          pt: 'Norueguês',
          ru: 'Норвежский',
          es: 'Noruego',
          fr: 'Norvégien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 114,
        id_flag: null,
        abbreviation: 'nus',
        version: null,
        name: JSON.stringify({
          en: 'Nuer',
          de: 'Nuer',
          it: 'Nuer',
          ja: 'ヌエル語',
          ko: '누에르어',
          zh: '努埃尔语',
          pt: 'Nuer',
          ru: 'Нуэр',
          es: 'Nuer',
          fr: 'Nuer',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 115,
        id_flag: null,
        abbreviation: 'ny',
        version: null,
        name: JSON.stringify({
          en: 'Nyanja',
          de: 'Nyanja',
          it: 'Nyanja',
          ja: 'ニャンジャ語',
          ko: '냔자어',
          zh: '尼扬贾语',
          pt: 'Nianja',
          ru: 'Ньянджа',
          es: 'Chichewa',
          fr: 'Nyanja',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 116,
        id_flag: null,
        abbreviation: 'om',
        version: null,
        name: JSON.stringify({
          en: 'Oromo',
          de: 'Oromo',
          it: 'Oromo',
          ja: 'オロモ語',
          ko: '오로모어',
          zh: '奥罗莫语',
          pt: 'Oromo',
          ru: 'Оромо',
          es: 'Oromo',
          fr: 'Oromo',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 117,
        id_flag: null,
        abbreviation: 'kwn',
        version: null,
        name: JSON.stringify({
          en: 'Oshiwambo',
          de: 'Oshivambo',
          it: 'Oshiwambo',
          ja: 'オシワンボ語',
          ko: '오시왐보어',
          zh: '奥西瓦姆博语',
          pt: 'Oshiwambo',
          ru: 'Ошивамбо',
          es: 'Oshiwambo',
          fr: 'Oshiwambo',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 118,
        id_flag: null,
        abbreviation: 'pau',
        version: null,
        name: JSON.stringify({
          en: 'Palauan',
          de: 'Palauisch',
          it: 'Palauano',
          ja: 'パラオ語',
          ko: '팔라우어',
          zh: '帕劳语',
          pt: 'Palauano',
          ru: 'Палау',
          es: 'Palauano',
          fr: 'Paluan',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 119,
        id_flag: null,
        abbreviation: 'pap',
        version: null,
        name: JSON.stringify({
          en: 'Papiamento',
          de: 'Papiamento',
          it: 'Papiamento',
          ja: 'パピアメント語',
          ko: '파피아멘토어',
          zh: '帕皮亚门托语',
          pt: 'Papiamento',
          ru: 'Папьяменто',
          es: 'Papiamento',
          fr: 'Papiamento',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 120,
        id_flag: null,
        abbreviation: 'ps',
        version: null,
        name: JSON.stringify({
          en: 'Pashto',
          de: 'Paschtu',
          it: 'Pashto',
          ja: 'パシュトー語',
          ko: '파슈토어',
          zh: '普什图语',
          pt: 'Pashto',
          ru: 'Пушту',
          es: 'Pastún',
          fr: 'Pachto',
        }),
        description: null,
        orientation: 'R2L',
        public: 0,
      },
      {
        id: 121,
        id_flag: null,
        abbreviation: 'fa',
        version: null,
        name: JSON.stringify({
          en: 'Persian',
          de: 'Persisch',
          it: 'Persiano',
          ja: 'ペルシア語',
          ko: '페르시아어',
          zh: '波斯语',
          pt: 'Persa',
          ru: 'Персидский',
          es: 'Persa',
          fr: 'Persan',
        }),
        description: null,
        orientation: 'R2L',
        public: 0,
      },
      {
        id: 122,
        id_flag: null,
        abbreviation: 'pih',
        version: null,
        name: JSON.stringify({
          en: 'Pitcairn-Norfolk',
          de: 'Pitcairn-Englisch',
          it: 'Pitcairnese',
          ja: 'ピトケアン語',
          ko: '핏케언어',
          zh: '皮特肯语',
          pt: 'Pitcairnês',
          ru: 'Питкэрнский',
          es: 'Pitcairnés',
          fr: 'Pitcairnais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 123,
        id_flag: null,
        abbreviation: 'pl',
        version: null,
        name: JSON.stringify({
          en: 'Polish',
          de: 'Polnisch',
          it: 'Polacco',
          ja: 'ポーランド語',
          ko: '폴란드어',
          zh: '波兰语',
          pt: 'Polonês',
          ru: 'Польский',
          es: 'Polaco',
          fr: 'Polonais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 124,
        id_flag: null,
        abbreviation: 'pt',
        version: null,
        name: JSON.stringify({
          en: 'Portuguese',
          de: 'Portugiesisch',
          it: 'Portoghese',
          ja: 'ポルトガル語',
          ko: '포르투갈어',
          zh: '葡萄牙语',
          pt: 'Português',
          ru: 'Португальский',
          es: 'Portugués',
          fr: 'Portugais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 125,
        id_flag: null,
        abbreviation: 'pt',
        version: 'BR',
        name: JSON.stringify({
          en: 'Brazilian Portuguese',
          de: 'Brasilianisches Portugiesisch',
          it: 'Portoghese brasiliano',
          ja: 'ブラジルポルトガル語',
          ko: '브라질 포르투갈어',
          zh: '巴西葡萄牙语',
          pt: 'Português brasileiro',
          ru: 'Бразильский португальский',
          es: 'Portugués brasileño',
          fr: 'Portugais brésilien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 126,
        id_flag: null,
        abbreviation: 'fuc',
        version: null,
        name: JSON.stringify({
          en: 'Pulaar',
          de: 'Pulaar',
          it: 'Pulaar',
          ja: 'プラール語',
          ko: '풀라르어',
          zh: '颇尔语',
          pt: 'Pulaar',
          ru: 'Пулаар',
          es: 'Pulaar',
          fr: 'Pulaar',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 127,
        id_flag: null,
        abbreviation: 'pa',
        version: null,
        name: JSON.stringify({
          en: 'Punjabi',
          de: 'Punjabi',
          it: 'Punjabi',
          ja: 'パンジャブ語',
          ko: '펀자브어',
          zh: '旁遮普语',
          pt: 'Panjabi',
          ru: 'Панджаби',
          es: 'Punyabí',
          fr: 'Pendjabi',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 128,
        id_flag: null,
        abbreviation: 'quc',
        version: null,
        name: JSON.stringify({
          en: "Q'eqchi'",
          de: 'Q’eqchi’',
          it: 'Q’eqchi’',
          ja: 'ケクチ語',
          ko: '케크치어',
          zh: '凯克其语',
          pt: 'Q’eqchi’',
          ru: 'Кекчи',
          es: 'Q’eqchi’',
          fr: 'Q’eqchi’',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 129,
        id_flag: null,
        abbreviation: 'qu',
        version: null,
        name: JSON.stringify({
          en: 'Quechua',
          de: 'Quechua',
          it: 'Quechua',
          ja: 'ケチュア語',
          ko: '케추아어',
          zh: '克丘亚语',
          pt: 'Quíchua',
          ru: 'Кечуа',
          es: 'Quechua',
          fr: 'Quechua',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 130,
        id_flag: null,
        abbreviation: 'ro',
        version: null,
        name: JSON.stringify({
          en: 'Romanian',
          de: 'Rumänisch',
          it: 'Rumeno',
          ja: 'ルーマニア語',
          ko: '루마니아어',
          zh: '罗马尼亚语',
          pt: 'Romeno',
          ru: 'Румынский',
          es: 'Rumano',
          fr: 'Roumain',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 131,
        id_flag: null,
        abbreviation: 'rm',
        version: null,
        name: JSON.stringify({
          en: 'Romansh',
          de: 'Rätoromanisch',
          it: 'Romancio',
          ja: 'ロマンシュ語',
          ko: '로만슈어',
          zh: '罗曼什语',
          pt: 'Romanche',
          ru: 'Романшский',
          es: 'Romanche',
          fr: 'Romanche',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 132,
        id_flag: null,
        abbreviation: 'ru',
        version: null,
        name: JSON.stringify({
          en: 'Russian',
          de: 'Russisch',
          it: 'Russo',
          ja: 'ロシア語',
          ko: '러시아어',
          zh: '俄语',
          pt: 'Russo',
          ru: 'Русский',
          es: 'Ruso',
          fr: 'Russe',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 133,
        id_flag: null,
        abbreviation: 'sm',
        version: null,
        name: JSON.stringify({
          en: 'Samoan',
          de: 'Samoanisch',
          it: 'Samoano',
          ja: 'サモア語',
          ko: '사모아어',
          zh: '萨摩亚语',
          pt: 'Samoano',
          ru: 'Самоанский',
          es: 'Samoano',
          fr: 'Samoan',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 134,
        id_flag: null,
        abbreviation: 'sg',
        version: null,
        name: JSON.stringify({
          en: 'Sango',
          de: 'Sango',
          it: 'Sango',
          ja: 'サンゴ語',
          ko: '산고어',
          zh: '桑戈语',
          pt: 'Sango',
          ru: 'Санго',
          es: 'Sango',
          fr: 'Sango',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 135,
        id_flag: null,
        abbreviation: 'gd',
        version: null,
        name: JSON.stringify({
          en: 'Scottish Gaelic',
          de: 'Schottisch-Gälisch',
          it: 'Gaelico scozzese',
          ja: 'スコットランド・ゲール語',
          ko: '스코틀랜드 게일어',
          zh: '苏格兰盖尔语',
          pt: 'Gaélico escocês',
          ru: 'Шотландский гэльский',
          es: 'Gaélico escocés',
          fr: 'Gaélique écossais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 136,
        id_flag: null,
        abbreviation: 'sr',
        version: null,
        name: JSON.stringify({
          en: 'Serbian',
          de: 'Serbisch',
          it: 'Serbo',
          ja: 'セルビア語',
          ko: '세르비아어',
          zh: '塞尔维亚语',
          pt: 'Sérvio',
          ru: 'Сербский',
          es: 'Serbio',
          fr: 'Serbe',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 137,
        id_flag: null,
        abbreviation: 'sh',
        version: null,
        name: JSON.stringify({
          en: 'Serbo-Croatian',
          de: 'Serbokroatisch',
          it: 'Serbo-croato',
          ja: 'セルボ・クロアチア語',
          ko: '세르보크로아티아어',
          zh: '塞尔维亚-克罗地亚语',
          pt: 'Servo-croata',
          ru: 'Сербскохорватский',
          es: 'Serbocroata',
          fr: 'Serbo-croate',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 138,
        id_flag: null,
        abbreviation: 'st',
        version: null,
        name: JSON.stringify({
          en: 'Sesotho',
          de: 'Sesotho',
          it: 'Sesotho',
          ja: 'セソト語',
          ko: '세소토어',
          zh: '塞索托语',
          pt: 'Sesoto',
          ru: 'Сесото',
          es: 'Sesotho',
          fr: 'Sotho du Sud',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 139,
        id_flag: null,
        abbreviation: 'tn',
        version: null,
        name: JSON.stringify({
          en: 'Setswana',
          de: 'Setswana',
          it: 'Setswana',
          ja: 'ツワナ語',
          ko: '세츠와나어',
          zh: '茨瓦纳语',
          pt: 'Setswana',
          ru: 'Сетсвана',
          es: 'Setswana',
          fr: 'Setswana',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 140,
        id_flag: null,
        abbreviation: 'crs',
        version: null,
        name: JSON.stringify({
          en: 'Seychellois Creole',
          de: 'Seychellenkreol',
          it: 'Creolo delle Seychelles',
          ja: 'セーシェル・クレオール語',
          ko: '세이셸 크리올어',
          zh: '塞舌尔克里奥尔语',
          pt: 'Crioulo seichelense',
          ru: 'Сейшельский креольский',
          es: 'Criollo seychelense',
          fr: 'Créole seychellois',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 141,
        id_flag: null,
        abbreviation: 'sn',
        version: null,
        name: JSON.stringify({
          en: 'Shona',
          de: 'Shona',
          it: 'Shona',
          ja: 'ショナ語',
          ko: '쇼나어',
          zh: '绍纳语',
          pt: 'Shona',
          ru: 'Шона',
          es: 'Shona',
          fr: 'Shona',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 142,
        id_flag: null,
        abbreviation: 'nd',
        version: null,
        name: JSON.stringify({
          en: 'Sindebele',
          de: 'Sindebele',
          it: 'Sindebele',
          ja: 'シンデベレ語',
          ko: '신데벨레어',
          zh: '辛德贝莱语',
          pt: 'Sindebele',
          ru: 'Синдебеле',
          es: 'Sindebele',
          fr: 'Sindebele',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 143,
        id_flag: null,
        abbreviation: 'sd',
        version: null,
        name: JSON.stringify({
          en: 'Sindhi',
          de: 'Sindhi',
          it: 'Sindhi',
          ja: 'シンド語',
          ko: '신디어',
          zh: '信德语',
          pt: 'Sindi',
          ru: 'Синдхи',
          es: 'Sindhi',
          fr: 'Sindhi',
        }),
        description: null,
        orientation: 'R2L',
        public: 0,
      },
      {
        id: 144,
        id_flag: null,
        abbreviation: 'si',
        version: null,
        name: JSON.stringify({
          en: 'Sinhala',
          de: 'Singhalesisch',
          it: 'Singalese',
          ja: 'シンハラ語',
          ko: '싱할라어',
          zh: '僧伽罗语',
          pt: 'Cingalês',
          ru: 'Сингальский',
          es: 'Cingalés',
          fr: 'Cingalais',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 145,
        id_flag: null,
        abbreviation: 'sk',
        version: null,
        name: JSON.stringify({
          en: 'Slovak',
          de: 'Slowakisch',
          it: 'Slovacco',
          ja: 'スロバキア語',
          ko: '슬로바키아어',
          zh: '斯洛伐克语',
          pt: 'Eslovaco',
          ru: 'Словацкий',
          es: 'Eslovaco',
          fr: 'Slovaque',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 146,
        id_flag: null,
        abbreviation: 'sl',
        version: null,
        name: JSON.stringify({
          en: 'Slovenian',
          de: 'Slowenisch',
          it: 'Sloveno',
          ja: 'スロベニア語',
          ko: '슬로베니아어',
          zh: '斯洛文尼亚语',
          pt: 'Esloveno',
          ru: 'Словенский',
          es: 'Esloveno',
          fr: 'Slovène',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 147,
        id_flag: null,
        abbreviation: 'pis',
        version: null,
        name: JSON.stringify({
          en: 'Solomon Islands Pijin',
          de: 'Pijin',
          it: 'Pidgin delle Isole Salomone',
          ja: 'ソロモン諸島ピジン語',
          ko: '솔로몬 제도 피진어',
          zh: '所罗门群岛皮金语',
          pt: 'Pijin das Ilhas Salomão',
          ru: 'Пиджин Соломоновых островов',
          es: 'Pijin de las Islas Salomón',
          fr: 'Pijin des Îles Salomon',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 148,
        id_flag: null,
        abbreviation: 'so',
        version: null,
        name: JSON.stringify({
          en: 'Somali',
          de: 'Somali',
          it: 'Somalo',
          ja: 'ソマリ語',
          ko: '소말리아어',
          zh: '索马里语',
          pt: 'Somali',
          ru: 'Сомалийский',
          es: 'Somalí',
          fr: 'Somali',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 149,
        id_flag: null,
        abbreviation: 'st',
        version: null,
        name: JSON.stringify({
          en: 'Southern Sotho',
          de: 'Süd-Sotho',
          it: 'Sotho del sud',
          ja: '南部ソト語',
          ko: '남부 소토어',
          zh: '南索托语',
          pt: 'Soto do sul',
          ru: 'Южный сото',
          es: 'Sotho meridional',
          fr: 'Sotho du Sud',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 150,
        id_flag: null,
        abbreviation: 'es',
        version: null,
        name: JSON.stringify({
          en: 'Spanish',
          de: 'Spanisch',
          it: 'Spagnolo',
          ja: 'スペイン語',
          ko: '스페인어',
          zh: '西班牙语',
          pt: 'Espanhol',
          ru: 'Испанский',
          es: 'Español',
          fr: 'Espagnol',
        }),
        description: null,
        orientation: 'L2R',
        public: 1,
      },
      {
        id: 151,
        id_flag: null,
        abbreviation: 'srn',
        version: null,
        name: JSON.stringify({
          en: 'Sranan Tongo',
          de: 'Sranan Tongo',
          it: 'Sranan Tongo',
          ja: 'スラナン・トンゴ語',
          ko: '스라난 통고어',
          zh: '苏里南汤加语',
          pt: 'Surinamês',
          ru: 'Сранан-тонго',
          es: 'Sranan tongo',
          fr: 'Sranan tongo',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 152,
        id_flag: null,
        abbreviation: 'sw',
        version: null,
        name: JSON.stringify({
          en: 'Swahili',
          de: 'Suaheli',
          it: 'Swahili',
          ja: 'スワヒリ語',
          ko: '스와힐리어',
          zh: '斯瓦希里语',
          pt: 'Suaíli',
          ru: 'Суахили',
          es: 'Suajili',
          fr: 'Swahili',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 153,
        id_flag: null,
        abbreviation: 'ss',
        version: null,
        name: JSON.stringify({
          en: 'Swati',
          de: 'Swati',
          it: 'Swati',
          ja: 'スワジ語',
          ko: '스와티어',
          zh: '斯瓦蒂语',
          pt: 'Swati',
          ru: 'Свати',
          es: 'Suazi',
          fr: 'Swati',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 154,
        id_flag: null,
        abbreviation: 'sv',
        version: null,
        name: JSON.stringify({
          en: 'Swedish',
          de: 'Schwedisch',
          it: 'Svedese',
          ja: 'スウェーデン語',
          ko: '스웨덴어',
          zh: '瑞典语',
          pt: 'Sueco',
          ru: 'Шведский',
          es: 'Sueco',
          fr: 'Suédois',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 155,
        id_flag: null,
        abbreviation: 'ty',
        version: null,
        name: JSON.stringify({
          en: 'Tahitian',
          de: 'Tahitianisch',
          it: 'Tahitiano',
          ja: 'タヒチ語',
          ko: '타히티어',
          zh: '塔希提语',
          pt: 'Taitiano',
          ru: 'Таитянский',
          es: 'Tahitiano',
          fr: 'Tahitien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 156,
        id_flag: null,
        abbreviation: 'tg',
        version: null,
        name: JSON.stringify({
          en: 'Tajik',
          de: 'Tadschikisch',
          it: 'Tagico',
          ja: 'タジク語',
          ko: '타지크어',
          zh: '塔吉克语',
          pt: 'Tajique',
          ru: 'Таджикский',
          es: 'Tayiko',
          fr: 'Tadjik',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 157,
        id_flag: null,
        abbreviation: 'ta',
        version: null,
        name: JSON.stringify({
          en: 'Tamil',
          de: 'Tamil',
          it: 'Tamil',
          ja: 'タミル語',
          ko: '타밀어',
          zh: '泰米尔语',
          pt: 'Tâmil',
          ru: 'Тамильский',
          es: 'Tamil',
          fr: 'Tamoul',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 158,
        id_flag: null,
        abbreviation: 'te',
        version: null,
        name: JSON.stringify({
          en: 'Telugu',
          de: 'Telugu',
          it: 'Telugu',
          ja: 'テルグ語',
          ko: '텔루구어',
          zh: '泰卢固语',
          pt: 'Télugo',
          ru: 'Телугу',
          es: 'Telugu',
          fr: 'Télougou',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 159,
        id_flag: null,
        abbreviation: 'tem',
        version: null,
        name: JSON.stringify({
          en: 'Temne',
          de: 'Temne',
          it: 'Temne',
          ja: 'テムネ語',
          ko: '템네어',
          zh: '泰姆奈语',
          pt: 'Temne',
          ru: 'Темне',
          es: 'Temne',
          fr: 'Temne',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 160,
        id_flag: null,
        abbreviation: 'tet',
        version: null,
        name: JSON.stringify({
          en: 'Tetum',
          de: 'Tetum',
          it: 'Tetum',
          ja: 'テトゥン語',
          ko: '테툼어',
          zh: '德顿语',
          pt: 'Tétum',
          ru: 'Тетум',
          es: 'Tetun',
          fr: 'Tetum',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 161,
        id_flag: null,
        abbreviation: 'th',
        version: null,
        name: JSON.stringify({
          en: 'Thai',
          de: 'Thailändisch',
          it: 'Thai',
          ja: 'タイ語',
          ko: '태국어',
          zh: '泰语',
          pt: 'Tailandês',
          ru: 'Тайский',
          es: 'Tailandés',
          fr: 'Thaï',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 162,
        id_flag: null,
        abbreviation: 'thr',
        version: null,
        name: JSON.stringify({
          en: 'Tharu',
          de: 'Tharu',
          it: 'Tharu',
          ja: 'タル語',
          ko: '타루어',
          zh: '塔鲁语',
          pt: 'Tharu',
          ru: 'Тхару',
          es: 'Tharu',
          fr: 'Tharu',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 163,
        id_flag: null,
        abbreviation: 'ti',
        version: null,
        name: JSON.stringify({
          en: 'Tigrinya',
          de: 'Tigrinya',
          it: 'Tigrino',
          ja: 'ティグリニャ語',
          ko: '티그리냐어',
          zh: '提格利尼亚语',
          pt: 'Tigrínia',
          ru: 'Тигринья',
          es: 'Tigriña',
          fr: 'Tigrigna',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 164,
        id_flag: null,
        abbreviation: 'tpi',
        version: null,
        name: JSON.stringify({
          en: 'Tok Pisin',
          de: 'Tok Pisin',
          it: 'Tok Pisin',
          ja: 'トク・ピシン語',
          ko: '토크 피신어',
          zh: '托克皮辛语',
          pt: 'Tok Pisin',
          ru: 'Ток-писин',
          es: 'Tok pisin',
          fr: 'Tok pisin',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 165,
        id_flag: null,
        abbreviation: 'tkl',
        version: null,
        name: JSON.stringify({
          en: 'Tokelauan',
          de: 'Tokelauanisch',
          it: 'Tokelauano',
          ja: 'トケラウ語',
          ko: '토켈라우어',
          zh: '托克劳语',
          pt: 'Tokelauano',
          ru: 'Токелау',
          es: 'Tokelauano',
          fr: 'Tokelau',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 166,
        id_flag: null,
        abbreviation: 'to',
        version: null,
        name: JSON.stringify({
          en: 'Tongan',
          de: 'Tongaisch',
          it: 'Tongano',
          ja: 'トンガ語',
          ko: '통가어',
          zh: '汤加语',
          pt: 'Tonganês',
          ru: 'Тонганский',
          es: 'Tongano',
          fr: 'Tongien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 167,
        id_flag: null,
        abbreviation: 'lua',
        version: null,
        name: JSON.stringify({
          en: 'Tshiluba',
          de: 'Tshiluba',
          it: 'Tshiluba',
          ja: 'チルバ語',
          ko: '칠루바어',
          zh: '奇卢伯语',
          pt: 'Tchiluba',
          ru: 'Чилуба',
          es: 'Tshiluba',
          fr: 'Tshiluba',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 168,
        id_flag: null,
        abbreviation: 'tr',
        version: null,
        name: JSON.stringify({
          en: 'Turkish',
          de: 'Türkisch',
          it: 'Turco',
          ja: 'トルコ語',
          ko: '터키어',
          zh: '土耳其语',
          pt: 'Turco',
          ru: 'Турецкий',
          es: 'Turco',
          fr: 'Turc',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 169,
        id_flag: null,
        abbreviation: 'tk',
        version: null,
        name: JSON.stringify({
          en: 'Turkmen',
          de: 'Turkmenisch',
          it: 'Turkmeno',
          ja: 'トルクメン語',
          ko: '투르크멘어',
          zh: '土库曼语',
          pt: 'Turcomeno',
          ru: 'Туркменский',
          es: 'Turcomano',
          fr: 'Turkmène',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 170,
        id_flag: null,
        abbreviation: 'tvl',
        version: null,
        name: JSON.stringify({
          en: 'Tuvaluan',
          de: 'Tuvaluisch',
          it: 'Tuvaluano',
          ja: 'ツバル語',
          ko: '투발루어',
          zh: '图瓦卢语',
          pt: 'Tuvaluano',
          ru: 'Тувалу',
          es: 'Tuvaluano',
          fr: 'Tuvalu',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 171,
        id_flag: null,
        abbreviation: 'uk',
        version: null,
        name: JSON.stringify({
          en: 'Ukrainian',
          de: 'Ukrainisch',
          it: 'Ucraino',
          ja: 'ウクライナ語',
          ko: '우크라이나어',
          zh: '乌克兰语',
          pt: 'Ucraniano',
          ru: 'Украинский',
          es: 'Ucraniano',
          fr: 'Ukrainien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 172,
        id_flag: null,
        abbreviation: 'ur',
        version: null,
        name: JSON.stringify({
          en: 'Urdu',
          de: 'Urdu',
          it: 'Urdu',
          ja: 'ウルドゥー語',
          ko: '우르두어',
          zh: '乌尔都语',
          pt: 'Urdu',
          ru: 'Урду',
          es: 'Urdu',
          fr: 'Ourdou',
        }),
        description: null,
        orientation: 'R2L',
        public: 0,
      },
      {
        id: 173,
        id_flag: null,
        abbreviation: 'uz',
        version: null,
        name: JSON.stringify({
          en: 'Uzbek',
          de: 'Usbekisch',
          it: 'Uzbeco',
          ja: 'ウズベク語',
          ko: '우즈베크어',
          zh: '乌兹别克语',
          pt: 'Uzbeque',
          ru: 'Узбекский',
          es: 'Uzbeko',
          fr: 'Ouzbek',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 174,
        id_flag: null,
        abbreviation: 'vi',
        version: null,
        name: JSON.stringify({
          en: 'Vietnamese',
          de: 'Vietnamesisch',
          it: 'Vietnamita',
          ja: 'ベトナム語',
          ko: '베트남어',
          zh: '越南语',
          pt: 'Vietnamita',
          ru: 'Вьетнамский',
          es: 'Vietnamita',
          fr: 'Vietnamien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 175,
        id_flag: null,
        abbreviation: 'wls',
        version: null,
        name: JSON.stringify({
          en: 'Wallisian',
          de: 'Wallisianisch',
          it: 'Wallisiano',
          ja: 'ワリス語',
          ko: '왈리스어',
          zh: '瓦利斯语',
          pt: 'Wallisiano',
          ru: 'Уоллисский',
          es: 'Wallisiano',
          fr: 'Wallisien',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 176,
        id_flag: null,
        abbreviation: 'wo',
        version: null,
        name: JSON.stringify({
          en: 'Wolof',
          de: 'Wolof',
          it: 'Wolof',
          ja: 'ウォロフ語',
          ko: '월로프어',
          zh: '沃洛夫语',
          pt: 'Uólofe',
          ru: 'Волоф',
          es: 'Wólof',
          fr: 'Wolof',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 177,
        id_flag: null,
        abbreviation: 'xh',
        version: null,
        name: JSON.stringify({
          en: 'Xhosa',
          de: 'Xhosa',
          it: 'Xhosa',
          ja: 'コサ語',
          ko: '코사어',
          zh: '科萨语',
          pt: 'Xhosa',
          ru: 'Коса',
          es: 'Xhosa',
          fr: 'Xhosa',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 178,
        id_flag: null,
        abbreviation: 'yo',
        version: null,
        name: JSON.stringify({
          en: 'Yoruba',
          de: 'Yoruba',
          it: 'Yoruba',
          ja: 'ヨルバ語',
          ko: '요루바어',
          zh: '约鲁巴语',
          pt: 'Iorubá',
          ru: 'Йоруба',
          es: 'Yoruba',
          fr: 'Yoruba',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 179,
        id_flag: null,
        abbreviation: 'dje',
        version: null,
        name: JSON.stringify({
          en: 'Zarma',
          de: 'Zarma',
          it: 'Zarma',
          ja: 'ザルマ語',
          ko: '자르마어',
          zh: '哲尔马语',
          pt: 'Zarma',
          ru: 'Зарма',
          es: 'Zarma',
          fr: 'Zarma',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
      {
        id: 180,
        id_flag: null,
        abbreviation: 'zu',
        version: null,
        name: JSON.stringify({
          en: 'Zulu',
          de: 'Zulu',
          it: 'Zulu',
          ja: 'ズールー語',
          ko: '줄루어',
          zh: '祖鲁语',
          pt: 'Zulu',
          ru: 'Зулу',
          es: 'Zulú',
          fr: 'Zoulou',
        }),
        description: null,
        orientation: 'L2R',
        public: 0,
      },
    ];

    return languages;
  },

  up: async (queryInterface) => {
    const batchSize = 50;
    const languages = this.get();

    for (let i = 0; i < languages.length; i += batchSize) {
      const batch = languages.slice(i, i + batchSize);
      for (const language of batch) {
        await queryInterface.bulkInsert('data_languages', [language], {
          updateOnDuplicate: ['flag_id', 'abbreviation', 'version', 'name', 'description', 'orientation', 'public'],
        });
      }
    }
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('data_languages', null, {});
  },
};
