'use strict';

module.exports = {
  get: () => {
    const currencies = [
      {
        id: 1,
        name: JSON.stringify({
          en: 'Afghan Afghani',
          de: 'Afghanischer Afghani',
          it: 'Afghani afghano',
          ja: 'アフガニ・アフガニスタン',
          ko: '아프가니스탄 아프가니',
          zh: '阿富汗阿富汗尼',
          pt: 'Afegane afegão',
          ru: 'Афганский афгани',
          es: 'Afgani afgano',
          fr: 'Afghani afghan',
        }),
        abbreviation: 'AFN',
        symbol: '؋',
      },
      {
        id: 2,
        name: JSON.stringify({
          en: 'United Arab Emirates Dirham',
          de: 'VAE-Dirham',
          it: 'Dirham degli Emirati Arabi Uniti',
          ja: 'アラブ首長国連邦ディルハム',
          ko: '아랍에미리트 디르함',
          zh: '阿联酋迪拉姆',
          pt: 'Dirrã dos Emirados Árabes Unidos',
          ru: 'Дирхам ОАЭ',
          es: 'Dírham de los Emiratos Árabes Unidos',
          fr: 'Dirham des Émirats arabes unis',
        }),
        abbreviation: 'AED',
        symbol: 'د.إ',
      },
      {
        id: 3,
        name: JSON.stringify({
          en: 'Albanian Lek',
          de: 'Albanischer Lek',
          it: 'Lek albanese',
          ja: 'アルバニアレク',
          ko: '알바니아 레크',
          zh: '阿尔巴尼亚列克',
          pt: 'Lek albanês',
          ru: 'Албанский лек',
          es: 'Lek albanés',
          fr: 'Lek albanais',
        }),
        abbreviation: 'ALL',
        symbol: 'L',
      },
      {
        id: 4,
        name: JSON.stringify({
          en: 'Armenian Dram',
          de: 'Armenischer Dram',
          it: 'Dram armeno',
          ja: 'アルメニアドラム',
          ko: '아르메니아 드람',
          zh: '亚美尼亚德拉姆',
          pt: 'Dram armênio',
          ru: 'Армянский драм',
          es: 'Dram armenio',
          fr: 'Dram arménien',
        }),
        abbreviation: 'AMD',
        symbol: '֏',
      },
      {
        id: 5,
        name: JSON.stringify({
          en: 'Netherlands Antillean Guilder',
          de: 'Niederländische-Antillen-Gulden',
          it: 'Fiorino delle Antille Olandesi',
          ja: 'オランダ領アンティルギルダー',
          ko: '네덜란드령 안틸레스 길더',
          zh: '荷属安的列斯盾',
          pt: 'Florim das Antilhas Holandesas',
          ru: 'Нидерландский антильский гульден',
          es: 'Florín de las Antillas Neerlandesas',
          fr: 'Florin des Antilles néerlandaises',
        }),
        abbreviation: 'ANG',
        symbol: 'ƒ',
      },
      {
        id: 6,
        name: JSON.stringify({
          en: 'Angolan Kwanza',
          de: 'Angolanischer Kwanza',
          it: 'Kwanza angolano',
          ja: 'アンゴラクワンザ',
          ko: '앙골라 콴자',
          zh: '安哥拉宽扎',
          pt: 'Kwanza angolano',
          ru: 'Ангольская кванза',
          es: 'Kwanza angoleño',
          fr: 'Kwanza angolais',
        }),
        abbreviation: 'AOA',
        symbol: 'Kz',
      },
      {
        id: 7,
        name: JSON.stringify({
          en: 'Argentine Peso',
          de: 'Argentinischer Peso',
          it: 'Peso argentino',
          ja: 'アルゼンチンペソ',
          ko: '아르헨티나 페소',
          zh: '阿根廷比索',
          pt: 'Peso argentino',
          ru: 'Аргентинский песо',
          es: 'Peso argentino',
          fr: 'Peso argentin',
        }),
        abbreviation: 'ARS',
        symbol: '$',
      },
      {
        id: 8,
        name: JSON.stringify({
          en: 'Australian Dollar',
          de: 'Australischer Dollar',
          it: 'Dollaro australiano',
          ja: 'オーストラリアドル',
          ko: '호주 달러',
          zh: '澳大利亚元',
          pt: 'Dólar australiano',
          ru: 'Австралийский доллар',
          es: 'Dólar australiano',
          fr: 'Dollar australien',
        }),
        abbreviation: 'AUD',
        symbol: 'A$',
      },
      {
        id: 9,
        name: JSON.stringify({
          en: 'Aruban Florin',
          de: 'Aruba-Florin',
          it: 'Fiorino di Aruba',
          ja: 'アルバフロリン',
          ko: '아루바 플로린',
          zh: '阿鲁巴弗罗林',
          pt: 'Florim de Aruba',
          ru: 'Арубанский флорин',
          es: 'Florín arubeño',
          fr: 'Florin arubais',
        }),
        abbreviation: 'AWG',
        symbol: 'ƒ',
      },
      {
        id: 10,
        name: JSON.stringify({
          en: 'Azerbaijani Manat',
          de: 'Aserbaidschan-Manat',
          it: 'Manat azero',
          ja: 'アゼルバイジャンマナト',
          ko: '아제르바이잔 마나트',
          zh: '阿塞拜疆马纳特',
          pt: 'Manat azeri',
          ru: 'Азербайджанский манат',
          es: 'Manat azerbaiyano',
          fr: 'Manat azerbaïdjanais',
        }),
        abbreviation: 'AZN',
        symbol: '₼',
      },
      {
        id: 11,
        name: JSON.stringify({
          en: 'Bosnia and Herzegovina Convertible Mark',
          de: 'Konvertible Mark Bosnien und Herzegowina',
          it: 'Marco convertibile della Bosnia ed Erzegovina',
          ja: 'ボスニア・ヘルツェゴビナ兌換マルク',
          ko: '보스니아 헤르체고비나 태환 마르크',
          zh: '波斯尼亚和黑塞哥维那可兑换马克',
          pt: 'Marco conversível da Bósnia e Herzegovina',
          ru: 'Конвертируемая марка Боснии и Герцеговины',
          es: 'Marco convertible de Bosnia y Herzegovina',
          fr: 'Mark convertible de Bosnie-Herzégovine',
        }),
        abbreviation: 'BAM',
        symbol: 'KM',
      },
      {
        id: 12,
        name: JSON.stringify({
          en: 'Barbadian Dollar',
          de: 'Barbados-Dollar',
          it: 'Dollaro barbadiano',
          ja: 'バルバドスドル',
          ko: '바베이도스 달러',
          zh: '巴巴多斯元',
          pt: 'Dólar barbadense',
          ru: 'Барбадосский доллар',
          es: 'Dólar barbadense',
          fr: 'Dollar barbadien',
        }),
        abbreviation: 'BBD',
        symbol: 'Bds$',
      },
      {
        id: 13,
        name: JSON.stringify({
          en: 'Bangladeshi Taka',
          de: 'Bangladesch-Taka',
          it: 'Taka bengalese',
          ja: 'バングラデシュタカ',
          ko: '방글라데시 타카',
          zh: '孟加拉国塔卡',
          pt: 'Taka bengali',
          ru: 'Бангладешская така',
          es: 'Taka de Bangladés',
          fr: 'Taka bangladais',
        }),
        abbreviation: 'BDT',
        symbol: '৳',
      },
      {
        id: 14,
        name: JSON.stringify({
          en: 'Bulgarian Lev',
          de: 'Bulgarischer Lew',
          it: 'Lev bulgaro',
          ja: 'ブルガリアレフ',
          ko: '불가리아 레프',
          zh: '保加利亚列弗',
          pt: 'Lev búlgaro',
          ru: 'Болгарский лев',
          es: 'Lev búlgaro',
          fr: 'Lev bulgare',
        }),
        abbreviation: 'BGN',
        symbol: 'лв',
      },
      {
        id: 15,
        name: JSON.stringify({
          en: 'Bahraini Dinar',
          de: 'Bahrain-Dinar',
          it: 'Dinaro del Bahrein',
          ja: 'バーレーンディナール',
          ko: '바레인 디나르',
          zh: '巴林第纳尔',
          pt: 'Dinar bareinita',
          ru: 'Бахрейнский динар',
          es: 'Dinar bahreiní',
          fr: 'Dinar bahreïni',
        }),
        abbreviation: 'BHD',
        symbol: '.د.ب',
      },
      {
        id: 16,
        name: JSON.stringify({
          en: 'Burundian Franc',
          de: 'Burundi-Franc',
          it: 'Franco del Burundi',
          ja: 'ブルンジフラン',
          ko: '부룬디 프랑',
          zh: '布隆迪法郎',
          pt: 'Franco burundiano',
          ru: 'Бурундийский франк',
          es: 'Franco burundiano',
          fr: 'Franc burundais',
        }),
        abbreviation: 'BIF',
        symbol: 'FBu',
      },
      {
        id: 17,
        name: JSON.stringify({
          en: 'Bermudian Dollar',
          de: 'Bermuda-Dollar',
          it: 'Dollaro delle Bermuda',
          ja: 'バミューダドル',
          ko: '버뮤다 달러',
          zh: '百慕大元',
          pt: 'Dólar bermudense',
          ru: 'Бермудский доллар',
          es: 'Dólar bermudeño',
          fr: 'Dollar bermudien',
        }),
        abbreviation: 'BMD',
        symbol: 'BD$',
      },
      {
        id: 18,
        name: JSON.stringify({
          en: 'Brunei Dollar',
          de: 'Brunei-Dollar',
          it: 'Dollaro del Brunei',
          ja: 'ブルネイドル',
          ko: '브루나이 달러',
          zh: '文莱元',
          pt: 'Dólar bruneano',
          ru: 'Брунейский доллар',
          es: 'Dólar de Brunéi',
          fr: 'Dollar brunéien',
        }),
        abbreviation: 'BND',
        symbol: 'B$',
      },
      {
        id: 19,
        name: JSON.stringify({
          en: 'Bolivian Boliviano',
          de: 'Bolivianischer Boliviano',
          it: 'Boliviano boliviano',
          ja: 'ボリビアボリビアーノ',
          ko: '볼리비아 볼리비아노',
          zh: '玻利维亚诺',
          pt: 'Boliviano boliviano',
          ru: 'Боливийский боливиано',
          es: 'Boliviano boliviano',
          fr: 'Boliviano bolivien',
        }),
        abbreviation: 'BOB',
        symbol: 'Bs.',
      },
      {
        id: 20,
        name: JSON.stringify({
          en: 'Brazilian Real',
          de: 'Brasilianischer Real',
          it: 'Real brasiliano',
          ja: 'ブラジルレアル',
          ko: '브라질 헤알',
          zh: '巴西雷亚尔',
          pt: 'Real brasileiro',
          ru: 'Бразильский реал',
          es: 'Real brasileño',
          fr: 'Réal brésilien',
        }),
        abbreviation: 'BRL',
        symbol: 'R$',
      },
      {
        id: 21,
        name: JSON.stringify({
          en: 'Bahamian Dollar',
          de: 'Bahama-Dollar',
          it: 'Dollaro delle Bahamas',
          ja: 'バハマドル',
          ko: '바하마 달러',
          zh: '巴哈马元',
          pt: 'Dólar bahamense',
          ru: 'Багамский доллар',
          es: 'Dólar bahameño',
          fr: 'Dollar bahaméen',
        }),
        abbreviation: 'BSD',
        symbol: 'B$',
      },
      {
        id: 22,
        name: JSON.stringify({
          en: 'Bhutanese Ngultrum',
          de: 'Bhutan-Ngultrum',
          it: 'Ngultrum bhutanese',
          ja: 'ブータンニュルタム',
          ko: '부탄 눌트럼',
          zh: '不丹努尔特鲁姆',
          pt: 'Ngultrum butanês',
          ru: 'Бутанский нгултрум',
          es: 'Ngultrum de Bután',
          fr: 'Ngultrum bhoutanais',
        }),
        abbreviation: 'BTN',
        symbol: 'Nu.',
      },
      {
        id: 23,
        name: JSON.stringify({
          en: 'Botswana Pula',
          de: 'Botswana-Pula',
          it: 'Pula del Botswana',
          ja: 'ボツワナプラ',
          ko: '보츠와나 풀라',
          zh: '博茨瓦纳普拉',
          pt: 'Pula botsuanesa',
          ru: 'Ботсванская пула',
          es: 'Pula de Botsuana',
          fr: 'Pula botswanais',
        }),
        abbreviation: 'BWP',
        symbol: 'P',
      },
      {
        id: 24,
        name: JSON.stringify({
          en: 'Belarusian Ruble',
          de: 'Weißrussischer Rubel',
          it: 'Rublo bielorusso',
          ja: 'ベラルーシルーブル',
          ko: '벨라루스 루블',
          zh: '白俄罗斯卢布',
          pt: 'Rublo bielorrusso',
          ru: 'Белорусский рубль',
          es: 'Rublo bielorruso',
          fr: 'Rouble biélorusse',
        }),
        abbreviation: 'BYN',
        symbol: 'Br',
      },
      {
        id: 25,
        name: JSON.stringify({
          en: 'Belize Dollar',
          de: 'Belize-Dollar',
          it: 'Dollaro del Belize',
          ja: 'ベリーズドル',
          ko: '벨리즈 달러',
          zh: '伯利兹元',
          pt: 'Dólar belizenho',
          ru: 'Белизский доллар',
          es: 'Dólar beliceño',
          fr: 'Dollar bélizien',
        }),
        abbreviation: 'BZD',
        symbol: 'BZ$',
      },
      {
        id: 26,
        name: JSON.stringify({
          en: 'Canadian Dollar',
          de: 'Kanadischer Dollar',
          it: 'Dollaro canadese',
          ja: 'カナダドル',
          ko: '캐나다 달러',
          zh: '加拿大元',
          pt: 'Dólar canadense',
          ru: 'Канадский доллар',
          es: 'Dólar canadiense',
          fr: 'Dollar canadien',
        }),
        abbreviation: 'CAD',
        symbol: 'C$',
      },
      {
        id: 27,
        name: JSON.stringify({
          en: 'Congolese Franc',
          de: 'Kongo-Franc',
          it: 'Franco congolese',
          ja: 'コンゴフラン',
          ko: '콩고 프랑',
          zh: '刚果法郎',
          pt: 'Franco congolês',
          ru: 'Конголезский франк',
          es: 'Franco congoleño',
          fr: 'Franc congolais',
        }),
        abbreviation: 'CDF',
        symbol: 'FC',
      },
      {
        id: 28,
        name: JSON.stringify({
          en: 'Swiss Franc',
          de: 'Schweizer Franken',
          it: 'Franco svizzero',
          ja: 'スイスフラン',
          ko: '스위스 프랑',
          zh: '瑞士法郎',
          pt: 'Franco suíço',
          ru: 'Швейцарский франк',
          es: 'Franco suizo',
          fr: 'Franc suisse',
        }),
        abbreviation: 'CHF',
        symbol: 'CHF',
      },
      {
        id: 29,
        name: JSON.stringify({
          en: 'Chilean Peso',
          de: 'Chilenischer Peso',
          it: 'Peso cileno',
          ja: 'チリペソ',
          ko: '칠레 페소',
          zh: '智利比索',
          pt: 'Peso chileno',
          ru: 'Чилийский песо',
          es: 'Peso chileno',
          fr: 'Peso chilien',
        }),
        abbreviation: 'CLP',
        symbol: '$',
      },
      {
        id: 30,
        name: JSON.stringify({
          en: 'Chinese Yuan',
          de: 'Chinesischer Yuan',
          it: 'Yuan cinese',
          ja: '中国人民元',
          ko: '중국 위안',
          zh: '人民币',
          pt: 'Yuan chinês',
          ru: 'Китайский юань',
          es: 'Yuan chino',
          fr: 'Yuan chinois',
        }),
        abbreviation: 'CNY',
        symbol: '¥',
      },
      {
        id: 31,
        name: JSON.stringify({
          en: 'Colombian Peso',
          de: 'Kolumbianischer Peso',
          it: 'Peso colombiano',
          ja: 'コロンビアペソ',
          ko: '콜롬비아 페소',
          zh: '哥伦比亚比索',
          pt: 'Peso colombiano',
          ru: 'Колумбийский песо',
          es: 'Peso colombiano',
          fr: 'Peso colombien',
        }),
        abbreviation: 'COP',
        symbol: '$',
      },
      {
        id: 32,
        name: JSON.stringify({
          en: 'Costa Rican Colón',
          de: 'Costa-Rica-Colón',
          it: 'Colón costaricano',
          ja: 'コスタリカコロン',
          ko: '코스타리카 콜론',
          zh: '哥斯达黎加科朗',
          pt: 'Colón costa-riquenho',
          ru: 'Костариканский колон',
          es: 'Colón costarricense',
          fr: 'Colón costaricain',
        }),
        abbreviation: 'CRC',
        symbol: '₡',
      },
      {
        id: 33,
        name: JSON.stringify({
          en: 'Cuban Convertible Peso',
          de: 'Kubanischer Konvertibler Peso',
          it: 'Peso cubano convertibile',
          ja: 'キューバ兌換ペソ',
          ko: '쿠바 태환 페소',
          zh: '古巴可兑换比索',
          pt: 'Peso cubano conversível',
          ru: 'Кубинский конвертируемый песо',
          es: 'Peso cubano convertible',
          fr: 'Peso cubain convertible',
        }),
        abbreviation: 'CUC',
        symbol: 'CUC$',
      },
      {
        id: 34,
        name: JSON.stringify({
          en: 'Cuban Peso',
          de: 'Kubanischer Peso',
          it: 'Peso cubano',
          ja: 'キューバペソ',
          ko: '쿠바 페소',
          zh: '古巴比索',
          pt: 'Peso cubano',
          ru: 'Кубинский песо',
          es: 'Peso cubano',
          fr: 'Peso cubain',
        }),
        abbreviation: 'CUP',
        symbol: '₱',
      },
      {
        id: 35,
        name: JSON.stringify({
          en: 'Cape Verdean Escudo',
          de: 'Kap-Verde-Escudo',
          it: 'Escudo capoverdiano',
          ja: 'カーボベルデエスクード',
          ko: '카보베르데 에스쿠도',
          zh: '佛得角埃斯库多',
          pt: 'Escudo cabo-verdiano',
          ru: 'Эскудо Кабо-Верде',
          es: 'Escudo caboverdiano',
          fr: 'Escudo cap-verdien',
        }),
        abbreviation: 'CVE',
        symbol: 'Esc',
      },
      {
        id: 36,
        name: JSON.stringify({
          en: 'Czech Koruna',
          de: 'Tschechische Krone',
          it: 'Corona ceca',
          ja: 'チェココルナ',
          ko: '체코 코루나',
          zh: '捷克克朗',
          pt: 'Coroa tcheca',
          ru: 'Чешская крона',
          es: 'Corona checa',
          fr: 'Couronne tchèque',
        }),
        abbreviation: 'CZK',
        symbol: 'Kč',
      },
      {
        id: 37,
        name: JSON.stringify({
          en: 'Djiboutian Franc',
          de: 'Dschibuti-Franc',
          it: 'Franco di Gibuti',
          ja: 'ジブチフラン',
          ko: '지부티 프랑',
          zh: '吉布提法郎',
          pt: 'Franco djibutiano',
          ru: 'Джибутийский франк',
          es: 'Franco yibutiano',
          fr: 'Franc djiboutien',
        }),
        abbreviation: 'DJF',
        symbol: 'Fdj',
      },
      {
        id: 38,
        name: JSON.stringify({
          en: 'Danish Krone',
          de: 'Dänische Krone',
          it: 'Corona danese',
          ja: 'デンマーククローネ',
          ko: '덴마크 크로네',
          zh: '丹麦克朗',
          pt: 'Coroa dinamarquesa',
          ru: 'Датская крона',
          es: 'Corona danesa',
          fr: 'Couronne danoise',
        }),
        abbreviation: 'DKK',
        symbol: 'kr',
      },
      {
        id: 39,
        name: JSON.stringify({
          en: 'Dominican Peso',
          de: 'Dominikanischer Peso',
          it: 'Peso dominicano',
          ja: 'ドミニカペソ',
          ko: '도미니카 페소',
          zh: '多米尼加比索',
          pt: 'Peso dominicano',
          ru: 'Доминиканский песо',
          es: 'Peso dominicano',
          fr: 'Peso dominicain',
        }),
        abbreviation: 'DOP',
        symbol: 'RD$',
      },
      {
        id: 40,
        name: JSON.stringify({
          en: 'Algerian Dinar',
          de: 'Algerischer Dinar',
          it: 'Dinaro algerino',
          ja: 'アルジェリアディナール',
          ko: '알제리 디나르',
          zh: '阿尔及利亚第纳尔',
          pt: 'Dinar argelino',
          ru: 'Алжирский динар',
          es: 'Dinar argelino',
          fr: 'Dinar algérien',
        }),
        abbreviation: 'DZD',
        symbol: 'دج',
      },
      {
        id: 41,
        name: JSON.stringify({
          en: 'Egyptian Pound',
          de: 'Ägyptisches Pfund',
          it: 'Sterlina egiziana',
          ja: 'エジプトポンド',
          ko: '이집트 파운드',
          zh: '埃及镑',
          pt: 'Libra egípcia',
          ru: 'Египетский фунт',
          es: 'Libra egipcia',
          fr: 'Livre égyptienne',
        }),
        abbreviation: 'EGP',
        symbol: 'E£',
      },
      {
        id: 42,
        name: JSON.stringify({
          en: 'Eritrean Nakfa',
          de: 'Eritreischer Nakfa',
          it: 'Nakfa eritreo',
          ja: 'エリトリアナクファ',
          ko: '에리트리아 나크파',
          zh: '厄立特里亚纳克法',
          pt: 'Nakfa eritreia',
          ru: 'Эритрейская накфа',
          es: 'Nakfa eritreo',
          fr: 'Nakfa érythréen',
        }),
        abbreviation: 'ERN',
        symbol: 'Nfk',
      },
      {
        id: 43,
        name: JSON.stringify({
          en: 'Ethiopian Birr',
          de: 'Äthiopischer Birr',
          it: 'Birr etiope',
          ja: 'エチオピアブル',
          ko: '에티오피아 비르',
          zh: '埃塞俄比亚比尔',
          pt: 'Birr etíope',
          ru: 'Эфиопский быр',
          es: 'Birr etíope',
          fr: 'Birr éthiopien',
        }),
        abbreviation: 'ETB',
        symbol: 'Br',
      },
      {
        id: 44,
        name: JSON.stringify({
          en: 'Euro',
          de: 'Euro',
          it: 'Euro',
          ja: 'ユーロ',
          ko: '유로',
          zh: '欧元',
          pt: 'Euro',
          ru: 'Евро',
          es: 'Euro',
          fr: 'Euro',
        }),
        abbreviation: 'EUR',
        symbol: '€',
      },
      {
        id: 45,
        name: JSON.stringify({
          en: 'Fijian Dollar',
          de: 'Fidschi-Dollar',
          it: 'Dollaro delle Figi',
          ja: 'フィジードル',
          ko: '피지 달러',
          zh: '斐济元',
          pt: 'Dólar fijiano',
          ru: 'Фиджийский доллар',
          es: 'Dólar fiyiano',
          fr: 'Dollar fidjien',
        }),
        abbreviation: 'FJD',
        symbol: 'FJ$',
      },
      {
        id: 46,
        name: JSON.stringify({
          en: 'Falkland Islands Pound',
          de: 'Falkland-Pfund',
          it: 'Sterlina delle Falkland',
          ja: 'フォークランド諸島ポンド',
          ko: '포클랜드 제도 파운드',
          zh: '福克兰群岛镑',
          pt: 'Libra das Ilhas Falkland',
          ru: 'Фунт Фолклендских островов',
          es: 'Libra malvinense',
          fr: 'Livre des îles Falkland',
        }),
        abbreviation: 'FKP',
        symbol: 'FK£',
      },
      {
        id: 47,
        name: JSON.stringify({
          en: 'Pound Sterling',
          de: 'Britisches Pfund',
          it: 'Sterlina britannica',
          ja: '英ポンド',
          ko: '영국 파운드',
          zh: '英镑',
          pt: 'Libra esterlina',
          ru: 'Фунт стерлингов',
          es: 'Libra esterlina',
          fr: 'Livre sterling',
        }),
        abbreviation: 'GBP',
        symbol: '£',
      },
      {
        id: 48,
        name: JSON.stringify({
          en: 'Georgian Lari',
          de: 'Georgischer Lari',
          it: 'Lari georgiano',
          ja: 'ジョージアラリ',
          ko: '조지아 라리',
          zh: '格鲁吉亚拉里',
          pt: 'Lari georgiano',
          ru: 'Грузинский лари',
          es: 'Lari georgiano',
          fr: 'Lari géorgien',
        }),
        abbreviation: 'GEL',
        symbol: '₾',
      },
      {
        id: 49,
        name: JSON.stringify({
          en: 'Guernsey Pound',
          de: 'Guernsey-Pfund',
          it: 'Sterlina di Guernsey',
          ja: 'ガーンジーポンド',
          ko: '건지 파운드',
          zh: '根西镑',
          pt: 'Libra de Guernsey',
          ru: 'Фунт Гернси',
          es: 'Libra de Guernsey',
          fr: 'Livre de Guernesey',
        }),
        abbreviation: 'GGP',
        symbol: '£',
      },
      {
        id: 50,
        name: JSON.stringify({
          en: 'Ghanaian Cedi',
          de: 'Ghanaischer Cedi',
          it: 'Cedi ghanese',
          ja: 'ガーナセディ',
          ko: '가나 세디',
          zh: '加纳塞地',
          pt: 'Cedi ganês',
          ru: 'Ганский седи',
          es: 'Cedi ghanés',
          fr: 'Cedi ghanéen',
        }),
        abbreviation: 'GHS',
        symbol: '₵',
      },
      {
        id: 51,
        name: JSON.stringify({
          en: 'Gibraltar Pound',
          de: 'Gibraltar-Pfund',
          it: 'Sterlina di Gibilterra',
          ja: 'ジブラルタルポンド',
          ko: '지브롤터 파운드',
          zh: '直布罗陀镑',
          pt: 'Libra de Gibraltar',
          ru: 'Гибралтарский фунт',
          es: 'Libra de Gibraltar',
          fr: 'Livre de Gibraltar',
        }),
        abbreviation: 'GIP',
        symbol: '£',
      },
      {
        id: 52,
        name: JSON.stringify({
          en: 'Gambian Dalasi',
          de: 'Gambia-Dalasi',
          it: 'Dalasi gambiano',
          ja: 'ガンビアダラシ',
          ko: '감비아 달라시',
          zh: '冈比亚达拉西',
          pt: 'Dalasi gambiano',
          ru: 'Гамбийский даласи',
          es: 'Dalasi gambiano',
          fr: 'Dalasi gambien',
        }),
        abbreviation: 'GMD',
        symbol: 'D',
      },
      {
        id: 53,
        name: JSON.stringify({
          en: 'Guinean Franc',
          de: 'Guinea-Franc',
          it: 'Franco guineano',
          ja: 'ギニアフラン',
          ko: '기니 프랑',
          zh: '几内亚法郎',
          pt: 'Franco guineense',
          ru: 'Гвинейский франк',
          es: 'Franco guineano',
          fr: 'Franc guinéen',
        }),
        abbreviation: 'GNF',
        symbol: 'FG',
      },
      {
        id: 54,
        name: JSON.stringify({
          en: 'Guatemalan Quetzal',
          de: 'Guatemaltekischer Quetzal',
          it: 'Quetzal guatemalteco',
          ja: 'グアテマラケツァル',
          ko: '과테말라 케찰',
          zh: '危地马拉格查尔',
          pt: 'Quetzal guatemalteco',
          ru: 'Гватемальский кетсаль',
          es: 'Quetzal guatemalteco',
          fr: 'Quetzal guatémaltèque',
        }),
        abbreviation: 'GTQ',
        symbol: 'Q',
      },
      {
        id: 55,
        name: JSON.stringify({
          en: 'Guyanese Dollar',
          de: 'Guyana-Dollar',
          it: 'Dollaro della Guyana',
          ja: 'ガイアナドル',
          ko: '가이아나 달러',
          zh: '圭亚那元',
          pt: 'Dólar guianense',
          ru: 'Гайанский доллар',
          es: 'Dólar guyanés',
          fr: 'Dollar guyanais',
        }),
        abbreviation: 'GYD',
        symbol: 'GY$',
      },
      {
        id: 56,
        name: JSON.stringify({
          en: 'Hong Kong Dollar',
          de: 'Hongkong-Dollar',
          it: 'Dollaro di Hong Kong',
          ja: '香港ドル',
          ko: '홍콩 달러',
          zh: '港元',
          pt: 'Dólar de Hong Kong',
          ru: 'Гонконгский доллар',
          es: 'Dólar de Hong Kong',
          fr: 'Dollar de Hong Kong',
        }),
        abbreviation: 'HKD',
        symbol: 'HK$',
      },
      {
        id: 57,
        name: JSON.stringify({
          en: 'Honduran Lempira',
          de: 'Honduranischer Lempira',
          it: 'Lempira honduregna',
          ja: 'ホンジュラスレンピラ',
          ko: '온두라스 렘피라',
          zh: '洪都拉斯伦皮拉',
          pt: 'Lempira hondurenha',
          ru: 'Гондурасская лемпира',
          es: 'Lempira hondureño',
          fr: 'Lempira hondurien',
        }),
        abbreviation: 'HNL',
        symbol: 'L',
      },
      {
        id: 58,
        name: JSON.stringify({
          en: 'Croatian Kuna',
          de: 'Kroatische Kuna',
          it: 'Kuna croata',
          ja: 'クロアチアクーナ',
          ko: '크로아티아 쿠나',
          zh: '克罗地亚库纳',
          pt: 'Kuna croata',
          ru: 'Хорватская куна',
          es: 'Kuna croata',
          fr: 'Kuna croate',
        }),
        abbreviation: 'HRK',
        symbol: 'kn',
      },
      {
        id: 59,
        name: JSON.stringify({
          en: 'Haitian Gourde',
          de: 'Haitianische Gourde',
          it: 'Gourde haitiano',
          ja: 'ハイチグールド',
          ko: '아이티 구르드',
          zh: '海地古德',
          pt: 'Gourde haitiano',
          ru: 'Гаитянский гурд',
          es: 'Gourde haitiano',
          fr: 'Gourde haïtienne',
        }),
        abbreviation: 'HTG',
        symbol: 'G',
      },
      {
        id: 60,
        name: JSON.stringify({
          en: 'Hungarian Forint',
          de: 'Ungarischer Forint',
          it: 'Fiorino ungherese',
          ja: 'ハンガリーフォリント',
          ko: '헝가리 포린트',
          zh: '匈牙利福林',
          pt: 'Forint húngaro',
          ru: 'Венгерский форинт',
          es: 'Forinto húngaro',
          fr: 'Forint hongrois',
        }),
        abbreviation: 'HUF',
        symbol: 'Ft',
      },
      {
        id: 61,
        name: JSON.stringify({
          en: 'Indonesian Rupiah',
          de: 'Indonesische Rupiah',
          it: 'Rupia indonesiana',
          ja: 'インドネシアルピア',
          ko: '인도네시아 루피아',
          zh: '印尼盾',
          pt: 'Rupia indonésia',
          ru: 'Индонезийская рупия',
          es: 'Rupia indonesia',
          fr: 'Roupie indonésienne',
        }),
        abbreviation: 'IDR',
        symbol: 'Rp',
      },
      {
        id: 62,
        name: JSON.stringify({
          en: 'Israeli New Shekel',
          de: 'Israelischer Neuer Schekel',
          it: 'Nuovo shekel israeliano',
          ja: 'イスラエル新シェケル',
          ko: '이스라엘 신 셰켈',
          zh: '以色列新谢克尔',
          pt: 'Novo shekel israelense',
          ru: 'Израильский новый шекель',
          es: 'Nuevo shequel israelí',
          fr: 'Nouveau shekel israélien',
        }),
        abbreviation: 'ILS',
        symbol: '₪',
      },
      {
        id: 63,
        name: JSON.stringify({
          en: 'Indian Rupee',
          de: 'Indische Rupie',
          it: 'Rupia indiana',
          ja: 'インドルピー',
          ko: '인도 루피',
          zh: '印度卢比',
          pt: 'Rupia indiana',
          ru: 'Индийская рупия',
          es: 'Rupia india',
          fr: 'Roupie indienne',
        }),
        abbreviation: 'INR',
        symbol: '₹',
      },
      {
        id: 64,
        name: JSON.stringify({
          en: 'Iraqi Dinar',
          de: 'Irakischer Dinar',
          it: 'Dinaro iracheno',
          ja: 'イラクディナール',
          ko: '이라크 디나르',
          zh: '伊拉克第纳尔',
          pt: 'Dinar iraquiano',
          ru: 'Иракский динар',
          es: 'Dinar iraquí',
          fr: 'Dinar irakien',
        }),
        abbreviation: 'IQD',
        symbol: 'ع.د',
      },
      {
        id: 65,
        name: JSON.stringify({
          en: 'Iranian Rial',
          de: 'Iranischer Rial',
          it: 'Rial iraniano',
          ja: 'イランリアル',
          ko: '이란 리얄',
          zh: '伊朗里亚尔',
          pt: 'Rial iraniano',
          ru: 'Иранский риал',
          es: 'Rial iraní',
          fr: 'Rial iranien',
        }),
        abbreviation: 'IRR',
        symbol: '﷼',
      },
      {
        id: 66,
        name: JSON.stringify({
          en: 'Icelandic Króna',
          de: 'Isländische Krone',
          it: 'Corona islandese',
          ja: 'アイスランドクローナ',
          ko: '아이슬란드 크로나',
          zh: '冰岛克朗',
          pt: 'Coroa islandesa',
          ru: 'Исландская крона',
          es: 'Corona islandesa',
          fr: 'Couronne islandaise',
        }),
        abbreviation: 'ISK',
        symbol: 'kr',
      },
      {
        id: 67,
        name: JSON.stringify({
          en: 'Jamaican Dollar',
          de: 'Jamaika-Dollar',
          it: 'Dollaro giamaicano',
          ja: 'ジャマイカドル',
          ko: '자메이카 달러',
          zh: '牙买加元',
          pt: 'Dólar jamaicano',
          ru: 'Ямайский доллар',
          es: 'Dólar jamaiquino',
          fr: 'Dollar jamaïcain',
        }),
        abbreviation: 'JMD',
        symbol: 'J$',
      },
      {
        id: 68,
        name: JSON.stringify({
          en: 'Jordanian Dinar',
          de: 'Jordanischer Dinar',
          it: 'Dinaro giordano',
          ja: 'ヨルダンディナール',
          ko: '요르단 디나르',
          zh: '约旦第纳尔',
          pt: 'Dinar jordaniano',
          ru: 'Иорданский динар',
          es: 'Dinar jordano',
          fr: 'Dinar jordanien',
        }),
        abbreviation: 'JOD',
        symbol: 'د.ا',
      },
      {
        id: 69,
        name: JSON.stringify({
          en: 'Japanese Yen',
          de: 'Japanischer Yen',
          it: 'Yen giapponese',
          ja: '日本円',
          ko: '일본 엔',
          zh: '日元',
          pt: 'Iene japonês',
          ru: 'Японская иена',
          es: 'Yen japonés',
          fr: 'Yen japonais',
        }),
        abbreviation: 'JPY',
        symbol: '¥',
      },
      {
        id: 70,
        name: JSON.stringify({
          en: 'Kenyan Shilling',
          de: 'Kenia-Schilling',
          it: 'Scellino keniota',
          ja: 'ケニアシリング',
          ko: '케냐 실링',
          zh: '肯尼亚先令',
          pt: 'Xelim queniano',
          ru: 'Кенийский шиллинг',
          es: 'Chelín keniano',
          fr: 'Shilling kenyan',
        }),
        abbreviation: 'KES',
        symbol: 'KSh',
      },
      {
        id: 71,
        name: JSON.stringify({
          en: 'Kyrgyzstani Som',
          de: 'Kirgisischer Som',
          it: 'Som kirghiso',
          ja: 'キルギスソム',
          ko: '키르기스스탄 솜',
          zh: '吉尔吉斯斯坦索姆',
          pt: 'Som quirguiz',
          ru: 'Киргизский сом',
          es: 'Som kirguís',
          fr: 'Som kirghize',
        }),
        abbreviation: 'KGS',
        symbol: 'с',
      },
      {
        id: 72,
        name: JSON.stringify({
          en: 'Cambodian Riel',
          de: 'Kambodschanischer Riel',
          it: 'Riel cambogiano',
          ja: 'カンボジアリエル',
          ko: '캄보디아 리엘',
          zh: '柬埔寨瑞尔',
          pt: 'Riel cambojano',
          ru: 'Камбоджийский риель',
          es: 'Riel camboyano',
          fr: 'Riel cambodgien',
        }),
        abbreviation: 'KHR',
        symbol: '៛',
      },
      {
        id: 73,
        name: JSON.stringify({
          en: 'Comorian Franc',
          de: 'Komoren-Franc',
          it: 'Franco comoriano',
          ja: 'コモロフラン',
          ko: '코모로 프랑',
          zh: '科摩罗法郎',
          pt: 'Franco comorense',
          ru: 'Коморский франк',
          es: 'Franco comorano',
          fr: 'Franc comorien',
        }),
        abbreviation: 'KMF',
        symbol: 'CF',
      },
      {
        id: 74,
        name: JSON.stringify({
          en: 'North Korean Won',
          de: 'Nordkoreanischer Won',
          it: 'Won nordcoreano',
          ja: '北朝鮮ウォン',
          ko: '조선민주주의인민공화국 원',
          zh: '朝鲜圆',
          pt: 'Won norte-coreano',
          ru: 'Северокорейская вона',
          es: 'Won norcoreano',
          fr: 'Won nord-coréen',
        }),
        abbreviation: 'KPW',
        symbol: '₩',
      },
      {
        id: 75,
        name: JSON.stringify({
          en: 'South Korean Won',
          de: 'Südkoreanischer Won',
          it: 'Won sudcoreano',
          ja: '韓国ウォン',
          ko: '대한민국 원',
          zh: '韩元',
          pt: 'Won sul-coreano',
          ru: 'Южнокорейская вона',
          es: 'Won surcoreano',
          fr: 'Won sud-coréen',
        }),
        abbreviation: 'KRW',
        symbol: '₩',
      },
      {
        id: 76,
        name: JSON.stringify({
          en: 'Kuwaiti Dinar',
          de: 'Kuwait-Dinar',
          it: 'Dinaro kuwaitiano',
          ja: 'クウェートディナール',
          ko: '쿠ウェ이트 디나르',
          zh: '科威特第纳尔',
          pt: 'Dinar kuwaitiano',
          ru: 'Кувейтский динар',
          es: 'Dinar kuwaití',
          fr: 'Dinar koweïtien',
        }),
        abbreviation: 'KWD',
        symbol: 'د.ك',
      },
      {
        id: 77,
        name: JSON.stringify({
          en: 'Cayman Islands Dollar',
          de: 'Kaiman-Dollar',
          it: 'Dollaro delle Isole Cayman',
          ja: 'ケイマン諸島ドル',
          ko: '케이맨 제도 달러',
          zh: '开曼群岛元',
          pt: 'Dólar das Ilhas Cayman',
          ru: 'Доллар Каймановых островов',
          es: 'Dólar de las Islas Caimán',
          fr: 'Dollar des îles Caïmans',
        }),
        abbreviation: 'KYD',
        symbol: 'CI$',
      },
      {
        id: 78,
        name: JSON.stringify({
          en: 'Kazakhstani Tenge',
          de: 'Kasachischer Tenge',
          it: 'Tenge kazako',
          ja: 'カザフスタンテンゲ',
          ko: '카자흐스탄 텡게',
          zh: '哈萨克斯坦坚戈',
          pt: 'Tenge cazaque',
          ru: 'Казахстанский тенге',
          es: 'Tenge kazajo',
          fr: 'Tenge kazakh',
        }),
        abbreviation: 'KZT',
        symbol: '₸',
      },
      {
        id: 79,
        name: JSON.stringify({
          en: 'Lao Kip',
          de: 'Laotischer Kip',
          it: 'Kip laotiano',
          ja: 'ラオスキープ',
          ko: '라오스 킵',
          zh: '老挝基普',
          pt: 'Kip laosiano',
          ru: 'Лаосский кип',
          es: 'Kip laosiano',
          fr: 'Kip laotien',
        }),
        abbreviation: 'LAK',
        symbol: '₭',
      },
      {
        id: 80,
        name: JSON.stringify({
          en: 'Lebanese Pound',
          de: 'Libanesisches Pfund',
          it: 'Sterlina libanese',
          ja: 'レバノンポンド',
          ko: '레바논 파운드',
          zh: '黎巴嫩镑',
          pt: 'Libra libanesa',
          ru: 'Ливанский фунт',
          es: 'Libra libanesa',
          fr: 'Livre libanaise',
        }),
        abbreviation: 'LBP',
        symbol: 'ل.ل',
      },
      {
        id: 81,
        name: JSON.stringify({
          en: 'Sri Lankan Rupee',
          de: 'Sri-Lanka-Rupie',
          it: 'Rupia singalese',
          ja: 'スリランカルピー',
          ko: '스리랑카 루피',
          zh: '斯里兰卡卢比',
          pt: 'Rupia do Sri Lanka',
          ru: 'Шри-ланкийская рупия',
          es: 'Rupia de Sri Lanka',
          fr: 'Roupie srilankaise',
        }),
        abbreviation: 'LKR',
        symbol: 'Rs',
      },
      {
        id: 82,
        name: JSON.stringify({
          en: 'Liberian Dollar',
          de: 'Liberianischer Dollar',
          it: 'Dollaro liberiano',
          ja: 'リベリアドル',
          ko: '라이베리아 달러',
          zh: '利比里亚元',
          pt: 'Dólar liberiano',
          ru: 'Либерийский доллар',
          es: 'Dólar liberiano',
          fr: 'Dollar libérien',
        }),
        abbreviation: 'LRD',
        symbol: 'L$',
      },
      {
        id: 83,
        name: JSON.stringify({
          en: 'Lesotho Loti',
          de: 'Loti lesothischer',
          it: 'Loti lesothiano',
          ja: 'レソトロティ',
          ko: '레소토 로티',
          zh: '莱索托洛蒂',
          pt: 'Loti lesotiano',
          ru: 'Лоти Лесото',
          es: 'Loti de Lesoto',
          fr: 'Loti lesothan',
        }),
        abbreviation: 'LSL',
        symbol: 'L',
      },
      {
        id: 84,
        name: JSON.stringify({
          en: 'Libyan Dinar',
          de: 'Libyscher Dinar',
          it: 'Dinaro libico',
          ja: 'リビアディナール',
          ko: '리비아 디나르',
          zh: '利比亚第纳尔',
          pt: 'Dinar líbio',
          ru: 'Ливийский динар',
          es: 'Dinar libio',
          fr: 'Dinar libyen',
        }),
        abbreviation: 'LYD',
        symbol: 'ل.د',
      },
      {
        id: 85,
        name: JSON.stringify({
          en: 'Moroccan Dirham',
          de: 'Marokkanischer Dirham',
          it: 'Dirham marocchino',
          ja: 'モロッコディルハム',
          ko: '모로코 디르함',
          zh: '摩洛哥迪拉姆',
          pt: 'Dirrã marroquino',
          ru: 'Марокканский дирхам',
          es: 'Dírham marroquí',
          fr: 'Dirham marocain',
        }),
        abbreviation: 'MAD',
        symbol: 'د.م.',
      },
      {
        id: 86,
        name: JSON.stringify({
          en: 'Moldovan Leu',
          de: 'Moldauischer Leu',
          it: 'Leu moldavo',
          ja: 'モルドバレイ',
          ko: '몰도바 레우',
          zh: '摩尔多瓦列伊',
          pt: 'Leu moldavo',
          ru: 'Молдавский лей',
          es: 'Leu moldavo',
          fr: 'Leu moldave',
        }),
        abbreviation: 'MDL',
        symbol: 'L',
      },
      {
        id: 87,
        name: JSON.stringify({
          en: 'Malagasy Ariary',
          de: 'Madagassischer Ariary',
          it: 'Ariary malgascio',
          ja: 'マダガスカルアリアリ',
          ko: '마다가스카르 아리아리',
          zh: '马达加斯加阿里亚里',
          pt: 'Ariary malgaxe',
          ru: 'Малагасийский ариари',
          es: 'Ariary malgache',
          fr: 'Ariary malgache',
        }),
        abbreviation: 'MGA',
        symbol: 'Ar',
      },
      {
        id: 88,
        name: JSON.stringify({
          en: 'Macedonian Denar',
          de: 'Mazedonischer Denar',
          it: 'Denar macedone',
          ja: 'マケドニアデナル',
          ko: '마케도니아 데나르',
          zh: '马其顿代纳尔',
          pt: 'Dinar macedônio',
          ru: 'Македонский денар',
          es: 'Denar macedonio',
          fr: 'Denar macédonien',
        }),
        abbreviation: 'MKD',
        symbol: 'ден',
      },
      {
        id: 89,
        name: JSON.stringify({
          en: 'Myanmar Kyat',
          de: 'Myanmar-Kyat',
          it: 'Kyat birmano',
          ja: 'ミャンマーキャット',
          ko: '미얀마 캐럿',
          zh: '缅甸缅元',
          pt: 'Kyat birmanês',
          ru: 'Мьянманский кьят',
          es: 'Kyat de Myanmar',
          fr: 'Kyat birman',
        }),
        abbreviation: 'MMK',
        symbol: 'Ks',
      },
      {
        id: 90,
        name: JSON.stringify({
          en: 'Mongolian Tögrög',
          de: 'Mongolischer Tögrög',
          it: 'Tugrik mongolo',
          ja: 'モンゴルトゥグルグ',
          ko: '몽골 투그릭',
          zh: '蒙古图格里克',
          pt: 'Tugrik mongol',
          ru: 'Монгольский тугрик',
          es: 'Tugrik mongol',
          fr: 'Tugrik mongol',
        }),
        abbreviation: 'MNT',
        symbol: '₮',
      },
      {
        id: 91,
        name: JSON.stringify({
          en: 'Macanese Pataca',
          de: 'Macao-Pataca',
          it: 'Pataca di Macao',
          ja: 'マカオパタカ',
          ko: '마카오 파타카',
          zh: '澳门元',
          pt: 'Pataca macaense',
          ru: 'Патака Макао',
          es: 'Pataca macanesa',
          fr: 'Pataca macanaise',
        }),
        abbreviation: 'MOP',
        symbol: 'MOP$',
      },
      {
        id: 92,
        name: JSON.stringify({
          en: 'Mauritanian Ouguiya',
          de: 'Mauretanischer Ouguiya',
          it: 'Ouguiya mauritana',
          ja: 'モーリタニアウギア',
          ko: '모리타니아 우기야',
          zh: '毛里塔尼亚乌吉亚',
          pt: 'Ouguiya mauritana',
          ru: 'Мавританская угия',
          es: 'Uquiya mauritana',
          fr: 'Ouguiya mauritanienne',
        }),
        abbreviation: 'MRU',
        symbol: 'UM',
      },
      {
        id: 93,
        name: JSON.stringify({
          en: 'Mauritian Rupee',
          de: 'Mauritius-Rupie',
          it: 'Rupia mauriziana',
          ja: 'モーリシャスルピー',
          ko: '모리셔스 루피',
          zh: '毛里求斯卢比',
          pt: 'Rupia mauriciana',
          ru: 'Маврикийская рупия',
          es: 'Rupia mauriciana',
          fr: 'Roupie mauricienne',
        }),
        abbreviation: 'MUR',
        symbol: 'Rs',
      },
      {
        id: 94,
        name: JSON.stringify({
          en: 'Maldivian Rufiyaa',
          de: 'Malediven-Rufiyaa',
          it: 'Rufiyaa delle Maldive',
          ja: 'モルディブルフィヤ',
          ko: '몰디브 루피야',
          zh: '马尔代夫拉菲亚',
          pt: 'Rufia maldiviana',
          ru: 'Мальдивская руфия',
          es: 'Rufiyaa de Maldivas',
          fr: 'Rufiyaa maldivien',
        }),
        abbreviation: 'MVR',
        symbol: 'Rf',
      },
      {
        id: 95,
        name: JSON.stringify({
          en: 'Malawian Kwacha',
          de: 'Malawi-Kwacha',
          it: 'Kwacha malawiano',
          ja: 'マラウィクワチャ',
          ko: '말라위 콰차',
          zh: '马拉维克瓦查',
          pt: 'Kwacha malauiano',
          ru: 'Малавийская квача',
          es: 'Kwacha malauí',
          fr: 'Kwacha malawite',
        }),
        abbreviation: 'MWK',
        symbol: 'MK',
      },
      {
        id: 96,
        name: JSON.stringify({
          en: 'Mexican Peso',
          de: 'Mexikanischer Peso',
          it: 'Peso messicano',
          ja: 'メキシコペソ',
          ko: '멕시코 페소',
          zh: '墨西哥比索',
          pt: 'Peso mexicano',
          ru: 'Мексиканский песо',
          es: 'Peso mexicano',
          fr: 'Peso mexicain',
        }),
        abbreviation: 'MXN',
        symbol: '$',
      },
      {
        id: 97,
        name: JSON.stringify({
          en: 'Malaysian Ringgit',
          de: 'Malaysischer Ringgit',
          it: 'Ringgit malese',
          ja: 'マレーシアリンギット',
          ko: '말레이시아 링깃',
          zh: '马来西亚林吉特',
          pt: 'Ringgit malaio',
          ru: 'Малайзийский ринггит',
          es: 'Ringgit malayo',
          fr: 'Ringgit malaisien',
        }),
        abbreviation: 'MYR',
        symbol: 'RM',
      },
      {
        id: 98,
        name: JSON.stringify({
          en: 'Mozambican Metical',
          de: 'Mosambikanischer Metical',
          it: 'Metical mozambicano',
          ja: 'モザンビークメティカル',
          ko: '모잠비크 메티칼',
          zh: '莫桑比克梅蒂卡尔',
          pt: 'Metical moçambicano',
          ru: 'Мозамбикский метикал',
          es: 'Metical mozambiqueño',
          fr: 'Metical mozambicain',
        }),
        abbreviation: 'MZN',
        symbol: 'MT',
      },
      {
        id: 99,
        name: JSON.stringify({
          en: 'Namibian Dollar',
          de: 'Namibia-Dollar',
          it: 'Dollaro namibiano',
          ja: 'ナミビアドル',
          ko: '나미비아 달러',
          zh: '纳米比亚元',
          pt: 'Dólar namibiano',
          ru: 'Намибийский доллар',
          es: 'Dólar namibio',
          fr: 'Dollar namibien',
        }),
        abbreviation: 'NAD',
        symbol: 'N$',
      },
      {
        id: 100,
        name: JSON.stringify({
          en: 'Nigerian Naira',
          de: 'Nigerianischer Naira',
          it: 'Naira nigeriana',
          ja: 'ナイジェリアナイラ',
          ko: '나이지리아 나이라',
          zh: '尼日利亚奈拉',
          pt: 'Naira nigeriana',
          ru: 'Нигерийская найра',
          es: 'Naira nigeriana',
          fr: 'Naira nigérian',
        }),
        abbreviation: 'NGN',
        symbol: '₦',
      },
      {
        id: 101,
        name: JSON.stringify({
          en: 'Nicaraguan Córdoba',
          de: 'Nicaragua-Córdoba',
          it: 'Córdoba nicaraguense',
          ja: 'ニカラグアコルドバ',
          ko: '니카라과 코르도바',
          zh: '尼加拉瓜科多巴',
          pt: 'Córdoba nicaraguense',
          ru: 'Никарагуанская кордоба',
          es: 'Córdoba nicaragüense',
          fr: 'Córdoba nicaraguayen',
        }),
        abbreviation: 'NIO',
        symbol: 'C$',
      },
      {
        id: 102,
        name: JSON.stringify({
          en: 'Norwegian Krone',
          de: 'Norwegische Krone',
          it: 'Corona norvegese',
          ja: 'ノルウェークローネ',
          ko: '노르웨이 크로네',
          zh: '挪威克朗',
          pt: 'Coroa norueguesa',
          ru: 'Норвежская крона',
          es: 'Corona noruega',
          fr: 'Couronne norvégienne',
        }),
        abbreviation: 'NOK',
        symbol: 'kr',
      },
      {
        id: 103,
        name: JSON.stringify({
          en: 'Nepalese Rupee',
          de: 'Nepalesische Rupie',
          it: 'Rupia nepalese',
          ja: 'ネパールルピー',
          ko: '네팔 루피',
          zh: '尼泊尔卢比',
          pt: 'Rupia nepalesa',
          ru: 'Непальская рупия',
          es: 'Rupia nepalesa',
          fr: 'Roupie népalaise',
        }),
        abbreviation: 'NPR',
        symbol: 'Rs',
      },
      {
        id: 104,
        name: JSON.stringify({
          en: 'New Zealand Dollar',
          de: 'Neuseeland-Dollar',
          it: 'Dollaro neozelandese',
          ja: 'ニュージーランドドル',
          ko: '뉴질랜드 달러',
          zh: '新西兰元',
          pt: 'Dólar neozelandês',
          ru: 'Новозеландский доллар',
          es: 'Dólar neozelandés',
          fr: 'Dollar néo-zélandais',
        }),
        abbreviation: 'NZD',
        symbol: 'NZ$',
      },
      {
        id: 105,
        name: JSON.stringify({
          en: 'Omani Rial',
          de: 'Omanischer Rial',
          it: 'Rial omanita',
          ja: 'オマーンリアル',
          ko: '오만 리얄',
          zh: '阿曼里亚尔',
          pt: 'Rial omanense',
          ru: 'Оманский риал',
          es: 'Rial omaní',
          fr: 'Rial omanais',
        }),
        abbreviation: 'OMR',
        symbol: 'ر.ع.',
      },
      {
        id: 106,
        name: JSON.stringify({
          en: 'Panamanian Balboa',
          de: 'Panama-Balboa',
          it: 'Balboa panamense',
          ja: 'パナマバルボア',
          ko: '파나마 발보아',
          zh: '巴拿马巴波亚',
          pt: 'Balboa panamenha',
          ru: 'Панамский балбоа',
          es: 'Balboa panameño',
          fr: 'Balboa panaméen',
        }),
        abbreviation: 'PAB',
        symbol: 'B/.',
      },
      {
        id: 107,
        name: JSON.stringify({
          en: 'Peruvian Sol',
          de: 'Peruanischer Sol',
          it: 'Sol peruviano',
          ja: 'ペルーソル',
          ko: '페루 솔',
          zh: '秘鲁索尔',
          pt: 'Sol peruano',
          ru: 'Перуанский соль',
          es: 'Sol peruano',
          fr: 'Sol péruvien',
        }),
        abbreviation: 'PEN',
        symbol: 'S/',
      },
      {
        id: 108,
        name: JSON.stringify({
          en: 'Papua New Guinean Kina',
          de: 'Papua-Neuguinea-Kina',
          it: 'Kina della Papua Nuova Guinea',
          ja: 'パプアニューギニアキナ',
          ko: '파푸아뉴기니 키나',
          zh: '巴布亚新几内亚基那',
          pt: 'Kina papuásia',
          ru: 'Кина Папуа-Новой Гвинеи',
          es: 'Kina de Papúa Nueva Guinea',
          fr: 'Kina papouan-néo-guinéen',
        }),
        abbreviation: 'PGK',
        symbol: 'K',
      },
      {
        id: 109,
        name: JSON.stringify({
          en: 'Philippine Peso',
          de: 'Philippinischer Peso',
          it: 'Peso filippino',
          ja: 'フィリピンペソ',
          ko: '필리핀 페소',
          zh: '菲律宾比索',
          pt: 'Peso filipino',
          ru: 'Филиппинское песо',
          es: 'Peso filipino',
          fr: 'Peso philippin',
        }),
        abbreviation: 'PHP',
        symbol: '₱',
      },
      {
        id: 110,
        name: JSON.stringify({
          en: 'Pakistani Rupee',
          de: 'Pakistanische Rupie',
          it: 'Rupia pakistana',
          ja: 'パキスタンルピー',
          ko: '파키스탄 루피',
          zh: '巴基斯坦卢比',
          pt: 'Rupia paquistanesa',
          ru: 'Пакистанская рупия',
          es: 'Rupia pakistaní',
          fr: 'Roupie pakistanaise',
        }),
        abbreviation: 'PKR',
        symbol: 'Rs',
      },
      {
        id: 111,
        name: JSON.stringify({
          en: 'Polish Złoty',
          de: 'Polnischer Złoty',
          it: 'Złoty polacco',
          ja: 'ポーランドズウォティ',
          ko: '폴란드 즈워티',
          zh: '波兰兹罗提',
          pt: 'Złoty polonês',
          ru: 'Польский злотый',
          es: 'Zloty polaco',
          fr: 'Zloty polonais',
        }),
        abbreviation: 'PLN',
        symbol: 'zł',
      },
      {
        id: 112,
        name: JSON.stringify({
          en: 'Paraguayan Guaraní',
          de: 'Paraguayischer Guaraní',
          it: 'Guaraní paraguaiano',
          ja: 'パラグアイグアラニ',
          ko: '파라과이 과라니',
          zh: '巴拉圭瓜拉尼',
          pt: 'Guaraní paraguaio',
          ru: 'Парагвайский гуарани',
          es: 'Guaraní paraguayo',
          fr: 'Guaraní paraguayen',
        }),
        abbreviation: 'PYG',
        symbol: '₲',
      },
      {
        id: 113,
        name: JSON.stringify({
          en: 'Qatari Riyal',
          de: 'Katar-Riyal',
          it: 'Riyal qatariota',
          ja: 'カタールリヤル',
          ko: '카타르 리얄',
          zh: '卡塔尔里亚尔',
          pt: 'Rial catariano',
          ru: 'Катарский риал',
          es: 'Riyal qatarí',
          fr: 'Riyal qatarien',
        }),
        abbreviation: 'QAR',
        symbol: 'ر.ق.',
      },
      {
        id: 114,
        name: JSON.stringify({
          en: 'Romanian Leu',
          de: 'Rumänischer Leu',
          it: 'Leu rumeno',
          ja: 'ルーマニアレウ',
          ko: '루마니아 레우',
          zh: '罗马尼亚列伊',
          pt: 'Leu romeno',
          ru: 'Румынский лей',
          es: 'Leu rumano',
          fr: 'Leu roumain',
        }),
        abbreviation: 'RON',
        symbol: 'lei',
      },
      {
        id: 115,
        name: JSON.stringify({
          en: 'Serbian Dinar',
          de: 'Serbischer Dinar',
          it: 'Dinaro serbo',
          ja: 'セルビアディナール',
          ko: '세르비아 디나르',
          zh: '塞尔维亚第纳尔',
          pt: 'Dinar sérvio',
          ru: 'Сербский динар',
          es: 'Dinar serbio',
          fr: 'Dinar serbe',
        }),
        abbreviation: 'RSD',
        symbol: 'дин',
      },
      {
        id: 116,
        name: JSON.stringify({
          en: 'Russian Ruble',
          de: 'Russischer Rubel',
          it: 'Rublo russo',
          ja: 'ロシアルーブル',
          ko: '러시아 루블',
          zh: '俄罗斯卢布',
          pt: 'Rublo russo',
          ru: 'Российский рубль',
          es: 'Rublo ruso',
          fr: 'Rouble russe',
        }),
        abbreviation: 'RUB',
        symbol: '₽',
      },
      {
        id: 117,
        name: JSON.stringify({
          en: 'Rwandan Franc',
          de: 'Ruanda-Franc',
          it: 'Franco ruandese',
          ja: 'ルワンダフラン',
          ko: '르완다 프랑',
          zh: '卢旺达法郎',
          pt: 'Franco ruandês',
          ru: 'Франк Руанды',
          es: 'Franco ruandés',
          fr: 'Franc rwandais',
        }),
        abbreviation: 'RWF',
        symbol: 'FRw',
      },
      {
        id: 118,
        name: JSON.stringify({
          en: 'Saudi Riyal',
          de: 'Saudi-Riyal',
          it: 'Riyal saudita',
          ja: 'サウジアラビアリヤル',
          ko: '사우디아라비아 리얄',
          zh: '沙特里亚尔',
          pt: 'Rial saudita',
          ru: 'Саудовский риял',
          es: 'Riyal saudí',
          fr: 'Riyal saoudien',
        }),
        abbreviation: 'SAR',
        symbol: 'ر.س',
      },
      {
        id: 119,
        name: JSON.stringify({
          en: 'Solomon Islands Dollar',
          de: 'Salomonen-Dollar',
          it: 'Dollaro delle Isole Salomone',
          ja: 'ソロモン諸島ドル',
          ko: '솔로몬 제도 달러',
          zh: '所罗门群岛元',
          pt: 'Dólar das Ilhas Salomão',
          ru: 'Доллар Соломоновых Островов',
          es: 'Dólar salomonense',
          fr: 'Dollar des îles Salomon',
        }),
        abbreviation: 'SBD',
        symbol: 'SI$',
      },
      {
        id: 120,
        name: JSON.stringify({
          en: 'Seychellois Rupee',
          de: 'Seychellen-Rupie',
          it: 'Rupia delle Seychelles',
          ja: 'セーシェルルピー',
          ko: '세이셸 루피',
          zh: '塞舌尔卢比',
          pt: 'Rupia seichelense',
          ru: 'Сейшельская рупия',
          es: 'Rupia seychelense',
          fr: 'Roupie seychelloise',
        }),
        abbreviation: 'SCR',
        symbol: 'SR',
      },
      {
        id: 121,
        name: JSON.stringify({
          en: 'Sudanese Pound',
          de: 'Sudanesisches Pfund',
          it: 'Sterlina sudanese',
          ja: 'スーダンポンド',
          ko: '수단 파운드',
          zh: '苏丹镑',
          pt: 'Libra sudanesa',
          ru: 'Суданский фунт',
          es: 'Libra sudanesa',
          fr: 'Livre soudanaise',
        }),
        abbreviation: 'SDG',
        symbol: 'ج.س.',
      },
      {
        id: 122,
        name: JSON.stringify({
          en: 'Swedish Krona',
          de: 'Schwedische Krone',
          it: 'Corona svedese',
          ja: 'スウェーデンクローナ',
          ko: '스웨덴 크로나',
          zh: '瑞典克朗',
          pt: 'Coroa sueca',
          ru: 'Шведская крона',
          es: 'Corona sueca',
          fr: 'Couronne suédoise',
        }),
        abbreviation: 'SEK',
        symbol: 'kr',
      },
      {
        id: 123,
        name: JSON.stringify({
          en: 'Singapore Dollar',
          de: 'Singapur-Dollar',
          it: 'Dollaro di Singapore',
          ja: 'シンガポールドル',
          ko: '싱가포르 달러',
          zh: '新加坡元',
          pt: 'Dólar de Singapura',
          ru: 'Сингапурский доллар',
          es: 'Dólar de Singapur',
          fr: 'Dollar de Singapour',
        }),
        abbreviation: 'SGD',
        symbol: 'S$',
      },
      {
        id: 124,
        name: JSON.stringify({
          en: 'Saint Helena Pound',
          de: 'St.-Helena-Pfund',
          it: "Sterlina di Sant'Elena",
          ja: 'セントヘレナポンド',
          ko: '세인트헬레나 파운드',
          zh: '圣赫勒拿镑',
          pt: 'Libra de Santa Helena',
          ru: 'Фунт острова Святой Елены',
          es: 'Libra de Santa Elena',
          fr: 'Livre de Sainte-Hélène',
        }),
        abbreviation: 'SHP',
        symbol: '£',
      },
      {
        id: 125,
        name: JSON.stringify({
          en: 'Sierra Leonean Leone',
          de: 'Sierra-leonischer Leone',
          it: 'Leone della Sierra Leone',
          ja: 'シエラレオネレオン',
          ko: '시에라리온 리온',
          zh: '塞拉利昂利昂',
          pt: 'Leone de Serra Leoa',
          ru: 'Леоне Сьерра-Леоне',
          es: 'Leone de Sierra Leona',
          fr: 'Leone sierra-léonais',
        }),
        abbreviation: 'SLL',
        symbol: 'Le',
      },
      {
        id: 126,
        name: JSON.stringify({
          en: 'Somali Shilling',
          de: 'Somalia-Schilling',
          it: 'Scellino somalo',
          ja: 'ソマリアシリング',
          ko: '소말리아 실링',
          zh: '索马里先令',
          pt: 'Xelim somali',
          ru: 'Сомалийский шиллинг',
          es: 'Chelín somalí',
          fr: 'Shilling somalien',
        }),
        abbreviation: 'SOS',
        symbol: 'Sh',
      },
      {
        id: 127,
        name: JSON.stringify({
          en: 'Surinamese Dollar',
          de: 'Suriname-Dollar',
          it: 'Dollaro surinamese',
          ja: 'スリナムドル',
          ko: '수리남 달러',
          zh: '苏里南元',
          pt: 'Dólar do Suriname',
          ru: 'Суринамский доллар',
          es: 'Dólar surinamés',
          fr: 'Dollar surinamais',
        }),
        abbreviation: 'SRD',
        symbol: '$',
      },
      {
        id: 128,
        name: JSON.stringify({
          en: 'South Sudanese Pound',
          de: 'Südsudanesisches Pfund',
          it: 'Sterlina sudsudanese',
          ja: '南スーダンポンド',
          ko: '남수단 파운드',
          zh: '南苏丹镑',
          pt: 'Libra sul-sudanesa',
          ru: 'Южносуданский фунт',
          es: 'Libra sursudanesa',
          fr: 'Livre sud-soudanaise',
        }),
        abbreviation: 'SSP',
        symbol: '£',
      },
      {
        id: 129,
        name: JSON.stringify({
          en: 'São Tomé and Príncipe Dobra',
          de: 'São-toméische Dobra',
          it: 'Dobra di São Tomé e Príncipe',
          ja: 'サントメ・プリンシペドブラ',
          ko: '상투메 프린시페 도브라',
          zh: '圣多美和普林西比多布拉',
          pt: 'Dobra são-tomense',
          ru: 'Добра Сан-Томе и Принсипи',
          es: 'Dobra de Santo Tomé y Príncipe',
          fr: 'Dobra santoméen',
        }),
        abbreviation: 'STN',
        symbol: 'Db',
      },
      {
        id: 130,
        name: JSON.stringify({
          en: 'Swazi Lilangeni',
          de: 'Swasiländischer Lilangeni',
          it: 'Lilangeni dello Swaziland',
          ja: 'スワジランドリランゲニ',
          ko: '에스와티니 릴랑게니',
          zh: '斯威士兰里兰吉尼',
          pt: 'Lilangeni suázi',
          ru: 'Свазилендский лилангени',
          es: 'Lilangeni suazi',
          fr: 'Lilangeni swazi',
        }),
        abbreviation: 'SZL',
        symbol: 'E',
      },
      {
        id: 131,
        name: JSON.stringify({
          en: 'Syrian Pound',
          de: 'Syrisches Pfund',
          it: 'Sterlina siriana',
          ja: 'シリアポンド',
          ko: '시리아 파운드',
          zh: '叙利亚镑',
          pt: 'Libra síria',
          ru: 'Сирийский фунт',
          es: 'Libra siria',
          fr: 'Livre syrienne',
        }),
        abbreviation: 'SYP',
        symbol: '£',
      },
      {
        id: 132,
        name: JSON.stringify({
          en: 'Thai Baht',
          de: 'Thailändischer Baht',
          it: 'Baht thailandese',
          ja: 'タイバーツ',
          ko: '태국 밧',
          zh: '泰铢',
          pt: 'Baht tailandês',
          ru: 'Тайский бат',
          es: 'Baht tailandés',
          fr: 'Baht thaïlandais',
        }),
        abbreviation: 'THB',
        symbol: '฿',
      },
      {
        id: 133,
        name: JSON.stringify({
          en: 'Tajikistani Somoni',
          de: 'Tadschikischer Somoni',
          it: 'Somoni tagiko',
          ja: 'タジキスタンソモニ',
          ko: '타지키스탄 소모니',
          zh: '塔吉克斯坦索莫尼',
          pt: 'Somoni tajiquistanês',
          ru: 'Таджикский сомони',
          es: 'Somoni tayiko',
          fr: 'Somoni tadjik',
        }),
        abbreviation: 'TJS',
        symbol: 'SM',
      },
      {
        id: 134,
        name: JSON.stringify({
          en: 'Turkmenistan Manat',
          de: 'Turkmenistan-Manat',
          it: 'Manat turkmeno',
          ja: 'トルクメニスタンマナト',
          ko: '투르크메니스탄 마나트',
          zh: '土库曼斯坦马纳特',
          pt: 'Manat turcomeno',
          ru: 'Туркменский манат',
          es: 'Manat turcomano',
          fr: 'Manat turkmène',
        }),
        abbreviation: 'TMT',
        symbol: 'm',
      },
      {
        id: 135,
        name: JSON.stringify({
          en: 'Tunisian Dinar',
          de: 'Tunesischer Dinar',
          it: 'Dinaro tunisino',
          ja: 'チュニジアディナール',
          ko: '튀니지 디나르',
          zh: '突尼斯第纳尔',
          pt: 'Dinar tunisino',
          ru: 'Тунисский динар',
          es: 'Dinar tunecino',
          fr: 'Dinar tunisien',
        }),
        abbreviation: 'TND',
        symbol: 'د.ت',
      },
      {
        id: 136,
        name: JSON.stringify({
          en: 'Tongan Paʻanga',
          de: 'Tongaischer Paʻanga',
          it: 'Paʻanga tongano',
          ja: 'トンガパアンガ',
          ko: '통가 파앙가',
          zh: '汤加潘加',
          pt: 'Paʻanga tonganesa',
          ru: 'Тонганская паанга',
          es: 'Paʻanga tongano',
          fr: 'Paʻanga tongan',
        }),
        abbreviation: 'TOP',
        symbol: 'T$',
      },
      {
        id: 137,
        name: JSON.stringify({
          en: 'Turkish Lira',
          de: 'Türkische Lira',
          it: 'Lira turca',
          ja: 'トルコリラ',
          ko: '터키 리라',
          zh: '土耳其里拉',
          pt: 'Lira turca',
          ru: 'Турецкая лира',
          es: 'Lira turca',
          fr: 'Lire turque',
        }),
        abbreviation: 'TRY',
        symbol: '₺',
      },
      {
        id: 138,
        name: JSON.stringify({
          en: 'Trinidad and Tobago Dollar',
          de: 'Trinidad-und-Tobago-Dollar',
          it: 'Dollaro di Trinidad e Tobago',
          ja: 'トリニダード・トバゴドル',
          ko: '트리니다드 토바고 달러',
          zh: '特立尼达和多巴哥元',
          pt: 'Dólar de Trindade e Tobago',
          ru: 'Доллар Тринидада и Тобаго',
          es: 'Dólar de Trinidad y Tobago',
          fr: 'Dollar de Trinité-et-Tobago',
        }),
        abbreviation: 'TTD',
        symbol: 'TT$',
      },
      {
        id: 139,
        name: JSON.stringify({
          en: 'New Taiwan Dollar',
          de: 'Neuer Taiwan-Dollar',
          it: 'Nuovo dollaro taiwanese',
          ja: '新台湾ドル',
          ko: '신 타이완 달러',
          zh: '新台币',
          pt: 'Novo dólar taiwanês',
          ru: 'Новый тайваньский доллар',
          es: 'Nuevo dólar taiwanés',
          fr: 'Nouveau dollar taïwanais',
        }),
        abbreviation: 'TWD',
        symbol: 'NT$',
      },
      {
        id: 140,
        name: JSON.stringify({
          en: 'Tanzanian Shilling',
          de: 'Tansania-Schilling',
          it: 'Scellino tanzaniano',
          ja: 'タンザニアシリング',
          ko: '탄자니아 실링',
          zh: '坦桑尼亚先令',
          pt: 'Xelim tanzaniano',
          ru: 'Танзанийский шиллинг',
          es: 'Chelín tanzano',
          fr: 'Shilling tanzanien',
        }),
        abbreviation: 'TZS',
        symbol: 'TSh',
      },
      {
        id: 141,
        name: JSON.stringify({
          en: 'Ukrainian Hryvnia',
          de: 'Ukrainische Hrywnja',
          it: 'Grivnia ucraina',
          ja: 'ウクライナフリヴニャ',
          ko: '우크라이나 흐리우냐',
          zh: '乌克兰格里夫纳',
          pt: 'Hryvnia ucraniana',
          ru: 'Украинская гривна',
          es: 'Grivna ucraniana',
          fr: 'Hryvnia ukrainienne',
        }),
        abbreviation: 'UAH',
        symbol: '₴',
      },
      {
        id: 142,
        name: JSON.stringify({
          en: 'Ugandan Shilling',
          de: 'Uganda-Schilling',
          it: 'Scellino ugandese',
          ja: 'ウガンダシリング',
          ko: '우간다 실링',
          zh: '乌干达先令',
          pt: 'Xelim ugandense',
          ru: 'Угандийский шиллинг',
          es: 'Chelín ugandés',
          fr: 'Shilling ougandais',
        }),
        abbreviation: 'UGX',
        symbol: 'USh',
      },
      {
        id: 143,
        name: JSON.stringify({
          en: 'United States Dollar',
          de: 'US-Dollar',
          it: 'Dollaro statunitense',
          ja: '米ドル',
          ko: '미국 달러',
          zh: '美元',
          pt: 'Dólar americano',
          ru: 'Доллар США',
          es: 'Dólar estadounidense',
          fr: 'Dollar américain',
        }),
        abbreviation: 'USD',
        symbol: '$',
      },
      {
        id: 144,
        name: JSON.stringify({
          en: 'Uruguayan Peso',
          de: 'Uruguayischer Peso',
          it: 'Peso uruguaiano',
          ja: 'ウルグアイペソ',
          ko: '우루과이 페소',
          zh: '乌拉圭比索',
          pt: 'Peso uruguaio',
          ru: 'Уругвайский песо',
          es: 'Peso uruguayo',
          fr: 'Peso uruguayen',
        }),
        abbreviation: 'UYU',
        symbol: '$',
      },
      {
        id: 145,
        name: JSON.stringify({
          en: 'Uzbekistani Som',
          de: 'Usbekischer Som',
          it: 'Som uzbeko',
          ja: 'ウズベキスタンソム',
          ko: '우즈베키스탄 숨',
          zh: '乌兹别克斯坦苏姆',
          pt: 'Som uzbeque',
          ru: 'Узбекский сум',
          es: 'Som uzbeko',
          fr: 'Som ouzbek',
        }),
        abbreviation: 'UZS',
        symbol: 'сум',
      },
      {
        id: 146,
        name: JSON.stringify({
          en: 'Venezuelan Bolívar',
          de: 'Venezolanischer Bolívar',
          it: 'Bolívar venezuelano',
          ja: 'ベネズエラボリバル',
          ko: '베네수엘라 볼리바르',
          zh: '委内瑞拉玻利瓦尔',
          pt: 'Bolívar venezuelano',
          ru: 'Венесуэльский боливар',
          es: 'Bolívar venezolano',
          fr: 'Bolívar vénézuélien',
        }),
        abbreviation: 'VES',
        symbol: 'Bs.',
      },
      {
        id: 147,
        name: JSON.stringify({
          en: 'Vietnamese Đồng',
          de: 'Vietnamesischer Đồng',
          it: 'Đồng vietnamita',
          ja: 'ベトナムドン',
          ko: '베트남 동',
          zh: '越南盾',
          pt: 'Dồng vietnamita',
          ru: 'Вьетнамский донг',
          es: 'Đồng vietnamita',
          fr: 'Dồng vietnamien',
        }),
        abbreviation: 'VND',
        symbol: '₫',
      },
      {
        id: 148,
        name: JSON.stringify({
          en: 'Vanuatu Vatu',
          de: 'Vanuatu-Vatu',
          it: 'Vatu di Vanuatu',
          ja: 'バヌアツバツ',
          ko: '바누아투 바투',
          zh: '瓦努阿图瓦图',
          pt: 'Vatu de Vanuatu',
          ru: 'Вату Вануату',
          es: 'Vatu de Vanuatu',
          fr: 'Vatu vanuatais',
        }),
        abbreviation: 'VUV',
        symbol: 'Vt',
      },
      {
        id: 149,
        name: JSON.stringify({
          en: 'Samoan Tala',
          de: 'Samoanischer Tala',
          it: 'Tala samoano',
          ja: 'サモアタラ',
          ko: '사모아 탈라',
          zh: '萨摩亚塔拉',
          pt: 'Tala samoano',
          ru: 'Самоанская тала',
          es: 'Tala samoano',
          fr: 'Tala samoan',
        }),
        abbreviation: 'WST',
        symbol: 'T',
      },
      {
        id: 150,
        name: JSON.stringify({
          en: 'Central African CFA Franc',
          de: 'CFA-Franc BEAC',
          it: "Franco CFA dell'Africa Centrale",
          ja: '中央アフリカCFAフラン',
          ko: '중앙아프리카 CFA 프랑',
          zh: '中非法郎',
          pt: 'Franco CFA da África Central',
          ru: 'Франк КФА BEAC',
          es: 'Franco CFA de África Central',
          fr: "Franc CFA d'Afrique centrale",
        }),
        abbreviation: 'XAF',
        symbol: 'FCFA',
      },
      {
        id: 151,
        name: JSON.stringify({
          en: 'East Caribbean Dollar',
          de: 'Ostkaribischer Dollar',
          it: 'Dollaro dei Caraibi Orientali',
          ja: '東カリブドル',
          ko: '동카리브 달러',
          zh: '东加勒比元',
          pt: 'Dólar do Caribe Oriental',
          ru: 'Восточно-карибский доллар',
          es: 'Dólar del Caribe Oriental',
          fr: 'Dollar des Caraïbes orientales',
        }),
        abbreviation: 'XCD',
        symbol: 'EC$',
      },
      {
        id: 152,
        name: JSON.stringify({
          en: 'West African CFA Franc',
          de: 'CFA-Franc BCEAO',
          it: "Franco CFA dell'Africa Occidentale",
          ja: '西アフリカCFAフラン',
          ko: '서아프리카 CFA 프랑',
          zh: '西非法郎',
          pt: 'Franco CFA da África Ocidental',
          ru: 'Франк КФА BCEAO',
          es: 'Franco CFA de África Occidental',
          fr: "Franc CFA d'Afrique de l'Ouest",
        }),
        abbreviation: 'XOF',
        symbol: 'CFA',
      },
      {
        id: 153,
        name: JSON.stringify({
          en: 'CFP Franc',
          de: 'CFP-Franc',
          it: 'Franco CFP',
          ja: 'CFPフラン',
          ko: 'CFP 프랑',
          zh: '太平洋法郎',
          pt: 'Franco CFP',
          ru: 'Франк КФП',
          es: 'Franco CFP',
          fr: 'Franc CFP',
        }),
        abbreviation: 'XPF',
        symbol: '₣',
      },
      {
        id: 154,
        name: JSON.stringify({
          en: 'Yemeni Rial',
          de: 'Jemen-Rial',
          it: 'Rial yemenita',
          ja: 'イエメンリアル',
          ko: '예멘 리얄',
          zh: '也门里亚尔',
          pt: 'Rial iemenita',
          ru: 'Йеменский риал',
          es: 'Rial yemení',
          fr: 'Rial yéménite',
        }),
        abbreviation: 'YER',
        symbol: '﷼',
      },
      {
        id: 155,
        name: JSON.stringify({
          en: 'South African Rand',
          de: 'Südafrikanischer Rand',
          it: 'Rand sudafricano',
          ja: '南アフリカランド',
          ko: '남아프리카 랜드',
          zh: '南非兰特',
          pt: 'Rand sul-africano',
          ru: 'Южноафриканский рэнд',
          es: 'Rand sudafricano',
          fr: 'Rand sud-africain',
        }),
        abbreviation: 'ZAR',
        symbol: 'R',
      },
      {
        id: 156,
        name: JSON.stringify({
          en: 'Zambian Kwacha',
          de: 'Sambischer Kwacha',
          it: 'Kwacha dello Zambia',
          ja: 'ザンビアクワチャ',
          ko: '잠비아 콰차',
          zh: '赞比亚克瓦查',
          pt: 'Kwacha zambiano',
          ru: 'Замбийская квача',
          es: 'Kwacha zambiano',
          fr: 'Kwacha zambien',
        }),
        abbreviation: 'ZMW',
        symbol: 'ZK',
      },
      {
        id: 157,
        name: JSON.stringify({
          en: 'Zimbabwean Dollar',
          de: 'Simbabwe-Dollar',
          it: 'Dollaro dello Zimbabwe',
          ja: 'ジンバブエドル',
          ko: '짐바브웨 달러',
          zh: '津巴布韦元',
          pt: 'Dólar zimbabuense',
          ru: 'Доллар Зимбабве',
          es: 'Dólar zimbabuense',
          fr: 'Dollar zimbabwéen',
        }),
        abbreviation: 'ZWL',
        symbol: 'Z$',
      },
      {
        id: 158,
        name: JSON.stringify({
          en: 'CFA Franc (BCEAO)',
          de: 'CFA-Franc (BCEAO)',
          it: 'Franco CFA (BCEAO)',
          ja: 'CFAフラン (BCEAO)',
          ko: 'CFA 프랑 (BCEAO)',
          zh: '西非经共体法郎',
          pt: 'Franco CFA (BCEAO)',
          ru: 'Франк КФА (BCEAO)',
          es: 'Franco CFA (BCEAO)',
          fr: 'Franc CFA (BCEAO)',
        }),
        abbreviation: 'XOF',
        symbol: 'CFA',
      },
      {
        id: 159,
        name: JSON.stringify({
          en: 'CFA Franc (BEAC)',
          de: 'CFA-Franc (BEAC)',
          it: 'Franco CFA (BEAC)',
          ja: 'CFAフラン (BEAC)',
          ko: 'CFA 프랑 (BEAC)',
          zh: '中非经共体法郎',
          pt: 'Franco CFA (BEAC)',
          ru: 'Франк КФА (BEAC)',
          es: 'Franco CFA (BEAC)',
          fr: 'Franc CFA (BEAC)',
        }),
        abbreviation: 'XAF',
        symbol: 'FCFA',
      },
      // Nuevas monedas agregadas (IDs 160-166)
      {
        id: 160,
        name: JSON.stringify({
          en: 'Faroese Króna',
          de: 'Färöische Krone',
          it: 'Corona delle Fær Øer',
          ja: 'フェロー諸島クローネ',
          ko: '페로 제도 크로나',
          zh: '法罗克朗',
          pt: 'Coroa faroesa',
          ru: 'Фарерская крона',
          es: 'Corona feroesa',
          fr: 'Couronne féroïenne',
        }),
        abbreviation: 'FOK',
        symbol: 'kr',
      },
      {
        id: 161,
        name: JSON.stringify({
          en: 'Manx Pound',
          de: 'Manx-Pfund',
          it: 'Sterlina di Man',
          ja: 'マン島ポンド',
          ko: '맨 섬 파운드',
          zh: '马恩岛镑',
          pt: 'Libra de Man',
          ru: 'Мэнский фунт',
          es: 'Libra de la Isla de Man',
          fr: 'Livre manx',
        }),
        abbreviation: 'IMP',
        symbol: '£',
      },
      {
        id: 162,
        name: JSON.stringify({
          en: 'Jersey Pound',
          de: 'Jersey-Pfund',
          it: 'Sterlina di Jersey',
          ja: 'ジャージーポンド',
          ko: '저지 섬 파운드',
          zh: '泽西镑',
          pt: 'Libra de Jersey',
          ru: 'Джерсийский фунт',
          es: 'Libra de Jersey',
          fr: 'Livre de Jersey',
        }),
        abbreviation: 'JEP',
        symbol: '£',
      },
      {
        id: 163,
        name: JSON.stringify({
          en: 'Kiribati Dollar',
          de: 'Kiribati-Dollar',
          it: 'Dollaro di Kiribati',
          ja: 'キリバスドル',
          ko: '키리바시 달러',
          zh: '基里巴斯元',
          pt: 'Dólar de Kiribati',
          ru: 'Доллар Кирибати',
          es: 'Dólar kiribatiano',
          fr: 'Dollar kiribatien',
        }),
        abbreviation: 'KID',
        symbol: '$',
      },
      {
        id: 164,
        name: JSON.stringify({
          en: 'Tuvaluan Dollar',
          de: 'Tuvalu-Dollar',
          it: 'Dollaro di Tuvalu',
          ja: 'ツバルドル',
          ko: '투발루 달러',
          zh: '图瓦卢元',
          pt: 'Dólar de Tuvalu',
          ru: 'Доллар Тувалу',
          es: 'Dólar tuvaluano',
          fr: 'Dollar tuvaluan',
        }),
        abbreviation: 'TVD',
        symbol: '$',
      },
      {
        id: 165,
        name: JSON.stringify({
          en: 'Cook Islands Dollar',
          de: 'Cookinseln-Dollar',
          it: 'Dollaro delle Isole Cook',
          ja: 'クック諸島ドル',
          ko: '쿡 제도 달러',
          zh: '库克群岛元',
          pt: 'Dólar das Ilhas Cook',
          ru: 'Доллар Островов Кука',
          es: 'Dólar de las Islas Cook',
          fr: 'Dollar des îles Cook',
        }),
        abbreviation: 'CKD',
        symbol: '$',
      },
      {
        id: 166,
        name: JSON.stringify({
          en: 'Niue Dollar',
          de: 'Niue-Dollar',
          it: 'Dollaro di Niue',
          ja: 'ニウエドル',
          ko: '니우에 달러',
          zh: '纽埃元',
          pt: 'Dólar de Niue',
          ru: 'Доллар Ниуэ',
          es: 'Dólar de Niue',
          fr: 'Dollar niuéen',
        }),
        abbreviation: 'NUD',
        symbol: '$',
      },
    ];

    return currencies;
  },

  up: async (queryInterface) => {
    const batchSize = 50;
    const currencies = this.get();

    for (let i = 0; i < currencies.length; i += batchSize) {
      const batch = currencies.slice(i, i + batchSize);
      for (const currency of batch) {
        await queryInterface.bulkInsert('data_currencies', [currency], {
          updateOnDuplicate: ['name', 'abbreviation', 'symbol'],
        });
      }
    }
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('data_currencies', null, {});
  },
};
