module.exports = {
  local: {
    username: 'root',
    password: 'root_password',
    database: 'test_base',
    host: 'localhost',
    dialect: 'mysql',
    port: 3306,
    dialectOptions: {
      decimalNumbers: true,
      timezone: '-05:00',
    },
    charset: 'utf8mb4',
    collate: 'utf8mb4_general_ci',
    timezone: '-05:00',
    pool: {
      max: 1000,
      min: 0,
      idle: 400000,
    },
    logging: false,
  },
  development: {
    username: 'root',
    password: 'root_password',
    database: 'test_base',
    host: 'localhost',
    dialect: 'mysql',
    port: 3306,
    dialectOptions: {
      decimalNumbers: true,
      timezone: '-05:00',
    },
    charset: 'utf8mb4',
    collate: 'utf8mb4_general_ci',
    timezone: '-05:00',
    pool: {
      max: 1000,
      min: 0,
      idle: 400000,
    },
    logging: false,
  },
  test: {
    username: 'root',
    password: 'root_password',
    database: 'test_base',
    host: 'localhost',
    dialect: 'mysql',
    port: 3306,
    dialectOptions: {
      decimalNumbers: true,
      timezone: '-05:00',
    },
    charset: 'utf8mb4',
    collate: 'utf8mb4_general_ci',
    timezone: '-05:00',
    pool: {
      max: 1000,
      min: 0,
      idle: 400000,
    },
    logging: false,
  },
  production: {
    username: 'root',
    password: 'root_password',
    database: 'test_base',
    host: 'localhost',
    dialect: 'mysql',
    port: 3306,
    dialectOptions: {
      decimalNumbers: true,
      timezone: '-05:00',
    },
    charset: 'utf8mb4',
    collate: 'utf8mb4_general_ci',
    timezone: '-05:00',
    pool: {
      max: 1000,
      min: 0,
      idle: 400000,
    },
    logging: false,
  },
};
