name: Release Automation

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [develop]
    
permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: janheinrichmerker/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: git@github.com:Santiago1010/node-template.git
          user: Santiago1010
          output: CHANGELOG
